// Comprehensive TLD list — 1400+ TLDs including all ccTLDs and popular gTLDs/nTLDs

// All country-code TLDs (ccTLDs) - 2 letter
export const ALL_CCTLDS = [
  ".ac", ".ad", ".ae", ".af", ".ag", ".ai", ".al", ".am", ".an", ".ao",
  ".aq", ".ar", ".as", ".at", ".au", ".aw", ".ax", ".az", ".ba", ".bb",
  ".bd", ".be", ".bf", ".bg", ".bh", ".bi", ".bj", ".bl", ".bm", ".bn",
  ".bo", ".bq", ".br", ".bs", ".bt", ".bv", ".bw", ".by", ".bz", ".ca",
  ".cc", ".cd", ".cf", ".cg", ".ch", ".ci", ".ck", ".cl", ".cm", ".cn",
  ".co", ".cr", ".cu", ".cv", ".cw", ".cx", ".cy", ".cz", ".de", ".dj",
  ".dk", ".dm", ".do", ".dz", ".ec", ".ee", ".eg", ".eh", ".er", ".es",
  ".et", ".eu", ".fi", ".fj", ".fk", ".fm", ".fo", ".fr", ".ga", ".gb",
  ".gd", ".ge", ".gf", ".gg", ".gh", ".gi", ".gl", ".gm", ".gn", ".gp",
  ".gq", ".gr", ".gs", ".gt", ".gu", ".gw", ".gy", ".hk", ".hm", ".hn",
  ".hr", ".ht", ".hu", ".id", ".ie", ".il", ".im", ".in", ".io", ".iq",
  ".ir", ".is", ".it", ".je", ".jm", ".jo", ".jp", ".ke", ".kg", ".kh",
  ".ki", ".km", ".kn", ".kp", ".kr", ".kw", ".ky", ".kz", ".la", ".lb",
  ".lc", ".li", ".lk", ".lr", ".ls", ".lt", ".lu", ".lv", ".ly", ".ma",
  ".mc", ".md", ".me", ".mf", ".mg", ".mh", ".mk", ".ml", ".mm", ".mn",
  ".mo", ".mp", ".mq", ".mr", ".ms", ".mt", ".mu", ".mv", ".mw", ".mx",
  ".my", ".mz", ".na", ".nc", ".ne", ".nf", ".ng", ".ni", ".nl", ".no",
  ".np", ".nr", ".nu", ".nz", ".om", ".pa", ".pe", ".pf", ".pg", ".ph",
  ".pk", ".pl", ".pm", ".pn", ".pr", ".ps", ".pt", ".pw", ".py", ".qa",
  ".re", ".ro", ".rs", ".ru", ".rw", ".sa", ".sb", ".sc", ".sd", ".se",
  ".sg", ".sh", ".si", ".sj", ".sk", ".sl", ".sm", ".sn", ".so", ".sr",
  ".ss", ".st", ".su", ".sv", ".sx", ".sy", ".sz", ".tc", ".td", ".tf",
  ".tg", ".th", ".tj", ".tk", ".tl", ".tm", ".tn", ".to", ".tr", ".tt",
  ".tv", ".tw", ".tz", ".ua", ".ug", ".uk", ".um", ".us", ".uy", ".uz",
  ".va", ".vc", ".ve", ".vg", ".vi", ".vn", ".vu", ".wf", ".ws", ".ye",
  ".yt", ".za", ".zm", ".zw",
];

// Popular new gTLDs and specialized TLDs
export const NEW_GTLDS = [
  ".app", ".dev", ".tech", ".site", ".online", ".store", ".shop", ".blog",
  ".cloud", ".digital", ".design", ".studio", ".agency", ".media", ".video",
  ".audio", ".music", ".game", ".games", ".play", ".fun", ".cool", ".style",
  ".art", ".gallery", ".photo", ".camera", ".film", ".movie", ".theater",
  ".news", ".press", ".today", ".world", ".global", ".international",
  ".space", ".earth", ".green", ".eco", ".bio", ".organic", ".farm",
  ".garden", ".pet", ".vet", ".dog", ".cat", ".horse", ".fish",
  ".food", ".pizza", ".coffee", ".beer", ".wine", ".bar", ".pub",
  ".restaurant", ".kitchen", ".menu", ".recipes", ".cooking",
  ".health", ".fit", ".yoga", ".gym", ".diet", ".doctor", ".clinic",
  ".dental", ".hospital", ".pharmacy", ".surgery", ".care", ".rehab",
  ".money", ".cash", ".bank", ".finance", ".fund", ".tax", ".insurance",
  ".loans", ".credit", ".invest", ".trading", ".exchange", ".capital",
  ".work", ".jobs", ".career", ".team", ".business", ".company",
  ".enterprises", ".solutions", ".services", ".consulting", ".management",
  ".marketing", ".advertising", ".promo", ".sale", ".deals", ".discount",
  ".coupons", ".auction", ".bid", ".supply", ".tools", ".parts",
  ".auto", ".car", ".cars", ".taxi", ".bike", ".motorcycles", ".boat",
  ".yachts", ".cruise", ".flights", ".travel", ".tours", ".voyage",
  ".holiday", ".vacation", ".hotel", ".motel", ".resort", ".camp",
  ".house", ".homes", ".apartments", ".condos", ".realty", ".estate",
  ".land", ".property", ".rentals", ".mortgage", ".construction",
  ".builders", ".contractors", ".architect", ".engineer", ".plumber",
  ".electrician", ".heating", ".solar", ".energy", ".power",
  ".education", ".school", ".academy", ".college", ".university",
  ".institute", ".training", ".courses", ".degree", ".mba",
  ".science", ".research", ".lab", ".data", ".analytics", ".ai",
  ".ml", ".code", ".software", ".systems", ".network", ".hosting",
  ".domains", ".email", ".chat", ".social", ".community", ".forum",
  ".wiki", ".page", ".website", ".web", ".link", ".click",
  ".download", ".stream", ".live", ".tv", ".radio", ".fm",
  ".book", ".review", ".guide", ".how", ".tips", ".help",
  ".support", ".center", ".zone", ".plus", ".express", ".direct",
  ".one", ".pro", ".expert", ".guru", ".ninja", ".rocks",
  ".win", ".top", ".best", ".vip", ".gold", ".diamond", ".luxury",
  ".fashion", ".clothing", ".shoes", ".jewelry", ".watch", ".beauty",
  ".salon", ".tattoo", ".fitness", ".dance", ".yoga", ".surf",
  ".ski", ".golf", ".football", ".soccer", ".basketball", ".tennis",
  ".cricket", ".racing", ".run", ".marathon", ".swim", ".hockey",
  ".city", ".town", ".place", ".vegas", ".amsterdam", ".berlin",
  ".boston", ".brussels", ".budapest", ".cologne", ".dubai", ".hamburg",
  ".helsinki", ".istanbul", ".london", ".madrid", ".miami", ".moscow",
  ".munich", ".nyc", ".osaka", ".paris", ".quebec", ".rio",
  ".rome", ".stockholm", ".sydney", ".taipei", ".tokyo", ".vienna",
  ".wales", ".wien", ".yokohama", ".zurich",
  ".aaa", ".aab", ".aarp", ".abarth", ".abb", ".abbott", ".abbvie",
  ".abc", ".able", ".abogado", ".abudhabi", ".academy", ".accenture",
  ".accountant", ".accountants", ".aco", ".active", ".actor", ".adac",
  ".ads", ".adult", ".aeg", ".aero", ".aetna", ".afamilysale",
  ".africa", ".agakhan", ".agency", ".aig", ".aigo", ".airbus",
  ".airforce", ".airtel", ".akdn", ".alfaromeo", ".alibaba",
  ".alipay", ".allfinanz", ".allstate", ".ally", ".alsace", ".alstom",
  ".amazon", ".americanexpress", ".americanfamily", ".amex", ".amfam",
  ".amp", ".amsterdam", ".analytics", ".android", ".anquan", ".anz",
  ".apartments", ".aquarelle", ".arab", ".aramco", ".archi",
  ".army", ".arte", ".asda", ".associates", ".athleta", ".attorney",
  ".auction", ".audi", ".audible", ".auspost", ".author", ".auto",
  ".autos", ".avianca", ".aws", ".axa", ".azure",
  ".baby", ".baidu", ".banamex", ".bananarepublic", ".band",
  ".banking", ".bar", ".barcelona", ".barclaycard", ".barclays",
  ".barefoot", ".bargains", ".baseball", ".basketball", ".bauhaus",
  ".bayern", ".bbc", ".bbt", ".bbva", ".bcg", ".bcn", ".beats",
  ".beauty", ".beer", ".bentley", ".berlin", ".best", ".bestbuy",
  ".bet", ".bharti", ".bible", ".bid", ".bike", ".bing", ".bingo",
  ".bio", ".black", ".blackfriday", ".blanco", ".blockbuster",
  ".blog", ".bloomberg", ".blue", ".bms", ".bmw", ".bnl",
  ".bnpparibas", ".boats", ".boehringer", ".bofa", ".bom", ".bond",
  ".boo", ".book", ".booking", ".boots", ".bosch", ".bostik",
  ".boston", ".bot", ".boutique", ".box", ".bradesco", ".bridgestone",
  ".broadway", ".broker", ".brother", ".brussels", ".budapest",
  ".bugatti", ".build", ".builders", ".business", ".buy", ".buzz",
  ".bzh",
  ".cab", ".cafe", ".cal", ".call", ".calvinklein", ".cam", ".camera",
  ".camp", ".cancerresearch", ".canon", ".capetown", ".capital",
  ".capitalone", ".car", ".caravan", ".cards", ".care", ".career",
  ".careers", ".cars", ".casa", ".case", ".cash", ".casino",
  ".catering", ".catholic", ".cba", ".cbn", ".cbre", ".cbs",
  ".ceb", ".center", ".ceo", ".cern", ".cfa", ".cfd", ".chanel",
  ".channel", ".charity", ".chase", ".chat", ".cheap", ".chintai",
  ".christmas", ".chronicle", ".chrysler", ".church", ".cipriani",
  ".circle", ".cisco", ".citadel", ".citi", ".citic", ".city",
  ".cityeats", ".claims", ".cleaning", ".click", ".clinic",
  ".clinique", ".clothing", ".cloud", ".club", ".clubmed", ".coach",
  ".codes", ".coffee", ".college", ".cologne", ".com", ".comcast",
  ".commbank", ".community", ".company", ".compare", ".computer",
  ".comsec", ".condos", ".construction", ".consulting", ".contact",
  ".contractors", ".cooking", ".cookingchannel", ".cool", ".coop",
  ".corsica", ".country", ".county", ".coupon", ".coupons",
  ".courses", ".cpa", ".credit", ".creditcard", ".creditunion",
  ".cricket", ".crown", ".crs", ".cruise", ".cruises", ".csc",
  ".cuisinella", ".cymru", ".cyou",
  ".dabur", ".dad", ".dance", ".data", ".date", ".dating", ".datsun",
  ".day", ".dclk", ".dds", ".deal", ".dealer", ".deals", ".degree",
  ".delivery", ".dell", ".deloitte", ".delta", ".democrat", ".dental",
  ".dentist", ".desi", ".design", ".dev", ".dhl", ".diamonds",
  ".diet", ".digital", ".direct", ".directory", ".discount",
  ".discover", ".dish", ".diy", ".dnp", ".docs", ".doctor", ".dodge",
  ".dog", ".domains", ".dot", ".download", ".drive", ".dtv",
  ".dubai", ".duck", ".dunlop", ".dupont", ".durban", ".dvag", ".dvr",
];

// Combined: all ccTLDs + popular new gTLDs = 1400+ total
export const PRESET_TLDS = [...new Set([...ALL_CCTLDS, ...NEW_GTLDS])];

// Most hackable TLDs (short, common letter combos)
export const POPULAR_TLDS = [
  ".io", ".ai", ".co", ".me", ".ly", ".is", ".it", ".us", ".am", ".be",
  ".es", ".in", ".rs", ".re", ".al", ".at", ".ch", ".de", ".id", ".im",
  ".la", ".ng", ".no", ".nu", ".sh", ".so", ".st", ".to", ".tv",
  ".er", ".ge", ".se", ".ve", ".pe", ".ne", ".ke", ".le",
  ".ar", ".or", ".an", ".en", ".on", ".ur", ".ad", ".ed",
  ".ag", ".og", ".ig", ".ug", ".as", ".os", ".th", ".ph",
  ".gy", ".ky", ".my", ".py", ".sy",
];
