// Word Library Extra 20 - 6-letter gTLD expansions
// Auto-generated from 370K English word corpus
// 66 TLDs, 621 total words

export const WORD_LIBRARY_EXTRA20: Record<string, string[]> = {
  active: ["factive", "tactive", "coactive", "enactive", "exactive", "inactive", "practive", "reactive", "tractive", "unactive", "didactive", "impactive", "nonactive", "olfactive", "preactive", "proactive", "attractive", "autoactive", "detractive", "extractive", "hypoactive", "omniactive", "overactive", "refractive", "retractive", "semiactive", "unreactive", "vasoactive", "abstractive", "benefactive", "calefactive", "contractive", "diffractive", "distractive", "hyperactive", "interactive", "introactive", "neuroactive", "nonreactive", "photoactive", "protractive", "radioactive", "rarefactive", "retroactive", "subtractive", "superactive", "tumefactive", "vasifactive", "vasofactive", "antireactive", "birefractive", "chylifactive", "liquefactive", "overreactive", "petrifactive", "psychoactive", "putrefactive", "satisfactive", "semelfactive", "stupefactive", "unattractive", "undetractive", "unrefractive", "unretractive", "counteractive", "hyperreactive", "nondetractive", "nonextractive", "nonrefractive", "unabstractive", "undiffractive", "unprotractive", "unradioactive", "unretroactive", "unsubtractive", "immunoreactive", "nondiffractive", "nondistractive", "noninteractive", "nonradioactive", "nonretroactive", "nonsubtractive", "precontractive", "superattractive", "antiputrefactive", "noncounteractive", "resinoextractive", "counterattractive"],
  agency: ["coagency", "reagency", "nonagency", "subagency", "interagency", "superagency", "underagency", "counteragency"],
  amazon: ["stramazon"],
  author: ["coauthor", "proauthor"],
  beauty: ["nonbeauty"],
  berlin: ["kimberlin"],
  broker: ["subbroker", "pawnbroker", "playbroker", "sharebroker", "stockbroker"],
  camera: ["recamera", "aerocamera", "anticamera", "cinecamera", "minicamera", "telecamera", "microcamera", "stereocamera"],
  career: ["noncareer", "aftercareer"],
  casino: ["subcasino"],
  center: ["scenter", "decenter", "encenter", "incenter", "recenter", "uncenter", "apocenter", "concenter", "epicenter", "percenter", "subcenter", "barycenter", "deadcenter", "hypocenter", "indecenter", "innocenter", "metacenter", "pericenter", "orthocenter", "chromocenter", "circumcenter", "spermocenter", "antiepicenter", "prometacenter"],
  church: ["enchurch", "inchurch", "unchurch", "dischurch", "nonchurch", "prochurch", "antechurch", "antichurch", "forechurch", "overchurch", "afterchurch", "interchurch"],
  circle: ["encircle", "excircle", "incircle", "recircle", "demicircle", "hemicircle", "semicircle", "intercircle", "undercircle", "circumcircle"],
  claims: ["acclaims", "declaims", "exclaims", "reclaims", "disclaims", "misclaims", "proclaims", "quitclaims", "counterclaims"],
  clinic: ["aclinic", "diclinic", "isoclinic", "triclinic", "monoclinic", "policlinic", "polyclinic", "goneoclinic", "matroclinic", "patroclinic", "psychoclinic", "pseudomonoclinic"],
  county: ["noncounty", "viscounty", "intercounty"],
  credit: ["accredit", "recredit", "uncredit", "concredit", "discredit", "miscredit", "noncredit", "precredit", "overcredit", "reaccredit", "disaccredit", "preaccredit", "supercredit"],
  dating: ["iodating", "redating", "sedating", "updating", "amidating", "gradating", "mandating", "misdating", "outdating", "oxidating", "predating", "subdating", "antedating", "backdating", "denudating", "emendating", "foredating", "inundating", "lapidating", "postdating", "solidating", "validating", "candidating", "depredating", "elucidating", "fecundating", "liquidating", "radiodating", "regradating", "ungradating", "dilapidating", "fluoridating", "intimidating", "invalidating", "nonoxidating", "revalidating", "unvalidating", "accommodating", "consolidating", "reliquidating", "unelucidating", "unliquidating", "cantharidating", "nonelucidating", "nonliquidating", "preliquidating", "subinfeudating", "unintimidating", "reaccommodating", "reconsolidating", "unaccommodating", "unconsolidating", "nonaccommodating", "preaccommodating", "preconsolidating", "superaccommodating"],
  dealer: ["misdealer", "nondealer", "predealer", "subdealer", "bookdealer", "coaldealer", "junkdealer", "newsdealer", "interdealer", "underdealer"],
  degree: ["predegree", "millidegree"],
  dental: ["edental", "bidental", "predental", "tridental", "accidental", "incidental", "occidental", "paradental", "peridental", "polydental", "postdental", "residental", "interdental", "labiodental", "supradental", "antecedental", "coincidental", "descendental", "linguadental", "linguidental", "linguodental", "medicodental", "palatodental", "unaccidental", "unincidental", "unoccidental", "alveolodental", "maxillodental", "nonaccidental", "nonincidental", "nonoccidental", "nonresidental", "preaccidental", "transcendental", "uncoincidental", "noncoincidental", "pseudoaccidental", "pseudooccidental", "untranscendental"],
  design: ["undesign", "predesign", "foredesign"],
  direct: ["codirect", "undirect", "predirect", "unidirect", "semidirect"],
  doctor: ["bedoctor", "undoctor", "subdoctor", "demidoctor", "paradoctor", "superdoctor", "underdoctor"],
  energy: ["telenergy", "counterenergy"],
  equity: ["inequity", "obsequity", "preequity"],
  estate: ["gestate", "restate", "testate", "coestate", "prestate", "forestate", "intestate", "potestate", "untestate", "contestate", "realestate", "abintestate", "dehonestate"],
  events: ["prevents", "misevents", "nonevents"],
  expert: ["inexpert", "unexpert", "nonexpert", "proexpert", "overexpert"],
  family: ["nonfamily", "subfamily", "interfamily", "multifamily", "superfamily"],
  garden: ["antegarden"],
  giving: ["ingiving", "regiving", "ungiving", "forgiving", "lawgiving", "misgiving", "outgiving", "almsgiving", "gaingiving", "ringgiving", "bribegiving", "unforgiving", "unmisgiving", "nonforgiving", "preforgiving", "thanksgiving", "foremisgiving"],
  health: ["unhealth", "subhealth", "soulhealth"],
  hermes: ["chermes", "thermes"],
  insure: ["coinsure", "reinsure", "disinsure", "preinsure", "overinsure"],
  invest: ["reinvest", "disinvest", "preinvest", "overinvest"],
  jaguar: ["werejaguar"],
  kinder: ["unkinder", "gavelkinder", "wunderkinder"],
  kindle: ["akindle", "enkindle", "inkindle", "rekindle", "upkindle", "miskindle", "prekindle"],
  kosher: ["unkosher", "nonkosher"],
  lawyer: ["nonlawyer", "demilawyer", "underlawyer"],
  luxury: ["semiluxury"],
  market: ["remarket", "dismarket", "haymarket", "newmarket", "nonmarket", "aftermarket"],
  mobile: ["immobile", "unmobile", "airmobile", "artmobile", "nonmobile", "skimobile", "automobile", "bookmobile", "clubmobile", "locomobile", "oldsmobile", "pushmobile", "semimobile", "snowmobile", "traymobile", "bloodmobile", "radiomobile", "sensomobile", "skatemobile", "electromobile", "proautomobile"],
  mutual: ["immutual", "unmutual", "commutual", "nonmutual", "intermutual", "transmutual"],
  office: ["outoffice", "suboffice", "postoffice", "interoffice", "intraoffice"],
  oracle: ["coracle"],
  orange: ["sporange", "oosporange", "zoosporange", "megasporange", "zygosporange", "macrosporange", "microsporange", "tetrasporange", "trichosporange"],
  photos: ["aerophotos", "wirephotos"],
  racing: ["bracing", "gracing", "tracing", "embracing", "engracing", "outracing", "preracing", "proracing", "rebracing", "retracing", "terracing", "unbracing", "antiracing", "disgracing", "mistracing", "pretracing", "overbracing", "reembracing", "windbracing", "intertracing", "underbracing", "counterbracing", "interembracing"],
  resort: ["coresort", "preresort"],
  review: ["preview", "foreview", "prereview"],
  safety: ["insafety", "unsafety", "firesafety", "supersafety"],
  school: ["deschool", "reschool", "unschool", "proschool", "subschool", "antischool", "foreschool", "highschool", "playschool", "postschool", "extraschool", "interschool", "intraschool", "underschool"],
  secure: ["assecure", "insecure", "resecure", "unsecure", "presecure", "oversecure", "supersecure", "countersecure"],
  social: ["asocial", "insocial", "dissocial", "nonsocial", "subsocial", "oversocial", "semisocial", "extrasocial", "intersocial", "pathosocial", "protosocial", "cancrisocial", "ethicosocial", "pseudosocial", "physicosocial"],
  sports: ["disports", "gosports", "passports", "transports", "spoilsports"],
  stream: ["astream", "bestream", "distream", "restream", "upstream", "airstream", "jetstream", "midstream", "outstream", "substream", "amidstream", "downstream", "headstream", "mainstream", "millstream", "overstream", "slipstream", "windstream", "bloodstream", "interstream", "thirdstream", "understream", "counterstream"],
  supply: ["resupply", "unsupply", "presupply", "oversupply", "undersupply"],
  target: ["nontarget", "subtarget"],
  tattoo: ["rattattoo"],
  travel: ["betravel", "retravel", "outtravel", "pretravel", "protravel", "overtravel"],
  virgin: ["unvirgin", "demivirgin"],
  vision: ["avision", "division", "envision", "invision", "revision", "unvision", "prevision", "provision", "audivision", "forevision", "indivision", "omnivision", "redivision", "television", "aftervision", "condivision", "imprevision", "improvision", "introvision", "misdivision", "noctovision", "nondivision", "nonrevision", "predivision", "prerevision", "prodivision", "prorevision", "radiovision", "reprovision", "retrovision", "subdivision", "supervision", "unprovision", "equidivision", "preprovision", "semidivision", "stereovision", "stratovision", "foreprovision", "hyperdivision", "interdivision", "overprovision", "superdivision", "nonsupervision", "presupervision", "prosupervision"],
  voting: ["devoting", "pivoting", "revoting", "unvoting", "nonvoting", "outvoting", "prevoting", "overvoting"],
  voyage: ["revoyage", "outvoyage"],
};
