// Large flat English word corpus for domain hack generation
// Auto-indexed at load time against ALL TLDs — covers every suffix automatically

export const WORD_CORPUS: string[] = [
  // ── Domain / Tech / Internet ──────────────────────────────────────────
  "digital","virtual","network","connect","cloud","stream","mobile","global",
  "social","channel","platform","portal","online","download","upload","install",
  "software","hardware","firmware","interface","framework","algorithm","database",
  "analytics","dashboard","protocol","encrypt","secure","firewall","antivirus",
  "blockchain","crypto","token","wallet","exchange","startup","unicorn","venture",
  "domain","hosting","server","client","proxy","router","bandwidth","uptime",
  "devops","agile","scrum","deploy","pipeline","api","webhook","endpoint",
  "frontend","backend","fullstack","javascript","typescript","python","golang",
  "docker","kubernetes","linux","ubuntu","chatbot","robot","automation","machine",
  "neural","vision","speech","pixel","render","vector","canvas","search","index",
  "crawl","parse","query","cache","session","cookie","oauth","email","inbox",
  "message","chat","forum","blog","article","publish","post","comment","reply",
  "share","follow","subscribe","newsletter","campaign","landing","conversion",
  "funnel","traffic","ranking","metric","insight","report","monitor","alert",
  "trigger","workflow","automate","template","widget","plugin","extension","addon",
  "version","release","changelog","commit","branch","merge","debug","test","review",
  "feedback","iterate","terminal","console","kernel","binary","compile","runtime",
  "interpreter","debugger","profiler","linter","formatter","bundler","minifier",
  "optimizer","compressor","encoder","decoder","serializer","parser","tokenizer",
  "scheduler","dispatcher","middleware","gateway","loadbalancer","orchestrator",
  "container","sandbox","virtual","emulator","simulator","replica","mirror","shard",
  "cluster","partition","segment","bucket","namespace","registry","repository",
  "snapshot","backup","restore","failover","replication","sharding","indexing",
  "caching","queuing","streaming","batching","throttling","rate","limit","quota",
  "authentication","authorization","permission","role","policy","credential",
  "certificate","signature","checksum","hash","digest","nonce","entropy","cipher",
  "symmetric","asymmetric","public","private","key","secret","vault","keystore",

  // ── Business & Finance ────────────────────────────────────────────────
  "business","company","corporate","enterprise","industry","brand","market",
  "product","service","solution","customer","client","partner","vendor","supplier",
  "revenue","profit","margin","budget","finance","invest","fund","grant","loan",
  "credit","debit","payment","transaction","invoice","receipt","billing","bank",
  "insurance","mortgage","interest","dividend","stock","bond","equity","asset",
  "liability","trade","export","import","logistics","supply","retail","wholesale",
  "franchise","license","patent","trademark","copyright","legal","compliance","audit",
  "strategy","roadmap","milestone","goal","objective","launch","scale","expand",
  "acquire","merge","compete","disrupt","innovate","transform","optimize",
  "accelerate","activate","affiliate","aggregate","allocate","amplify","animate",
  "annotate","anticipate","appreciate","articulate","authenticate","calibrate",
  "calculate","capitalize","celebrate","collaborate","communicate","compensate",
  "concentrate","consolidate","coordinate","delegate","demonstrate","differentiate",
  "duplicate","elaborate","eliminate","evaluate","facilitate","formulate","generate",
  "illustrate","integrate","investigate","iterate","leverage","migrate","navigate",
  "negotiate","operate","orchestrate","participate","populate","regulate","simulate",
  "syndicate","terminate","translate","validate","visualize","monetize","prioritize",
  "categorize","summarize","recognize","specialize","initialize","stabilize",
  "mobilize","utilize","finalize","sanitize","customize","emphasize","organize",
  "analyze","maximize","minimize","synthesize","optimize","realize","materialize",
  "internationalize","capitalize","digitalize","operationalize","commercialize",

  // ── Words ending in .ai ───────────────────────────────────────────────
  "bonsai","samurai","thai","chai","dubai","sinai","bikini","tsunami",
  "origami","wasabi","sushi","umami","safari","broccoli","alibi","khaki",
  "cacti","fungi","alumni","stimuli","syllabi","radii","octopi","hippopotami",
  "hawaii","bahrain","cocktail","detail","retail","entail","curtail","derail",
  "email","gmail","blackmail","voicemail","snail","trail","prevail","avail",
  "assail","regail","travail","cocktail","ponytail","thumbnail","fantail",
  "dovetail","ringtail","cottontail","monorail","handrail",

  // ── Words ending in .io ───────────────────────────────────────────────
  "radio","studio","audio","patio","ratio","trio","scenario","portfolio","folio",
  "mario","oratorio","portfolio","pistachio","scenario","capriccio","fiorio",
  "impresario","virtuosio","romeo","rodeo","cameo","video","stereo","tattoo",

  // ── Words ending in .co ───────────────────────────────────────────────
  "cisco","disco","eco","poco","taco","calico","portico","stucco","fiasco",
  "tobacco","morocco","frisco","alco","narco","barco","greco","psycho",
  "gecko","picasso","rococo","flamenko","magneto","incognito",

  // ── Words ending in .me ───────────────────────────────────────────────
  "home","name","game","fame","time","rhyme","theme","scheme","extreme","supreme",
  "welcome","awesome","become","outcome","handsome","syndrome","genome","chrome",
  "dome","costume","resume","perfume","volume","consume","assume","presume",
  "income","overcome","username","nickname","surname","hostname","fullname",
  "frame","blame","flame","claim","tame","same","shame","overtime","sometime",
  "halftime","wartime","peacetime","bedtime","daytime","nighttime","lifetime",
  "longtime","pastime","springtime","summertime","wintertime","anytime","lunchtime",
  "overtime","prime","crime","climb","dime","lime","mime","slime","sublime",
  "paradigme","regime","programme","nickname","rename","domain",

  // ── Words ending in .us ───────────────────────────────────────────────
  "bonus","campus","focus","nexus","virus","status","circus","plus","minus",
  "census","genius","famous","various","previous","curious","glorious","obvious",
  "serious","numerous","nervous","dangerous","generous","enormous","vigorous",
  "laborious","notorious","prosperous","adventurous","ambitious","outrageous",
  "gorgeous","glamorous","humorous","fabulous","marvelous","wondrous","zealous",
  "jealous","callous","porous","luminous","venomous","unanimous","spontaneous",
  "extraneous","hiatus","apparatus","stratus","impetus","prospectus","syllabus",
  "omnibus","cactus","octopus","platypus","hippopotamus","exodus","radius","sinus",
  "ruckus","caucus","lexus","versus","consensus","rebus","nimbus","cumulus",
  "stimulus","calculus","modulus","animus","corpus","locus","clamorous","murderous",
  "thunderous","treacherous","monstrous","hazardous","ridiculous","miraculous",
  "tremendous","stupendous","horrendous","tremendous","rebellious","industrious",
  "victorious","glorious","ceremonious","harmonious","felonious","erroneous",
  "aquarius","libras","pisces","aries","taurus","geminus","cancer","virgo",
  "scorpius","sagittarius","capricornus",

  // ── Words ending in .is ───────────────────────────────────────────────
  "basis","axis","crisis","thesis","oasis","analysis","synthesis","emphasis",
  "diagnosis","praxis","nemesis","genesis","alexis","iris","otis","travis",
  "davis","mavis","artemis","atlantis","anubis","paris","aegis","marquis",
  "ibis","tiramisu","status","lotus","nexus","radius","hiatus",

  // ── Words ending in .it ───────────────────────────────────────────────
  "profit","benefit","submit","permit","commit","spirit","rabbit","orbit",
  "credit","visit","merit","limit","unit","audit","habit","exit","edit",
  "outfit","digit","forfeit","circuit","deficit","explicit","implicit","tacit",
  "legit","transmit","emit","omit","admit","summit","vomit","split","grit",
  "knit","quit","spit","skit","wit","fit","hit","kit","sit","bit","lit",
  "counterfit","acquit","remit","permit","submit","admit","omit","commit",
  "transmit","befit","misfit","retrofit","outwit","cockpit","armpit","sandpit",

  // ── Words ending in .at ───────────────────────────────────────────────
  "bat","cat","fat","hat","mat","pat","rat","sat","vat","brat","flat","chat",
  "that","what","squat","combat","format","habitat","wombat","acrobat",
  "democrat","bureaucrat","technocrat","diplomat","muscat","doormat","muskrat",
  "laundromat","autocrat","aristocrat","plutocrat","meritocrat","autocrat",
  "technocrat","ziggurat","loquat","begat","expat","caveat","habitat",

  // ── Words ending in .de ───────────────────────────────────────────────
  "arcade","cascade","decade","facade","grade","trade","blade","shade","spade",
  "jade","made","wade","fade","pride","bride","guide","ride","hide","side",
  "tide","wide","mode","code","rode","node","erode","decode","upgrade","blockade",
  "lemonade","serenade","grenade","promenade","escapade","masquerade","tirade",
  "accolade","barricade","charade","brigade","crusade","include","exclude",
  "conclude","preclude","intrude","extrude","protrude","attitude","altitude",
  "longitude","latitude","gratitude","magnitude","amplitude","solitude",
  "multitude","plenitude","certitude","fortitude","beatitude","beside","divide",
  "reside","abide","provide","decide","inside","outside","worldwide","override",
  "episode","explode","erode","corrode","commode","anode","electrode","diode",
  "triode","cathode","episode","abode","strode","overrode","encode","decode",
  "downgrade","retrograde","lemonade","escapade","marmalade","stockade","cascade",

  // ── Words ending in .go ───────────────────────────────────────────────
  "ego","ago","cargo","embargo","ergo","logo","mango","tango","vertigo","lingo",
  "bingo","dingo","mongo","gringo","flamingo","archipelago","amigo","forego",
  "indigo","Diego","jingo","farrago","virago","imago","virago","archipelago",

  // ── Words ending in .no ───────────────────────────────────────────────
  "piano","soprano","casino","volcano","rhino","neutrino","bambino","cappuccino",
  "filipino","techno","dynamo","espresso","inferno","soprano","albino","flamenko",
  "concertino","palomino","merino","camino","provino","andino",

  // ── Words ending in .to ───────────────────────────────────────────────
  "auto","photo","into","onto","canto","grotto","lotto","motto","gusto","presto",
  "burrito","risotto","mosquito","bandito","incognito","vibrato","staccato",
  "manifesto","concerto","allegretto","pizzicato","tomato","potato","falsetto",
  "stiletto","libretto","spaghetto","amaretto","cornetto","ghetto","grotto",
  "lotto","motto","risotto","filet","corvetto","vignette","roulette",

  // ── Words ending in .do ───────────────────────────────────────────────
  "judo","pseudo","credo","libido","torpedo","avocado","desperado","bravado",
  "tornado","nintendo","aikido","bushido","armado","colorado","eldorado",
  "mikado","commando","innuendo","innuendo","dynamo","placebo","placido",

  // ── Words ending in .so ───────────────────────────────────────────────
  "also","verso","torso","espresso","basso","virtuoso","peso","corso","russo",
  "grosso","capresso","concierge","tableau","bordeaux",

  // ── Words ending in .am ───────────────────────────────────────────────
  "dream","stream","team","cream","beam","foam","exam","telegram","program",
  "hologram","monogram","anagram","slam","clam","ram","ham","jam","dam","yam",
  "tram","pram","scam","sham","spam","cram","dram","madam","islam","imam",
  "panorama","instagram","cryptogram","diagram","cardiogram","electrocardiogram",
  "pictogram","ideogram","pictogram","aerogram","pentagram","hexagram","epigram",
  "program","reogram","sidestream","upstream","downstream","mainstream","livestream",
  "brainstorm",

  // ── Words ending in .st ───────────────────────────────────────────────
  "best","rest","test","west","nest","pest","vest","zest","chest","crest","quest",
  "gust","dust","bust","just","must","rust","trust","thrust","fist","list","mist",
  "wrist","exist","assist","persist","resist","consist","insist","artist","botanist",
  "chemist","cyclist","dentist","feminist","linguist","optimist","pacifist","pianist",
  "scientist","socialist","tourist","vocalist","broadcast","podcast","forecast",
  "contrast","outcast","typecast","downcast","overcast","steadfast","outlast",
  "vast","fast","last","past","cast","mast","blast","cost","host","most","post",
  "lost","frost","ghost","roast","toast","coast","boast","activist","specialist",
  "journalist","communist","physicist","geologist","biologist","economist",
  "capitalist","anarchist","perfectionist","impressionist","expressionist",
  "modernist","traditionalist","rationalist","finalist","finalist","naturalist",
  "realist","idealist","minimalist","maximalist","universalist","individualist",
  "functionalist","structuralist","environmentalist","nationalist","internationalist",

  // ── Words ending in .be ───────────────────────────────────────────────
  "vibe","tribe","describe","subscribe","ascribe","prescribe","globe","probe",
  "robe","lobe","tube","cube","lube","babe","scribe","diatribe","imbibe",
  "transcribe","inscribe","circumscribe","proscribe","microbe","wardrobe",
  "strobe","phobe","bribe","snob","job","mob","knob","blob","throb",

  // ── Words ending in .im ───────────────────────────────────────────────
  "slim","trim","swim","him","dim","rim","vim","whim","brim","grim","prim",
  "skim","interim","pilgrim","maximum","minimum","medium","premium","quantum",
  "optimum","minimum","stadium","forum","podium","atrium","radium","helium",
  "lithium","calcium","sodium","potassium","magnesium","aluminum","titanium",
  "platinum","chromium","uranium","plutonium","beryllium","selenium","tellurium",

  // ── Words ending in .or ───────────────────────────────────────────────
  "actor","color","favor","floor","labor","major","manor","minor","mirror",
  "motor","sector","senior","tenor","tumor","tutor","vapor","vector","vendor",
  "honor","humor","rumor","error","terror","horror","author","anchor","armor",
  "arbor","harbor","neighbor","sponsor","mentor","monitor","senator","governor",
  "professor","processor","successor","predecessor","investor","contractor",
  "administrator","educator","moderator","coordinator","collaborator","innovator",
  "navigator","calculator","generator","creator","operator","mediator","negotiator",
  "decorator","translator","demonstrator","investigator","communicator","facilitator",
  "accelerator","administrator","collaborator","aggregator","orchestrator",
  "interpreter","inspector","director","collector","conductor","detector","selector",
  "connector","protector","corrector","projector","reflector","transmitter","visitor",
  "auditor","creditor","editor","debtor","senator","rector","factor","doctor",
  "corridor","ambassador","bachelor","chancellor","bachelor",

  // ── Words ending in .er ───────────────────────────────────────────────
  "water","better","power","player","maker","builder","leader","teacher","manager",
  "developer","designer","creator","founder","partner","server","layer","filter",
  "handler","provider","subscriber","customer","speaker","blogger","hacker",
  "tracker","crawler","starter","broker","trader","investor","banker","lender",
  "writer","editor","publisher","reporter","producer","director","inspector",
  "controller","processor","computer","router","printer","scanner","reader",
  "listener","streamer","gamer","coder","reviewer","user","viewer","driver",
  "runner","winner","helper","timer","counter","holder","sender","receiver",
  "connector","detector","collector","selector","optimizer","minimizer",
  "maximizer","synthesizer","analyzer","summarizer","organizer","visualizer",
  "weather","winter","summer","flower","tower","wonder","thunder","render",
  "tender","gender","center","enter","vector","transfer","chapter","master",
  "disaster","cluster","register","reminder","cylinder","calendar","hunger",
  "anger","danger","stranger","stronger","younger","longer","higher","lighter",
  "faster","smaller","larger","harder","smarter","cheaper","deeper","softer",
  "cleaner","greener","cooler","warmer","quieter","louder","closer","further",
  "december","november","october","september","ember","timber","lumber","slumber",
  "number","plumber","cucumber","remember","gather","whether","father","mother",
  "brother","together","another","carpenter","interpreter","messenger","volunteer",
  "engineer","pioneer","profiteer","volunteer","customer","consumer","subscriber",

  // ── Words ending in .al ───────────────────────────────────────────────
  "local","global","social","moral","portal","total","digital","virtual","animal",
  "journal","signal","natural","neural","visual","manual","mutual","final","vital",
  "trial","denial","arrival","survival","proposal","disposal","removal","approval",
  "renewal","individual","universal","professional","emotional","rational","optional",
  "additional","traditional","educational","organizational","informational",
  "original","functional","structural","cultural","political","technical","critical",
  "practical","logical","ethical","typical","musical","physical","medical","surgical",
  "chemical","biological","ecological","geological","astronomical","mathematical",
  "philosophical","psychological","sociological","horizontal","vertical","diagonal",
  "central","lateral","federal","general","liberal","mineral","several","material",
  "editorial","tutorial","memorial","electoral","doctoral","pastoral","inaugural",
  "temporal","spiritual","annual","actual","equal","casual","usual","gradual",
  "virtual","factual","ritual","textual","eventual","intellectual","conceptual",
  "perpetual","contractual","contextual","perceptual","medal","pedal","spiral",
  "oval","rival","naval","royal","loyal","real","ideal","deal","appeal","ordeal",
  "reveal","steal","seal","heal","meal","peal","zeal","surreal","unreal","ideal",
  "commercial","financial","international","national","regional","provincial",
  "experimental","environmental","constitutional","institutional","fundamental",
  "instrumental","monumental","elemental","accidental","incidental","coincidental",
  "confidential","residential","presidential","credential","potential","essential",
  "differential","referential","existential","sequential","consequential",
  "substantial","circumstantial","controversial","adversarial","memorial","tutorial",
  "pictorial","sectorial","factorial","oratorial","editorial","territorial",

  // ── Words ending in .en ───────────────────────────────────────────────
  "open","even","seven","given","driven","written","frozen","broken","chosen",
  "woken","stolen","spoken","garden","golden","wooden","linen","kitchen","chicken",
  "happen","sharpen","strengthen","broaden","widen","often","listen","fasten",
  "glisten","hasten","lengthen","tighten","frighten","enlighten","brighten",
  "whiten","darken","deepen","weaken","sweeten","women","men","ten","hen","pen",
  "den","yen","zen","citizen","children","ashen","beaten","bitten","rotten",
  "gotten","forgotten","cotton","button","oxygen","nitrogen","hydrogen","silicon",
  "carbon","electron","neutron","proton","photon","open","eleven","heaven","seven",
  "pollen","frozen","dozen","often","woolen","lessen","raven","graven","shaven",
  "haven","maven","even","uneven","woven","proven","riven","striven","driven",
  "laden","maiden","maiden","leaden","threaten","sweeten","beaten","steepen",

  // ── Words ending in .on ───────────────────────────────────────────────
  "common","option","action","section","mention","question","solution","position",
  "function","relation","condition","connection","direction","production",
  "collection","selection","election","perfection","detection","correction",
  "protection","reflection","infection","injection","rejection","projection",
  "construction","destruction","instruction","introduction","reduction","seduction",
  "induction","conduction","automation","information","education","communication",
  "organization","administration","demonstration","observation","reservation",
  "preservation","conservation","transformation","formation","confirmation",
  "definition","nutrition","ambition","coalition","competition","recognition",
  "opposition","permission","commission","emission","omission","submission",
  "transmission","admission","petition","edition","addition","tradition","decision",
  "invasion","occasion","expansion","compression","session","mission","vision",
  "division","passion","reason","season","prison","lesson","person","horizon",
  "crimson","bison","poison","amazon","marathon","python","skeleton","phenomenon",
  "criterion","icon","falcon","bacon","beacon","lemon","demon","baton","button",
  "cotton","mutton","dragon","wagon","pentagon","hexagon","polygon","salon","canon",
  "ribbon","carbon","silicon","neon","xenon","argon","boron","radon","hereon",
  "thereon","whereon","skeleton","marathon","epsilon","criterion","phenomenon",
  "accordion","medallion","battalion","medallion","vermilion","pavilion","billion",
  "trillion","million","zillion","stallion","scallion","opinion","dominion","minion",
  "union","onion","reunion","communion","companion","champion","scorpion","clarion",
  "version","pension","tension","dimension","extension","comprehension","suspension",
  "apprehension","pretension","intervention","convention","prevention","attention",
  "invention","intention","detention","retention","contention","dissension",
  "citation","nation","station","creation","location","vacation","radiation",
  "graduation","situation","regulation","population","reputation","foundation",
  "donation","pollution","evolution","revolution","resolution","dissolution",
  "constitution","institution","substitution","contribution","distribution",
  "retribution","attribution","solution","execution","prosecution","persecution",

  // ── Words ending in .nd ───────────────────────────────────────────────
  "hand","land","band","sand","brand","grand","expand","command","demand",
  "understand","withstand","blend","friend","lend","send","spend","tend","trend",
  "extend","defend","offend","depend","recommend","dividend","second","thousand",
  "beyond","background","foreground","playground","compound","surround","profound",
  "abound","confound","astound","bound","found","ground","mound","pound","round",
  "sound","wound","around","rebound","beyond","bond","fond","pond","respond",
  "correspond","diamond","Oakland","island","mainland","overland","wonderland",
  "homeland","marshland","farmland","wetland","highland","lowland","midland",
  "portland","scotland","finland","england","ireland","zealand","thailand",
  "iceland","greenland","disneyland","woodland","upland","garland","heartland",
  "badland","farmland","wasteland","dreamland","fairyland","cloud","behind","bind",
  "blind","find","grind","kind","mind","wind","remind","mankind","defined","behind",
  "combined","designed","refined","aligned","assigned","resigned","confined","declined",

  // ── Words ending in .ng ───────────────────────────────────────────────
  "long","song","strong","king","ring","sing","thing","bring","string","swing",
  "spring","morning","evening","coming","going","being","using","having","taking",
  "making","giving","getting","saying","showing","calling","feeling","keeping",
  "leading","moving","building","changing","working","thinking","learning",
  "helping","creating","starting","running","testing","developing","designing",
  "planning","managing","growing","funding","marketing","launching","scaling",
  "coding","debugging","reviewing","deploying","monitoring","banking","trading",
  "investing","shopping","booking","gaming","streaming","messaging","searching",
  "sharing","tracking","ranking","indexing","caching","hosting","networking",
  "computing","programming","engineering","collaborating","mentoring","coaching",
  "consulting","freelancing","blogging","podcasting","vlogging","mapping","mining",
  "dining","teaching","reaching","drinking","thinking","breathing","speaking",
  "hiking","biking","surfing","reading","writing","painting","singing","dancing",

  // ── Words ending in .art ─────────────────────────────────────────────
  "heart","start","smart","cart","dart","part","tart","mart","restart",
  "counterpart","depart","apart","impart","upstart","kickstart","walmart",
  "flipchart","multipart","sweetheart","braveheart","lionheart","oxcart",
  "rampart","bulwark","stockmart","bookmark",

  // ── Words ending in .ink ─────────────────────────────────────────────
  "think","drink","link","rink","wink","brink","blink","shrink","stink","kink",
  "pink","sink","zinc","rethink","hotlink","hyperlink","deeplink","interlink",
  "outthink","overthink","crosslink","sidelink",

  // ── Words ending in .one ─────────────────────────────────────────────
  "phone","zone","bone","tone","stone","alone","clone","done","gone","cone",
  "drone","hone","lone","prone","throne","milestone","cornerstone","limestone",
  "keystone","earphone","microphone","saxophone","trombone","hormone","chromosome",
  "cyclone","ozone","everyone","someone","anyone","backbone","jawbone","wishbone",
  "headphone","smartphone","iphone","ringtone","monotone","overtone","undertone",
  "capstone","sandstone","cobblestone","brownstone","grindstone","millstone",
  "flagstone","cobblestone","gemstone","touchstone","turnstone","gravestone",
  "shinbone","cheekbone","tailbone","kneecap","kneecap","jawbone","hipbone",
  "trombone","collarbone","anklebone","thighbone","tailbone",

  // ── Words ending in .map ─────────────────────────────────────────────
  "roadmap","sitemap","heatmap","mindmap","bitmap","basemap","thumbnail",

  // ── Words ending in .run ─────────────────────────────────────────────
  "outrun","rerun","homerun","sunrun","dryrun","shortrun","longrun","endrun",

  // ── Words ending in .law ─────────────────────────────────────────────
  "inlaw","bylaw","outlaw","gunlaw","lawlaw","claw","draw","flaw","gnaw","jaw",
  "maw","paw","raw","saw","thaw","yaw","bylaw","outlaw","inlaw","ripsaw","hacksaw",
  "jigsaw","seesaw","handsaw","crossbow","rainbow","elbow","sparrow","arrow",
  "narrow","barrow","harrow","marrow","farrow","yarrow","meadow","shadow","widow",

  // ── Words ending in .new ─────────────────────────────────────────────
  "anew","renew","sinew","interview","overview","review","preview","preview",
  "worldview","birdview","longview","shortview",

  // ── Words ending in .win ─────────────────────────────────────────────
  "darwin","irwin","twin","unwin","erwin","baldwin","edwin","kevin","marvin",
  "devin","calvin","gavin","kelvin","alvin","melvin","sherwin","goodwin","sherwin",

  // ── Words ending in .dog ─────────────────────────────────────────────
  "hotdog","bulldog","sheepdog","watchdog","underdog","catalog","dialog","monolog",
  "prolog","epilog","analog","datalog","changelog","backlog","weblog","podcast",

  // ── Words ending in .cat ─────────────────────────────────────────────
  "wildcat","bobcat","tomcat","muscat","alleycat","copycat","aristocat","polecat",
  "meerkat","combat","acrobat","diplomat","democrat","technocrat","bureaucrat",

  // ── Words ending in .fit ─────────────────────────────────────────────
  "outfit","benefit","profit","misfit","retrofit","counterfit","benefit","legit",

  // ── Words ending in .tech ────────────────────────────────────────────
  "edtech","fintech","biotech","cleantech","medtech","proptech","legaltech",
  "insurtech","adtech","regtech","agritech","govtech","hrtech","martech",
  "climatetech","deeptech","nanotech","greentech","infotech","hightech","logitech",

  // ── Words ending in .net ─────────────────────────────────────────────
  "internet","dragnet","fishnet","hairnet","cabinet","clarinet","coronet",
  "bayonet","sonnet","planet","magnet","wicket","socket","rocket","pocket",
  "bucket","circuit","biscuit","blanket","market","basket","bracket","racket",
  "ticket","trumpet","muppet","target","buffet","inlet","outlet","eyelet",

  // ── Words ending in .org ─────────────────────────────────────────────
  "cyborg","android","humanoid","tabloid","paranoid","factoid","cuboid","ovoid",

  // ── Words ending in .ly ───────────────────────────────────────────────
  "daily","weekly","monthly","quickly","safely","lovely","lively","finally",
  "actually","totally","naturally","virtually","only","truly","holy","early",
  "nearly","clearly","exactly","definitely","barely","rarely","merely","surely",
  "purely","lately","widely","deeply","badly","sadly","madly","gladly","friendly",
  "kindly","costly","ghostly","mostly","likely","lonely","homely","ugly","supply",
  "apply","reply","multiply","imply","comply","rely","fly","sly","ally","bully",
  "jelly","belly","silly","hilly","family","italy","anomaly","assembly","butterfly",
  "centrally","smartly","partly","softly","gently","simply","openly","absolutely",
  "completely","entirely","perfectly","certainly","probably","possibly","necessarily",
  "currently","recently","frequently","constantly","apparently","obviously","seriously",
  "personally","especially","essentially","potentially","originally","primarily",
  "ultimately","gradually","eventually","immediately","previously","simultaneously",
  "professionally","internationally","dramatically","significantly","considerably",
  "independently","automatically","approximately","politically","financially",
  "commercially","effectively","relatively","positively","curly","burly","surly",
  "gnarly","early","pearly","yearly","dearly","deadly","elderly","fatherly",
  "motherly","brotherly","quarterly","orderly","scholarly","bodily","worldly",
  "lordly","earthly","heavenly","timely","homely","comely","seemly","kingly",

  // ── Words ending in .in ───────────────────────────────────────────────
  "online","offline","genuine","routine","discipline","medicine","feminine",
  "masculine","gasoline","quarantine","crystalline","serpentine","libertine",
  "adrenalin","violin","mandarin","aspirin","wolverine","figurine","pristine",
  "valentine","clementine","tangerine","submarine","tambourine","trampoline",
  "vitamin","protein","insulin","morphine","caffeine","nicotine","cocaine",
  "vaccine","mezzanine","combine","turbine","sunshine","moonshine","hairline",
  "airline","hotline","deadline","baseline","outline","pipeline","guideline",
  "streamline","undermine","redesign","define","refine","confine","assign",
  "resign","design","align","sign","mine","nine","vine","wine","pine","line",
  "spine","shine","shrine","divine","swine","twine","whine","decline","incline",
  "combine","define","refine","confine","consign","resign","malign","benign",
  "begin","skin","spin","twin","pin","bin","thin","grin","fin","cabin","satin",
  "resin","basin","ruin","coin","latin","margin","origin","virgin","certain",
  "captain","mountain","fountain","curtain","villain","terrain","explain",
  "complain","maintain","entertain","sustain","attain","detain","retain","strain",
  "admin","bulletin","dolphin","penguin","pumpkin","napkin","assassin","insulin",
  "berlin","darwin","protein","bargain","porcelain","sovereign","chieftain",
  "chaplain","chamberlain","refrain","constrain","restrain","abstain","pertain",
  "ascertain","ordain","elfin","muffin","coffin","paraffin","moccasin","mandolin",
  "javelin","goblin","merlin","kremlin","gremlin","urchin","imagine","examine",
  "domain","join","train","brain","gain","chain","main","plain","again","remain",
  "contain","obtain","login","plugin","within","herein","therein","wherein",

  // ── Words ending in .ge ───────────────────────────────────────────────
  "page","stage","age","cage","wage","sage","rage","image","damage","manage",
  "package","engage","advantage","message","passage","village","college","knowledge",
  "language","heritage","leverage","storage","coverage","mileage","percentage",
  "encourage","challenge","exchange","range","change","arrange","orange","strange",
  "large","merge","surge","emerge","submerge","converge","diverge","bridge",
  "ridge","fridge","knowledge","college","carriage","marriage","courage","voyage",
  "mortgage","footage","shortage","shortage","shortage","shortage","shortage",
  "shortage","shortage","portage","vintage","vintage","garage","garbage","mirage",

  // ── Words ending in .le ───────────────────────────────────────────────
  "able","table","stable","cable","enable","disable","available","reliable",
  "valuable","suitable","flexible","possible","responsible","accessible",
  "compatible","invisible","visible","terrible","horrible","incredible","acceptable",
  "reasonable","enjoyable","comfortable","memorable","favorable","considerable",
  "comparable","capable","lovable","movable","removable","renewable","reusable",
  "scalable","portable","trackable","searchable","shareable","printable","clickable",
  "readable","writable","editable","sortable","filterable","configurable",
  "customizable","deployable","sustainable","manageable","measurable","observable",
  "predictable","programmable","executable","reachable","simple","people","purple",
  "apple","jungle","single","angle","title","circle","article","vehicle","module",
  "example","sample","multiple","principle","obstacle","schedule","molecule",
  "capsule","muscle","puzzle","bundle","handle","model","travel","channel","panel",

  // ── Words ending in .se ───────────────────────────────────────────────
  "base","case","chase","close","choose","noise","house","mouse","goose","moose",
  "loose","dose","nose","pose","rose","use","cause","pause","clause","abuse",
  "excuse","confuse","refuse","amuse","accuse","reuse","diffuse","phase","phrase",
  "raise","praise","please","tease","freeze","breeze","squeeze","sneeze","disease",
  "decrease","increase","release","expertise","purchase","database","showcase",
  "uppercase","lowercase","otherwise","likewise","clockwise","crosswise","sunrise",
  "surprise","advertise","merchandise","exercise","enterprise","compromise",
  "improvise","organize","diverse","reverse","converse","universe","inverse",
  "adverse","perverse","traverse","rehearse","disburse","reimburse","immerse",
  "submerse","disperse","intersperse","coerce",

  // ── Words ending in .re ───────────────────────────────────────────────
  "more","core","store","score","explore","restore","before","ignore","adore",
  "ensure","measure","pleasure","treasure","feature","nature","future","picture",
  "structure","creature","culture","venture","capture","lecture","gesture","texture",
  "mixture","rupture","fracture","manufacture","architecture","infrastructure",
  "adventure","signature","temperature","furniture","literature","software",
  "hardware","where","there","here","share","care","dare","bare","compare",
  "prepare","declare","beware","aware","middleware","sure","pure","cure","secure",
  "obscure","mature","figure","configure","departure","pasture","nurture","rapture",
  "conjecture","architecture","overture","overture",

  // ── Words ending in .ke ───────────────────────────────────────────────
  "make","take","fake","bake","cake","lake","sake","shake","snake","stake",
  "wake","brake","flake","mistake","remake","overtake","handshake","earthquake",
  "snowflake","like","bike","hike","strike","spike","alike","dislike","unlike",
  "invoke","revoke","provoke","evoke","stroke","smoke","spoke","broke","woke",

  // ── Words ending in .ne ───────────────────────────────────────────────
  "online","airline","baseline","deadline","pipeline","headline","outline","decline",
  "define","combine","sunshine","moonshine","lifeline","guideline","timeline",
  "hotline","streamline","frontline","zone","bone","cone","done","gone","lone",
  "tone","stone","phone","drone","throne","chrome","ozone","cornerstone","milestone",
  "cocaine","caffeine","vaccine","routine","machine","cuisine","marine","magazine",
  "genuine","oline","gasoline","kerosene","nicotine","morphine","hormone","immune",
  "commune","fortune","tribune","magazine","wine","mine","nine","vine","pine",
  "line","spine","shine","shrine","divine","swine","twine","whine","brine","dine",
  "fine","mine","pine","vine","wine","antine","antine","antine",

  // ── Words ending in .ce ───────────────────────────────────────────────
  "place","space","face","race","grace","trace","pace","embrace","replace","surface",
  "interface","database","marketplace","workspace","showcase","practice","service",
  "notice","office","force","source","resource","choice","voice","advice","device",
  "justice","invoice","sequence","experience","audience","science","patience",
  "silence","balance","distance","instance","influence","difference","reference",
  "performance","resistance","assistance","importance","significance","convenience",
  "conference","preference","evidence","intelligence","excellence","ambiance",
  "brilliance","alliance","compliance","reliance","defiance","appliance",

  // ── Words ending in .ve ───────────────────────────────────────────────
  "live","give","drive","arrive","strive","thrive","achieve","believe","receive",
  "perceive","conceive","deceive","relieve","retrieve","creative","active","native",
  "massive","passive","positive","negative","sensitive","alternative","innovative",
  "exclusive","inclusive","attractive","productive","destructive","constructive",
  "collective","protective","effective","selective","objective","subjective",
  "primitive","executive","perspective","representative","archive","survive",
  "derive","revive","naive","olive","above","dove","cove","drove","glove","grove",
  "clove","stove","wove","trove","love","groove","approve","remove","improve",
  "prove","move","groove","beehive","overdrive","worldview",

  // ── Words ending in .work ────────────────────────────────────────────
  "network","framework","teamwork","homework","artwork","fieldwork","groundwork",
  "clockwork","patchwork","paperwork","overwork","guesswork","rework","ironwork",

  // ── Words ending in .ist ─────────────────────────────────────────────
  "activist","specialist","journalist","communist","optimist","physicist","geologist",
  "biologist","economist","capitalist","socialist","anarchist","perfectionist",
  "impressionist","expressionist","modernist","traditionalist","rationalist",
  "finalist","naturalist","realist","idealist","minimalist","universalist",
  "functionalist","environmentalist","nationalist","internationalist","individualist",
  "therapist","strategist","analyst","evangelist","catalyst","columnist","racist",
  "sexist","exist","consist","assist","insist","persist","resist","subsist",

  // ── Words ending in .app ─────────────────────────────────────────────
  "app","webapp","snapchat","recap","mishap","kneecap","skullcap","nightcap",
  "hubcap","icecap","redcap","hubcap","whitecap","handclap","bootstrap",

  // ── Words ending in .nt ───────────────────────────────────────────────
  "event","front","grant","hint","hunt","mint","parent","plant","point","print",
  "rant","rent","saint","scent","sent","spent","stunt","talent","tenant","tent",
  "tint","torrent","urgent","vent","want","went","content","element","moment",
  "payment","statement","treatment","agreement","development","government",
  "environment","management","department","movement","requirement","achievement",
  "adjustment","appointment","assessment","assignment","commitment","complement",
  "component","implement","investment","judgment","measurement","replacement",
  "settlement","supplement","tournament","advertisement","announcement","enhancement",
  "engagement","encouragement","employment","entertainment","experiment","improvement",
  "movement","nourishment","punishment","refreshment","requirement","retirement",

  // ── Additional mixed endings ──────────────────────────────────────────
  "earth","water","fire","wind","air","sun","moon","star","tree","leaf","flower",
  "forest","ocean","mountain","river","cloud","rain","snow","storm","energy","solar",
  "wind","green","eco","bio","natural","organic","sustainable","renewable","clean",
  "fresh","food","travel","fitness","health","beauty","fashion","sport","music",
  "film","book","life","work","play","learn","grow","build","explore","discover",
  "connect","inspire","lead","plan","track","measure","improve","simplify",
  "account","address","agreement","analysis","application","approach","benefit",
  "challenge","community","concept","context","contract","ecosystem","efficiency",
  "environment","growth","impact","initiative","insight","integration","inventory",
  "journey","knowledge","lifecycle","methodology","objective","opportunity","overview",
  "pathway","priority","process","profile","prototype","quality","requirement",
  "scalability","sustainability","system","toolkit","transparency","utility",
  "velocity","visibility","workflow","inventory","momentum","partnership",
];

// Bilingual meanings for corpus words
export const CORPUS_MEANINGS: Record<string, string> = {
  // Domain/Tech
  digital: "数字的 · Digital",
  virtual: "虚拟的 · Virtual",
  network: "网络 · Network",
  connect: "连接 · Connect",
  cloud: "云端 · Cloud",
  stream: "流媒体 · Stream",
  mobile: "移动 · Mobile",
  global: "全球 · Global",
  social: "社交 · Social",
  platform: "平台 · Platform",
  algorithm: "算法 · Algorithm",
  database: "数据库 · Database",
  startup: "创业公司 · Startup",
  innovation: "创新 · Innovation",
  blockchain: "区块链 · Blockchain",
  software: "软件 · Software",
  hardware: "硬件 · Hardware",
  security: "安全 · Security",
  // Domain-hack specific
  bonsai: "盆栽 · Bonsai",
  samurai: "武士 · Samurai",
  radio: "收音机/无线电 · Radio",
  studio: "工作室 · Studio",
  audio: "音频 · Audio",
  ratio: "比例 · Ratio",
  portfolio: "作品集 · Portfolio",
  scenario: "场景/方案 · Scenario",
  cisco: "思科 · Cisco",
  disco: "迪斯科 · Disco",
  fiasco: "惨败 · Fiasco",
  calico: "印花布 · Calico",
  tobacco: "烟草 · Tobacco",
  home: "家 · Home",
  game: "游戏 · Game",
  fame: "名声 · Fame",
  theme: "主题 · Theme",
  scheme: "方案 · Scheme",
  extreme: "极限 · Extreme",
  welcome: "欢迎 · Welcome",
  awesome: "极好的 · Awesome",
  outcome: "结果 · Outcome",
  genome: "基因组 · Genome",
  chrome: "铬/Chrome浏览器 · Chrome",
  syndrome: "综合症 · Syndrome",
  bonus: "奖励 · Bonus",
  campus: "校园 · Campus",
  focus: "焦点 · Focus",
  nexus: "联系/纽带 · Nexus",
  virus: "病毒 · Virus",
  status: "状态 · Status",
  genius: "天才 · Genius",
  curious: "好奇的 · Curious",
  serious: "严肃的 · Serious",
  famous: "著名的 · Famous",
  enormous: "巨大的 · Enormous",
  generous: "慷慨的 · Generous",
  basis: "基础 · Basis",
  crisis: "危机 · Crisis",
  thesis: "论文/命题 · Thesis",
  oasis: "绿洲 · Oasis",
  analysis: "分析 · Analysis",
  synthesis: "综合/合成 · Synthesis",
  emphasis: "强调 · Emphasis",
  diagnosis: "诊断 · Diagnosis",
  nemesis: "劲敌/报应 · Nemesis",
  genesis: "起源/创世纪 · Genesis",
  profit: "利润 · Profit",
  benefit: "收益/好处 · Benefit",
  credit: "信用/学分 · Credit",
  audit: "审计 · Audit",
  spirit: "精神 · Spirit",
  digit: "数字/手指 · Digit",
  circuit: "电路 · Circuit",
  deficit: "赤字 · Deficit",
  heart: "心脏/心 · Heart",
  start: "开始 · Start",
  smart: "智能/聪明 · Smart",
  art: "艺术 · Art",
  arcade: "拱廊/游戏厅 · Arcade",
  cascade: "瀑布/级联 · Cascade",
  decade: "十年 · Decade",
  grade: "等级/成绩 · Grade",
  trade: "贸易 · Trade",
  upgrade: "升级 · Upgrade",
  code: "代码 · Code",
  node: "节点 · Node",
  ego: "自我 · Ego",
  cargo: "货物 · Cargo",
  embargo: "禁运 · Embargo",
  logo: "标志 · Logo",
  mango: "芒果 · Mango",
  tango: "探戈 · Tango",
  vertigo: "眩晕 · Vertigo",
  indigo: "靛蓝 · Indigo",
  flamingo: "火烈鸟 · Flamingo",
  piano: "钢琴 · Piano",
  casino: "赌场 · Casino",
  volcano: "火山 · Volcano",
  rhino: "犀牛 · Rhino",
  auto: "汽车/自动 · Auto",
  photo: "照片 · Photo",
  motto: "格言 · Motto",
  gusto: "热情/兴致 · Gusto",
  presto: "迅速/快速 · Presto",
  burrito: "墨西哥卷饼 · Burrito",
  mosquito: "蚊子 · Mosquito",
  incognito: "隐身模式 · Incognito",
  vibrato: "颤音 · Vibrato",
  manifesto: "宣言 · Manifesto",
  avocado: "牛油果 · Avocado",
  tornado: "龙卷风 · Tornado",
  desperado: "亡命之徒 · Desperado",
  dream: "梦想 · Dream",
  team: "团队 · Team",
  cream: "奶油/精华 · Cream",
  program: "程序/项目 · Program",
  hologram: "全息图 · Hologram",
  diagram: "图表 · Diagram",
  best: "最好 · Best",
  rest: "休息/其余 · Rest",
  test: "测试 · Test",
  west: "西方 · West",
  quest: "任务/探索 · Quest",
  artist: "艺术家 · Artist",
  dentist: "牙医 · Dentist",
  optimist: "乐观主义者 · Optimist",
  specialist: "专家 · Specialist",
  activist: "活动家 · Activist",
  broadcast: "广播 · Broadcast",
  podcast: "播客 · Podcast",
  forecast: "预测 · Forecast",
  outcast: "被放逐者 · Outcast",
  globe: "地球/全球 · Globe",
  tube: "管/YouTube · Tube",
  cube: "立方体 · Cube",
  slim: "苗条/纤薄 · Slim",
  trim: "修剪/整洁 · Trim",
  pilgrim: "朝圣者 · Pilgrim",
  long: "长 · Long",
  song: "歌曲 · Song",
  strong: "强壮/坚强 · Strong",
  king: "国王 · King",
  ring: "戒指/铃声 · Ring",
  spring: "春天/弹簧 · Spring",
  morning: "早晨 · Morning",
  building: "建筑/建设 · Building",
  developing: "开发中 · Developing",
  marketing: "营销 · Marketing",
  gaming: "游戏 · Gaming",
  streaming: "流媒体 · Streaming",
  coding: "编码 · Coding",
  local: "本地 · Local",
  total: "总计 · Total",
  natural: "自然的 · Natural",
  final: "最终 · Final",
  trial: "试用/审判 · Trial",
  survival: "生存 · Survival",
  professional: "专业 · Professional",
  rational: "理性 · Rational",
  original: "原创 · Original",
  cultural: "文化 · Cultural",
  technical: "技术 · Technical",
  practical: "实用 · Practical",
  logical: "逻辑 · Logical",
  medical: "医疗 · Medical",
  biological: "生物 · Biological",
  mathematical: "数学 · Mathematical",
  philosophical: "哲学 · Philosophical",
  open: "开放/打开 · Open",
  garden: "花园 · Garden",
  citizen: "公民 · Citizen",
  oxygen: "氧气 · Oxygen",
  electron: "电子 · Electron",
  action: "行动 · Action",
  solution: "解决方案 · Solution",
  function: "功能 · Function",
  connection: "连接 · Connection",
  information: "信息 · Information",
  education: "教育 · Education",
  communication: "通信/沟通 · Communication",
  organization: "组织 · Organization",
  transformation: "转型 · Transformation",
  definition: "定义 · Definition",
  competition: "竞争 · Competition",
  vision: "愿景 · Vision",
  decision: "决策 · Decision",
  passion: "热情 · Passion",
  person: "人 · Person",
  amazon: "亚马逊 · Amazon",
  silicon: "硅 · Silicon",
  dragon: "龙 · Dragon",
  water: "水 · Water",
  power: "力量/电力 · Power",
  player: "玩家 · Player",
  leader: "领导者 · Leader",
  teacher: "教师 · Teacher",
  manager: "经理 · Manager",
  developer: "开发者 · Developer",
  designer: "设计师 · Designer",
  creator: "创作者 · Creator",
  founder: "创始人 · Founder",
  partner: "合作伙伴 · Partner",
  server: "服务器 · Server",
  customer: "客户 · Customer",
  tracker: "追踪器 · Tracker",
  broker: "中间人/经纪人 · Broker",
  trader: "交易者 · Trader",
  investor: "投资者 · Investor",
  writer: "作家 · Writer",
  editor: "编辑 · Editor",
  computer: "计算机 · Computer",
  router: "路由器 · Router",
  filter: "过滤器 · Filter",
  generator: "生成器 · Generator",
  operator: "操作员 · Operator",
  monitor: "监控/显示器 · Monitor",
  thunder: "雷声 · Thunder",
  actor: "演员 · Actor",
  major: "主要/主修 · Major",
  minor: "次要/未成年 · Minor",
  sector: "部门/扇区 · Sector",
  senior: "高级/老年 · Senior",
  vendor: "供应商 · Vendor",
  honor: "荣誉 · Honor",
  error: "错误 · Error",
  author: "作者 · Author",
  mentor: "导师 · Mentor",
  governor: "州长 · Governor",
  professor: "教授 · Professor",
  innovator: "创新者 · Innovator",
  bar: "酒吧/条形 · Bar",
  car: "汽车 · Car",
  star: "明星/星星 · Star",
  avatar: "头像/化身 · Avatar",
  guitar: "吉他 · Guitar",
  radar: "雷达 · Radar",
  solar: "太阳能 · Solar",
  lunar: "月球 · Lunar",
  popular: "受欢迎的 · Popular",
  regular: "常规 · Regular",
  cellular: "蜂窝/细胞 · Cellular",
  modular: "模块化 · Modular",
  molecular: "分子 · Molecular",
  base: "基础 · Base",
  case: "案例 · Case",
  phase: "阶段 · Phase",
  phrase: "短语 · Phrase",
  expertise: "专业知识 · Expertise",
  purchase: "购买 · Purchase",
  showcase: "展示 · Showcase",
  exercise: "练习/锻炼 · Exercise",
  enterprise: "企业 · Enterprise",
  compromise: "妥协/折中 · Compromise",
  organize: "组织/整理 · Organize",
  more: "更多 · More",
  core: "核心 · Core",
  store: "商店/存储 · Store",
  score: "分数/得分 · Score",
  explore: "探索 · Explore",
  restore: "恢复 · Restore",
  ensure: "确保 · Ensure",
  measure: "测量/措施 · Measure",
  treasure: "宝藏 · Treasure",
  feature: "功能/特性 · Feature",
  nature: "自然 · Nature",
  future: "未来 · Future",
  structure: "结构 · Structure",
  culture: "文化 · Culture",
  venture: "创业/冒险 · Venture",
  capture: "捕获 · Capture",
  architecture: "架构 · Architecture",
  infrastructure: "基础设施 · Infrastructure",
  adventure: "冒险 · Adventure",
  literature: "文学 · Literature",
  make: "制作 · Make",
  take: "拿取 · Take",
  cake: "蛋糕 · Cake",
  lake: "湖泊 · Lake",
  mistake: "错误 · Mistake",
  earthquake: "地震 · Earthquake",
  like: "喜欢 · Like",
  bike: "自行车 · Bike",
  strike: "罢工/击打 · Strike",
  page: "页面 · Page",
  stage: "阶段/舞台 · Stage",
  image: "图像 · Image",
  manage: "管理 · Manage",
  engage: "参与/接触 · Engage",
  message: "消息 · Message",
  package: "包/套餐 · Package",
  knowledge: "知识 · Knowledge",
  language: "语言 · Language",
  storage: "存储 · Storage",
  coverage: "覆盖率 · Coverage",
  leverage: "杠杆/利用 · Leverage",
  challenge: "挑战 · Challenge",
  exchange: "交换/交流 · Exchange",
  range: "范围 · Range",
  change: "改变 · Change",
  able: "能够 · Able",
  table: "表格/桌子 · Table",
  stable: "稳定 · Stable",
  enable: "启用 · Enable",
  available: "可用 · Available",
  reliable: "可靠 · Reliable",
  flexible: "灵活 · Flexible",
  possible: "可能 · Possible",
  responsible: "负责任 · Responsible",
  accessible: "可访问 · Accessible",
  compatible: "兼容 · Compatible",
  simple: "简单 · Simple",
  people: "人们 · People",
  title: "标题 · Title",
  circle: "圆形 · Circle",
  article: "文章 · Article",
  module: "模块 · Module",
  example: "示例 · Example",
  multiple: "多个 · Multiple",
  principle: "原则 · Principle",
  schedule: "时间表 · Schedule",
  handle: "处理/手柄 · Handle",
  model: "模型 · Model",
  travel: "旅行 · Travel",
  channel: "频道 · Channel",
  panel: "面板 · Panel",
  optimize: "优化 · Optimize",
  analyze: "分析 · Analyze",
  maximize: "最大化 · Maximize",
  minimize: "最小化 · Minimize",
  customize: "定制 · Customize",
  visualize: "可视化 · Visualize",
  stabilize: "稳定化 · Stabilize",
  mobilize: "动员 · Mobilize",
  finalize: "完成 · Finalize",
  monetize: "变现 · Monetize",
  prioritize: "优先 · Prioritize",
  summarize: "总结 · Summarize",
  categorize: "分类 · Categorize",
  network: "网络 · Network",
  framework: "框架 · Framework",
  teamwork: "团队合作 · Teamwork",
  artwork: "艺术品 · Artwork",
  edtech: "教育科技 · EdTech",
  fintech: "金融科技 · FinTech",
  biotech: "生物科技 · BioTech",
  cleantech: "清洁技术 · CleanTech",
  medtech: "医疗科技 · MedTech",
  martech: "营销科技 · MarTech",
  hotdog: "热狗 · Hotdog",
  bulldog: "斗牛犬 · Bulldog",
  underdog: "弱势者 · Underdog",
  catalog: "目录 · Catalog",
  dialog: "对话 · Dialog",
  think: "思考 · Think",
  drink: "饮料/喝 · Drink",
  link: "链接 · Link",
  shrink: "收缩/萎缩 · Shrink",
  blink: "眨眼/Blink · Blink",
  roadmap: "路线图 · Roadmap",
  sitemap: "站点地图 · Sitemap",
  heatmap: "热力图 · Heatmap",
  mindmap: "思维导图 · Mindmap",
  bitmap: "位图 · Bitmap",
  outrun: "超过 · Outrun",
  rerun: "重播 · Rerun",
  outlaw: "歹徒/非法 · Outlaw",
  bylaw: "附则/内规 · Bylaw",
  renew: "更新/续期 · Renew",
  phone: "电话 · Phone",
  zone: "区域 · Zone",
  stone: "石头 · Stone",
  alone: "独自 · Alone",
  clone: "克隆 · Clone",
  drone: "无人机 · Drone",
  throne: "王座 · Throne",
  milestone: "里程碑 · Milestone",
  microphone: "麦克风 · Microphone",
  smartphone: "智能手机 · Smartphone",
  ozone: "臭氧 · Ozone",
  island: "岛屿 · Island",
  homeland: "家园 · Homeland",
  wetland: "湿地 · Wetland",
  highland: "高地 · Highland",
  scotland: "苏格兰 · Scotland",
  finland: "芬兰 · Finland",
  england: "英格兰 · England",
  ireland: "爱尔兰 · Ireland",
  zealand: "泽兰 · Zealand",
  thailand: "泰国 · Thailand",
  iceland: "冰岛 · Iceland",
  greenland: "格陵兰 · Greenland",
  earth: "地球 · Earth",
  energy: "能源 · Energy",
  food: "食物 · Food",
  health: "健康 · Health",
  beauty: "美丽 · Beauty",
  family: "家庭 · Family",
  love: "爱 · Love",
  life: "生活 · Life",
  create: "创造 · Create",
  build: "构建 · Build",
  design: "设计 · Design",
  develop: "开发 · Develop",
  discover: "发现 · Discover",
  inspire: "激励 · Inspire",
  improve: "改进 · Improve",
  simplify: "简化 · Simplify",
  internet: "互联网 · Internet",
  magnet: "磁铁 · Magnet",
  planet: "行星 · Planet",
  cabinet: "内阁/橱柜 · Cabinet",
  clarinet: "单簧管 · Clarinet",
  coronet: "小冠 · Coronet",
  bayonet: "刺刀 · Bayonet",
  sonnet: "十四行诗 · Sonnet",
  wildcat: "野猫 · Wildcat",
  bobcat: "猞猁 · Bobcat",
  copycat: "模仿者 · Copycat",
  think: "思考 · Think",
  drink: "喝/饮料 · Drink",
  link: "链接 · Link",
  blink: "眨眼 · Blink",
  shrink: "收缩 · Shrink",
  pink: "粉红色 · Pink",
  outcome: "结果 · Outcome",
  income: "收入 · Income",
  overcome: "克服 · Overcome",
  welcome: "欢迎 · Welcome",
  handsome: "英俊 · Handsome",
  awesome: "极好的 · Awesome",
  gruesome: "可怕的 · Gruesome",
  winsome: "迷人的 · Winsome",
  tiresome: "令人厌倦的 · Tiresome",
  loathsome: "令人厌恶的 · Loathsome",
  fearsome: "可怕的 · Fearsome",
  lonesome: "孤独的 · Lonesome",
};
