// Creative word splits for Asian ccTLDs with rare letter combos
// These TLDs don't naturally end English words, so we use creative approaches:
// 1. Brand-style names (prefix.tld)
// 2. Abbreviation-style splits
// 3. Words where the TLD letters appear embedded

export const WORD_LIBRARY_EXTRA5: Record<string, string[]> = {

  // ============================================================
  // .jp (Japan) — no English words end in "jp"
  // Use words that can be creatively split before "jp" isn't possible
  // Instead, offer prefix-style short domains
  // ============================================================
  jp: [],

  // ============================================================
  // .kr (Korea) — words containing "kr" are extremely rare
  // ============================================================
  kr: [],

  // ============================================================
  // .vn (Vietnam) — no natural English words end in "vn"
  // ============================================================
  vn: [],

  // ============================================================
  // .cn (China) — no natural English words end in "cn"
  // ============================================================
  cn: [],

  // ============================================================
  // .tw (Taiwan) — no natural English words end in "tw"
  // ============================================================
  tw: [],

  // ============================================================
  // .hk (Hong Kong) — no natural English words end in "hk"
  // ============================================================
  hk: [],

  // ============================================================
  // EXPAND EXISTING HIGH-VALUE TLDs WITH MORE WORDS
  // ============================================================

  // .io words (massive expansion)
  io: [
    "ratio", "studio", "radio", "audio", "portfolio", "scenario",
    "patio", "pistachio", "cheerio", "trio", "duo", "folio",
    "polio", "cardio", "ohio", "tokyo", "mario", "antonio",
    "romeo", "scorpio", "pinocchio", "cappuccino", "flamingo",
    "casino", "buffalo", "volcano", "tornado", "mosquito",
    "avocado", "colorado", "desperado", "commando", "torpedo",
    "crescendo", "innuendo", "manifesto", "risotto", "grotto",
    "ghetto", "stiletto", "falsetto", "libretto", "concerto",
    "virtuoso", "espresso", "fiasco", "fresco", "disco",
    "tobacco", "morocco", "calico", "bronco", "poncho",
  ],

  // .me words (massive expansion)
  me: [
    "home", "name", "game", "time", "come", "some", "frame",
    "flame", "fame", "blame", "shame", "same", "volume",
    "resume", "costume", "perfume", "welcome", "become",
    "overcome", "outcome", "income", "awesome", "handsome",
    "wholesome", "programme", "scheme", "theme", "extreme",
    "supreme", "crime", "prime", "rhyme", "dime", "lime",
    "mime", "slime", "chime", "enzyme", "genome", "syndrome",
    "biome", "chrome", "dome", "gnome", "hippodrome",
    "palindrome", "aerodrome", "syndrome", "monochrome",
    "velodrome", "astrodome", "metronome", "microbiome",
    "assume", "consume", "presume", "costume", "legume",
    "resume", "volume", "plume", "fume", "flume",
    "nickname", "surname", "regime", "sublime", "maritime",
    "overtime", "pastime", "lifetime", "bedtime", "daytime",
    "nighttime", "sometime", "meantime", "halftime", "mealtime",
    "pantomime", "paradigm",
  ],

  // .de words (massive expansion)
  de: [
    "code", "mode", "node", "guide", "inside", "outside",
    "provide", "decide", "upgrade", "trade", "shade", "blade",
    "grade", "arcade", "cascade", "parade", "lemonade",
    "ride", "hide", "side", "pride", "divide", "glide",
    "slide", "stride", "bride", "worldwide", "countryside",
    "alongside", "hillside", "roadside", "seaside", "fireside",
    "bedside", "ringside", "poolside", "curbside", "lakeside",
    "riverside", "mountainside", "oceanside",
    "crude", "rude", "dude", "include", "exclude", "conclude",
    "intrude", "preclude", "magnitude", "attitude", "altitude",
    "latitude", "longitude", "gratitude", "solitude", "aptitude",
    "multitude", "amplitude", "certitude", "fortitude",
    "servitude", "plenitude", "beatitude", "vicissitude",
    "abode", "episode", "electrode", "diode", "cathode",
    "explode", "implode", "corrode", "erode", "decode",
    "encode", "overload", "download", "upload", "reload",
    "barricade", "promenade", "masquerade", "serenade",
    "colonnade", "esplanade", "renegade", "retrograde",
    "accolade", "blockade", "stockade", "crusade", "tirade",
    "facade", "brocade", "decade", "grenade", "brigade",
    "charade", "escapade", "evade", "invade", "pervade",
    "persuade", "dissuade",
  ],

  // .re words (massive expansion)
  re: [
    "share", "care", "dare", "rare", "compare", "prepare",
    "aware", "software", "hardware", "before", "explore",
    "restore", "store", "score", "core", "more", "future",
    "nature", "culture", "structure", "feature", "picture",
    "capture", "adventure", "furniture", "architecture",
    "literature", "temperature", "agriculture", "manufacture",
    "infrastructure", "nomenclature", "caricature",
    "miniature", "signature", "creature", "moisture",
    "mixture", "fixture", "texture", "venture", "gesture",
    "posture", "pasture", "fracture", "lecture", "puncture",
    "rapture", "sculpture", "conjecture", "departure",
    "expenditure", "forfeiture", "aperture", "overture",
    "premature", "immature", "curvature", "candidature",
    "inspire", "require", "retire", "entire", "fire",
    "hire", "wire", "empire", "admire", "desire", "aspire",
    "conspire", "perspire", "transpire", "satire", "vampire",
    "bonfire", "campfire", "crossfire", "gunfire", "hellfire",
    "wildfire", "ceasefire", "surefire", "spitfire",
    "hemisphere", "sapphire", "quagmire", "umpire",
    "here", "where", "there", "everywhere", "nowhere",
    "somewhere", "anywhere", "atmosphere", "hemisphere",
    "sphere", "sincere", "severe", "austere", "cashmere",
    "mere", "premiere", "revere", "interfere", "persevere",
    "adhere", "cohere",
    "acre", "lucre", "ogre", "genre", "centre",
  ],

  // .st words (massive expansion - already large, add more specialized)
  st: [
    "podcast", "breakfast", "broadcast", "forecast", "downcast",
    "steadfast", "standfast", "colorfast", "holdfast",
    "contrast", "bombast", "enthusiast", "gymnast",
    "iconoclast", "outcast", "newscast", "typecast",
    "webcast", "simulcast", "sportscast",
  ],

  // .ng words (massive expansion)
  ng: [
    "blockchain", "debugging", "encrypting", "decrypting",
    "downloading", "uploading", "computing", "browsing",
    "blogging", "vlogging", "podcasting", "broadcasting",
    "networking", "programming", "rendering", "modeling",
    "prototyping", "wireframing", "brainstorming",
    "onboarding", "offboarding", "troubleshooting",
    "bookkeeping", "crowdfunding", "dropshipping",
    "freelancing", "ghostwriting", "headhunting",
    "moonlighting", "outsourcing", "proofreading",
    "sightseeing", "skateboarding", "snowboarding",
    "surfing", "paragliding", "skydiving", "bungee jumping",
    "mountaineering", "engineering", "volunteering",
    "campaigning", "fundraising", "mentoring",
  ],

  // .er words (more specialized)
  er: [
    "influencer", "freelancer", "commander", "defender",
    "contender", "surrender", "remember", "stakeholder",
    "stockholder", "shareholder", "homeowner", "landowner",
    "bystander", "commander", "highlander", "islander",
    "outlander", "philander", "alexander", "salamander",
    "lavender", "bartender", "transgender", "agenda",
    "surrender", "thunderer", "wanderer", "wonderer",
    "plunderer", "blunderer", "squanderer",
    "astronomer", "philosopher", "photographer",
    "choreographer", "videographer", "cinematographer",
    "biographer", "geographer", "cartographer",
    "lexicographer", "stenographer", "typographer",
    "calligrapher", "lithographer",
  ],

  // .al words (more specialized)
  al: [
    "ministerial", "editorial", "memorial", "industrial",
    "commercial", "territorial", "imperial", "material",
    "bacterial", "arterial", "magisterial", "managerial",
    "adversarial", "secretarial", "entrepreneurial",
    "controversial", "hypothetical", "alphabetical",
    "pharmaceutical", "mathematical", "astronomical",
    "ecclesiastical", "metaphysical", "analytical",
    "biographical", "chronological", "etymological",
    "genealogical", "geographical", "grammatical",
    "hierarchical", "ideological", "jurisdictional",
    "mythological", "neurological", "paradoxical",
    "philosophical", "psychological", "technological",
    "theological", "zoological",
    "aboriginal", "additional", "ceremonial", "centennial",
    "colloquial", "conditional", "congressional",
    "constitutional", "conventional", "conversational",
    "devotional", "dimensional", "directional",
    "educational", "emotional", "environmental",
    "exceptional", "functional", "generational",
    "gravitational", "informational", "inspirational",
    "institutional", "intentional", "international",
    "motivational", "navigational", "nutritional",
    "observational", "occupational", "operational",
    "organizational", "promotional", "proportional",
    "recreational", "relational", "representational",
    "rotational", "sensational", "situational",
    "transitional", "unconditional", "vocational",
  ],

  // .es words (more specialized)
  es: [
    "addresses", "analyses", "approaches", "archives",
    "balances", "branches", "businesses", "challenges",
    "chances", "changes", "charges", "choices",
    "circumstances", "coaches", "complexes", "consequences",
    "crashes", "databases", "differences", "distances",
    "employees", "exchanges", "exercises", "expenses",
    "experiences", "finances", "frequencies", "guidelines",
    "hurricanes", "instances", "interfaces", "languages",
    "licenses", "machines", "manages", "marriages",
    "mortgages", "packages", "passages", "percentages",
    "performances", "phrases", "practices", "preferences",
    "processes", "promises", "purchases", "purposes",
    "references", "releases", "resources", "responses",
    "revenues", "schedules", "sciences", "sentences",
    "sequences", "services", "strategies", "structures",
    "substances", "surfaces", "techniques", "templates",
    "universes", "variables", "vehicles", "villages",
    "warehouses", "websites",
  ],
};

// Chinese meanings for creative Asian TLD combinations
export const WORD_MEANINGS_EXTRA5: Record<string, string> = {
  // More .io meanings
  "scorp.io": "天蝎座",
  "pinocch.io": "匹诺曹",
  "flameng.io": "弗拉门戈(缩)",
  "stilet.to.io": "细高跟(缩)",
  "libret.to.io": "剧本(缩)",
  "concert.io": "音乐会(缩)",
  "virtuos.io": "大师(缩)",

  // More .me meanings
  "cri.me": "犯罪",
  "pri.me": "主要的/黄金",
  "rhy.me": "韵律",
  "di.me": "一角硬币",
  "li.me": "酸橙",
  "mi.me": "模仿",
  "sli.me": "黏液",
  "chi.me": "钟声",
  "chro.me": "铬/浏览器",
  "do.me": "圆顶",
  "gno.me": "侏儒",
  "syndro.me": "综合征",
  "bio.me": "生物群落",
  "geno.me": "基因组",
  "enzy.me": "酶",
  "nickna.me": "昵称",
  "surna.me": "姓氏",
  "regi.me": "政权",
  "subli.me": "崇高的",
  "mariti.me": "海事的",
  "overti.me": "加班",
  "lifeti.me": "一生",
  "bedti.me": "就寝时间",
  "dayti.me": "白天",
  "nightti.me": "夜间",
  "someti.me": "有时",
  "meanti.me": "同时",
  "halftime.me": "中场(缩)",
  "pantomi.me": "哑剧",
  "assu.me": "假设",
  "consu.me": "消费",
  "presu.me": "推定",
  "legu.me": "豆类",
  "plu.me": "羽毛",
  "fu.me": "烟气",
  "volu.me": "体积/卷",

  // More .de meanings
  "cru.de": "粗糙的/原油",
  "ru.de": "粗鲁的",
  "du.de": "家伙",
  "inclu.de": "包括",
  "exclu.de": "排除",
  "conclu.de": "总结",
  "intru.de": "入侵",
  "magnitu.de": "大小/量级",
  "attitu.de": "态度",
  "altitu.de": "海拔",
  "latitu.de": "纬度",
  "longitu.de": "经度",
  "gratitu.de": "感激",
  "solitu.de": "孤独",
  "aptitu.de": "才能",
  "fortitu.de": "毅力",
  "abo.de": "住所",
  "episo.de": "集/事件",
  "electro.de": "电极",
  "dio.de": "二极管",
  "catho.de": "阴极",
  "explo.de": "爆炸",
  "implo.de": "内爆",
  "corro.de": "腐蚀",
  "ero.de": "侵蚀",
  "deco.de": "解码",
  "enco.de": "编码",
  "overlo.ad.de": "过载(缩)",
  "barrica.de": "路障",
  "promena.de": "散步",
  "masquera.de": "化装舞会",
  "serena.de": "小夜曲",
  "colonna.de": "柱廊",
  "reneaga.de": "叛徒(缩)",
  "retroaga.de": "逆行(缩)",
  "accola.de": "赞誉",
  "blocka.de": "封锁",
  "crusa.de": "十字军",
  "tira.de": "长篇大论",
  "faca.de": "外观/正面",
  "broca.de": "织锦",
  "deca.de": "十年",
  "grena.de": "手榴弹",
  "briga.de": "旅/队",
  "chara.de": "猜字谜",
  "escapa.de": "冒险(缩)",
  "eva.de": "逃避",
  "inva.de": "入侵",
  "perva.de": "弥漫",
  "persua.de": "说服",
  "dissua.de": "劝阻",

  // More .re meanings
  "furnitu.re": "家具",
  "architectu.re": "建筑",
  "literatu.re": "文学",
  "temperatu.re": "温度",
  "agricultu.re": "农业",
  "manufactu.re": "制造",
  "infrastructu.re": "基础设施",
  "miniatu.re": "微型",
  "signatu.re": "签名",
  "moistu.re": "水分",
  "mixtu.re": "混合物",
  "fixtu.re": "固定装置",
  "textu.re": "纹理",
  "ventu.re": "冒险/企业",
  "gestu.re": "手势",
  "postu.re": "姿势",
  "pastu.re": "牧场",
  "fractu.re": "骨折",
  "lectu.re": "讲座",
  "punctu.re": "穿刺",
  "raptu.re": "狂喜",
  "sculptu.re": "雕塑",
  "departu.re": "离开",
  "expenditu.re": "支出",
  "apertu.re": "光圈",
  "overtu.re": "序曲",
  "prematu.re": "早产/不成熟",
  "curvatu.re": "曲率",
  "desi.re": "欲望",
  "aspi.re": "渴望",
  "conspi.re": "密谋",
  "perspi.re": "出汗",
  "sati.re": "讽刺",
  "vampi.re": "吸血鬼",
  "bonfi.re": "篝火",
  "campfi.re": "营火",
  "wildfi.re": "野火",
  "ceasefi.re": "停火",
  "spitfi.re": "烈性人",
  "saphi.re": "蓝宝石(缩)",
  "umpi.re": "裁判",
  "hemishe.re": "半球(缩)",
  "atmosphe.re": "气氛",
  "sphe.re": "球体/领域",
  "since.re": "真诚的",
  "seve.re": "严重的",
  "auste.re": "严肃的",
  "cashme.re": "羊绒",
  "premie.re": "首映",
  "reve.re": "尊敬",
  "interfe.re": "干涉",
  "perseve.re": "坚持",
  "adhe.re": "粘附",
  "gen.re": "类型/风格",
  "cent.re": "中心",
  "ac.re": "英亩",
  "og.re": "食人魔",

  // .ng specialized
  "blockchai.ng": "区块链(缩)",
  "debuggi.ng": "调试",
  "encrypti.ng": "加密",
  "downloadi.ng": "下载",
  "uploadi.ng": "上传",
  "computi.ng": "计算",
  "browsi.ng": "浏览",
  "bloggi.ng": "博客",
  "vloggi.ng": "视频博客",
  "podcasti.ng": "播客",
  "broadcasti.ng": "广播",
  "networki.ng": "网络",
  "programmi.ng": "编程",
  "renderi.ng": "渲染",
  "modeli.ng": "建模",
  "prototypi.ng": "原型设计",
  "brainstormi.ng": "头脑风暴",
  "onboardi.ng": "入职",
  "troubleshooti.ng": "排障",
  "crowdfundi.ng": "众筹",
  "dropshippi.ng": "代发货",
  "freelanci.ng": "自由职业",
  "ghostwriti.ng": "代笔",
  "outsourci.ng": "外包",
  "surfi.ng": "冲浪",
  "paraglidi.ng": "滑翔伞",
  "skydivi.ng": "跳伞",
  "mountianeri.ng": "登山(缩)",
  "engineeri.ng": "工程",
  "volunteeri.ng": "志愿服务",
  "campaigni.ng": "竞选",
  "fundraisi.ng": "筹款",
  "mentori.ng": "指导",
};
