// Word-level Chinese meanings — maps English words directly to Chinese
// Used as fallback when no domain-specific meaning exists
// Format: "english_word" -> "中文释义"

export const WORD_MEANINGS_WORDS: Record<string, string> = {
  // ── 科技 / Tech ──────────────────────────────────────────────────────────
  app: "应用", apps: "应用", code: "代码", dev: "开发", tech: "科技",
  data: "数据", api: "接口", web: "网络", net: "网络", cloud: "云端",
  host: "主机", site: "站点", blog: "博客", chat: "聊天", mail: "邮件",
  link: "链接", hack: "黑客", open: "开源", node: "节点", base: "基础",
  core: "核心", hub: "中心", lab: "实验室", io: "输入输出", bot: "机器人",
  ai: "人工智能", ml: "机器学习", gpu: "图形处理器", cpu: "处理器",
  server: "服务器", client: "客户端", proxy: "代理", cache: "缓存",
  token: "令牌", auth: "认证", key: "密钥", hash: "哈希", log: "日志",
  port: "端口", domain: "域名", dns: "域名解析", ssl: "安全证书",
  git: "版本控制", cli: "命令行", sdk: "开发套件", ide: "集成开发环境",
  debug: "调试", deploy: "部署", build: "构建", test: "测试", run: "运行",
  stack: "技术栈", front: "前端", back: "后端", full: "全栈",
  mobile: "移动端", desktop: "桌面端", browser: "浏览器",
  pixel: "像素", icon: "图标", theme: "主题", dark: "深色", light: "浅色",

  // ── 商业 / Business ───────────────────────────────────────────────────────
  shop: "购物", store: "商店", buy: "购买", sell: "销售", pay: "支付",
  cash: "现金", bank: "银行", fund: "基金", trade: "交易", deal: "交易",
  market: "市场", brand: "品牌", sale: "销售", price: "价格", cost: "成本",
  profit: "利润", gain: "收益", earn: "赚取", invest: "投资",
  startup: "创业", business: "商业", company: "公司", firm: "公司",
  corp: "公司", inc: "公司", ltd: "有限公司", group: "集团",
  agency: "机构", media: "媒体", press: "新闻", news: "新闻",
  post: "发帖", list: "清单", plan: "计划", work: "工作", job: "工作",
  hire: "招聘", staff: "员工", team: "团队", lead: "领导", manage: "管理",

  // ── 生活 / Life ───────────────────────────────────────────────────────────
  life: "生活", live: "生活", home: "家", house: "房子", room: "房间",
  city: "城市", town: "城镇", land: "土地", place: "地方", space: "空间",
  world: "世界", earth: "地球", nature: "自然", green: "绿色", blue: "蓝色",
  red: "红色", gold: "金色", white: "白色", black: "黑色",
  food: "食物", eat: "吃", drink: "饮料", cook: "烹饪", meal: "餐食",
  water: "水", juice: "果汁", milk: "牛奶", wine: "葡萄酒", beer: "啤酒",
  cafe: "咖啡厅", bar: "酒吧", hotel: "酒店", travel: "旅行",
  trip: "旅途", tour: "游览", road: "道路", walk: "步行", run: "跑步",
  sport: "运动", game: "游戏", play: "玩耍", fun: "趣味", joy: "欢乐",
  love: "爱", heart: "心", care: "关爱", hope: "希望", dream: "梦想",
  mind: "思维", soul: "灵魂", body: "身体", health: "健康", fit: "健身",
  yoga: "瑜伽", gym: "健身房", bike: "自行车", ride: "骑行", swim: "游泳",

  // ── 教育 / Education ──────────────────────────────────────────────────────
  learn: "学习", study: "学习", teach: "教学", school: "学校",
  class: "课程", book: "书籍", read: "阅读", write: "写作",
  note: "笔记", quiz: "测验", exam: "考试", grade: "成绩",
  skill: "技能", know: "知识", think: "思考", idea: "创意",
  smart: "聪明", wise: "智慧", edu: "教育", course: "课程",
  guide: "指南", help: "帮助", tip: "提示", how: "如何", why: "为何",

  // ── 社交 / Social ─────────────────────────────────────────────────────────
  share: "分享", like: "喜欢", follow: "关注", friend: "朋友",
  social: "社交", connect: "连接", meet: "见面", join: "加入",
  club: "俱乐部", group: "群组", forum: "论坛", talk: "交谈",
  say: "说", ask: "提问", answer: "回答", reply: "回复",
  vote: "投票", rate: "评分", review: "评价", comment: "评论",
  tag: "标签", feed: "动态", story: "故事", photo: "照片",
  video: "视频", live: "直播", stream: "流媒体", cast: "播放",

  // ── 创意 / Creative ───────────────────────────────────────────────────────
  art: "艺术", design: "设计", draw: "绘画", paint: "绘画",
  music: "音乐", song: "歌曲", beat: "节拍", sound: "声音",
  voice: "声音", show: "展示", make: "制作", create: "创作",
  build: "构建", craft: "工艺", studio: "工作室", pro: "专业",
  digital: "数字", pixel: "像素", frame: "帧", motion: "动态",
  style: "风格", mode: "模式", color: "颜色", view: "视图",
  print: "印刷", paper: "纸张", book: "书籍", page: "页面",
  type: "排版", font: "字体", logo: "标志", brand: "品牌",

  // ── 工具 / Utility ────────────────────────────────────────────────────────
  tool: "工具", kit: "工具包", pack: "打包", zip: "压缩",
  send: "发送", get: "获取", set: "设置", add: "添加",
  save: "保存", load: "加载", sync: "同步", update: "更新",
  delete: "删除", edit: "编辑", copy: "复制", move: "移动",
  search: "搜索", find: "查找", sort: "排序", filter: "筛选",
  scan: "扫描", read: "读取", write: "写入", parse: "解析",
  convert: "转换", export: "导出", import: "导入", merge: "合并",
  split: "分割", join: "合并", map: "映射", list: "列表",
  table: "表格", form: "表单", chart: "图表", graph: "图形",
  dash: "仪表", report: "报告", track: "追踪", monitor: "监控",
  alert: "警报", notify: "通知", remind: "提醒", timer: "定时器",

  // ── 常见词根 / Common roots ───────────────────────────────────────────────
  able: "能够", able: "能够", active: "活跃", actual: "实际",
  best: "最佳", better: "更好", big: "大型", bright: "明亮",
  clean: "清洁", clear: "清晰", close: "关闭", cool: "酷炫",
  daily: "每日", deep: "深度", direct: "直接", easy: "简单",
  easy: "简易", fast: "快速", final: "最终", first: "第一",
  free: "免费", fresh: "新鲜", good: "良好", great: "出色",
  happy: "快乐", hard: "努力", high: "高端", hot: "热门",
  just: "公正", kind: "友善", large: "大型", last: "最终",
  local: "本地", long: "长期", low: "低价", main: "主要",
  mega: "超级", micro: "微型", mini: "小型", more: "更多",
  most: "最多", much: "很多", multi: "多元", new: "新型",
  next: "下一个", nice: "优质", now: "即时", old: "传统",
  only: "唯一", open: "开放", own: "自有", pure: "纯粹",
  quick: "快速", real: "真实", rich: "富有", right: "正确",
  safe: "安全", same: "相同", sharp: "锐利", short: "简短",
  simple: "简单", single: "单一", slim: "精简", slow: "慢速",
  small: "小型", soft: "软件", solid: "稳固", soon: "即时",
  special: "特别", strong: "强大", super: "超级", sure: "确实",
  sweet: "甜蜜", true: "真实", turbo: "极速", ultra: "超级",
  unique: "独特", up: "向上", use: "使用", useful: "实用",
  valid: "有效", vast: "广阔", vital: "重要", warm: "温馨",
  well: "良好", wide: "广泛", wise: "明智", zero: "零点",

  // ── 常见后缀词汇 / Common suffix words ────────────────────────────────────
  action: "行动", active: "活跃", agency: "代理", agent: "代理",
  alpha: "第一", ance: "服务", any: "任意", area: "区域",
  bank: "银行", base: "基础", bin: "仓库", bit: "比特",
  box: "容器", byte: "字节", camp: "营地", card: "卡片",
  cast: "播放", center: "中心", chain: "链条", channel: "频道",
  chart: "图表", check: "检查", chip: "芯片", city: "城市",
  click: "点击", cloud: "云端", cluster: "集群", co: "公司",
  coin: "代币", collect: "收集", connect: "连接", console: "控制台",
  content: "内容", control: "控制", corner: "角落", craft: "工艺",
  crew: "团队", cross: "交叉", crowd: "人群", crypt: "加密",
  cube: "立方", culture: "文化", cycle: "循环",
  demo: "演示", deploy: "部署", desk: "桌面", direct: "直连",
  disk: "磁盘", dock: "停靠", drop: "下拉", dynamic: "动态",
  edge: "边缘", element: "元素", engine: "引擎", entity: "实体",
  event: "事件", expert: "专家", extend: "扩展",
  factory: "工厂", feed: "数据流", field: "字段", fire: "火热",
  fix: "修复", flag: "标志", flash: "闪存", flex: "灵活",
  flow: "流程", fly: "快飞", focus: "焦点", force: "力量",
  fork: "分支", format: "格式", forward: "转发",
  gen: "生成", geo: "地理", globe: "全球", grid: "网格",
  guard: "保护", guide: "指引",
  hyper: "超级",
  image: "图像", index: "索引", info: "信息", insight: "洞察",
  instant: "即时", intel: "情报", inter: "互联", invest: "投资",
  jet: "喷射", jump: "跳转",
  kit: "套件", knock: "触发",
  layer: "层", launch: "发布", learn: "学习", lens: "视角",
  level: "级别", line: "线路",
  master: "主控", matrix: "矩阵", meta: "元数据", meter: "计量",
  metrics: "指标", mode: "模式", module: "模块", mono: "单一",
  mount: "挂载",
  nano: "纳米", nest: "嵌套",
  omega: "终极", omni: "全方位",
  panel: "面板", path: "路径", pattern: "模式", peer: "对等",
  pipeline: "管道", platform: "平台", plug: "插件", pod: "容器",
  pool: "资源池", portal: "门户",
  query: "查询", queue: "队列",
  rack: "架构", range: "范围", relay: "转发", remote: "远程",
  render: "渲染", repo: "仓库", request: "请求", resource: "资源",
  rest: "接口", role: "角色", root: "根目录", router: "路由",
  rule: "规则",
  scope: "范围", script: "脚本", secure: "安全", seed: "种子",
  sensor: "传感器", service: "服务", session: "会话", setup: "配置",
  signal: "信号", smart: "智能", snap: "快照", source: "来源",
  spark: "火花", spec: "规格", speed: "速度", sphere: "领域",
  spin: "旋转", sprint: "冲刺", stage: "阶段", state: "状态",
  stats: "统计", status: "状态", stream: "流", struct: "结构",
  switch: "切换", system: "系统",
  task: "任务", template: "模板", terminal: "终端", text: "文本",
  thread: "线程", tick: "计时", track: "追踪", transfer: "传输",
  trigger: "触发",
  unit: "单元",
  vector: "向量", verify: "验证", version: "版本", view: "视图",
  void: "空值", volume: "卷",
  watch: "监听", wave: "波动", widget: "组件", wire: "连线",
  wrap: "包装",
  yield: "产出",
  zone: "区域",
};
