/**
 * word-meanings-extra10.ts — Chinese + English meanings for extra10 word library
 * Covers: .ee .lk .ro .bo .do .no .to .net .tz .cy .mn .by .eu .uk .ly .us .in .at .it
 *         .de .re .sh .ve .ge .se .pe .al .me .er .ne .rs .am supplements
 */
export const WORD_MEANINGS_EXTRA10: Record<string, string> = {

  // ── .ee domain hacks ───────────────────────────────────────────────────────
  "fr.ee":       "免费的；自由的",
  "tr.ee":       "树",
  "thr.ee":      "三",
  "agr.ee":      "同意；赞成",
  "degr.ee":     "度；程度；学位",
  "guarant.ee":  "保证；担保",
  "employ.ee":   "员工",
  "refug.ee":    "难民",
  "commit.ee":   "委员会",
  "trust.ee":    "受托人；理事",
  "train.ee":    "实习生",
  "devot.ee":    "爱好者；信徒",
  "escap.ee":    "逃跑者",
  "nomin.ee":    "被提名人",
  "honor.ee":    "受表彰者",
  "absent.ee":   "缺席者",
  "detain.ee":   "被拘留者",
  "attend.ee":   "与会者",
  "appont.ee":   "被任命者",
  "licens.ee":   "被许可人",
  "pay.ee":      "收款人",
  "retir.ee":    "退休人员",
  "coff.ee":     "咖啡",
  "b.ee":        "蜜蜂",

  // ── .lk domain hacks ───────────────────────────────────────────────────────
  "si.lk":   "丝绸",
  "mi.lk":   "牛奶",
  "bi.lk":   "欺骗；拖欠",
  "bu.lk":   "体积；大量",
  "su.lk":   "生闷气",
  "hu.lk":   "绿巨人；大块",
  "sku.lk":  "潜伏",
  "fo.lk":   "民间的；人们",
  "cha.lk":  "粉笔",
  "wa.lk":   "行走；步行",
  "ta.lk":   "交谈；讲话",
  "sta.lk":  "茎；跟踪",
  "ba.lk":   "拒绝；障碍",

  // ── .ro domain hacks ───────────────────────────────────────────────────────
  "he.ro":    "英雄",
  "ze.ro":    "零；零点",
  "mic.ro":   "微型的",
  "mac.ro":   "宏；宏观",
  "int.ro":   "介绍；序曲",
  "met.ro":   "地铁",
  "ret.ro":   "复古",
  "gy.ro":    "陀螺仪；旋转",
  "hyd.ro":   "氢；水力",
  "nit.ro":   "硝基；快速",
  "elect.ro": "电子的",
  "bist.ro":  "小酒馆",
  "mae.st.ro":"大师；指挥家",
  "allegro":  "快板（音乐）",
  "p.ro":     "专业的；职业",
  "eu.ro":    "欧元",

  // ── .bo domain hacks ───────────────────────────────────────────────────────
  "tur.bo":   "涡轮增压",
  "com.bo":   "组合；套餐",
  "lim.bo":   "困境；地狱边境",
  "bim.bo":   "金发美女（贬义）",
  "jum.bo":   "超大的",
  "gazet.bo": "花园凉亭",
  "place.bo": "安慰剂",
  "mam.bo":   "曼博舞",

  // ── .do domain hacks ───────────────────────────────────────────────────────
  "avoca.do":     "牛油果",
  "torna.do":     "龙卷风",
  "torpe.do":     "鱼雷",
  "aficiona.do":  "狂热爱好者",
  "despera.do":   "亡命徒",
  "brava.do":     "虚张声势",
  "innuen.do":    "暗示；影射",
  "libi.do":      "性欲；欲望",
  "stu.dio":      "工作室",
  "ju.do":        "柔道",
  "un.do":        "撤销；解开",
  "pseu.do":      "伪装的；假的",

  // ── .no domain hacks ───────────────────────────────────────────────────────
  "casi.no":    "赌场",
  "volca.no":   "火山",
  "pia.no":     "钢琴",
  "sopra.no":   "女高音",
  "dyna.mo":    "发电机；充沛精力",
  "rhi.no":     "犀牛",
  "tech.no":    "电子音乐；科技",
  "lati.no":    "拉丁裔",
  "ami.no":     "氨基（-amino）",
  "albi.no":    "白化病；白化",
  "bambi.no":   "小孩（意大利语）",
  "cappucci.no":"卡布奇诺",
  "domı.no":    "多米诺",
  "espress.o":  "浓缩咖啡",
  "infr.o":     "下方的",
  "monac.o":    "摩纳哥",
  "neutr.ino":  "中微子",

  // ── .to domain hacks ───────────────────────────────────────────────────────
  "pho.to":    "照片",
  "au.to":     "自动的；汽车",
  "al.to":     "中音；高音女",
  "grot.to":   "洞穴",
  "lot.to":    "乐透彩票",
  "mot.to":    "座右铭",
  "risot.to":  "意大利烩饭",
  "ghet.to":   "贫民窟",
  "manifes.to":"宣言",
  "pes.to":    "香蒜酱",
  "pres.to":   "快速地；魔法",
  "gus.to":    "热情；美味",
  "pron.to":   "立即；迅速",
  "ben.to":    "便当",
  "memen.to":  "纪念品",
  "incogni.to":"匿名的；隐身",
  "vibra.to":  "颤音",
  "stacca.to": "断奏（音乐）",
  "pota.to":   "土豆",
  "toma.to":   "西红柿",
  "torpe.do":  "鱼雷",
  "concerto":  "协奏曲",
  "falsetto":  "假声；假嗓",
  "stiletto":  "细跟高跟鞋",
  "libretto":  "歌剧台本",

  // ── .tz domain hacks ───────────────────────────────────────────────────────
  "bli.tz":   "闪电战",
  "gli.tz":   "浮华；炫耀",
  "ri.tz":    "豪华；奢侈",
  "wal.tz":   "华尔兹",
  "her.tz":   "赫兹（频率单位）",
  "quar.tz":  "石英",

  // ── .cy domain hacks ───────────────────────────────────────────────────────
  "democra.cy":  "民主",
  "diplo.ma.cy": "外交",
  "accura.cy":   "准确性",
  "adequa.cy":   "充足",
  "advoca.cy":   "倡导；宣传",
  "bureauc.ra.cy":"官僚",
  "conspira.cy": "阴谋",
  "suprema.cy":  "最高权力",
  "pharma.cy":   "药房",
  "lega.cy":     "遗产；遗留",
  "agen.cy":     "机构；代理",
  "urgen.cy":    "紧迫性",
  "curren.cy":   "货币；时效",
  "efficiен.cy": "效率",
  "presiden.cy": "总统职位",
  "emergen.cy":  "紧急情况",
  "frequen.cy":  "频率",
  "transparen.cy":"透明度",
  "redunnan.cy": "冗余",
  "litera.cy":   "读写能力",
  "pira.cy":     "盗版；海盗",
  "priva.cy":    "隐私",
  "fluen.cy":    "流利度",
  "proficien.cy":"熟练度",

  // ── .mn domain hacks ───────────────────────────────────────────────────────
  "autu.mn":  "秋天",
  "colu.mn":  "专栏；列",
  "sole.mn":  "庄严的；郑重",
  "conde.mn": "谴责；判决",
  "hy.mn":    "赞美诗；颂歌",

  // ── .by domain hacks ───────────────────────────────────────────────────────
  "lullab.y":   "摇篮曲",
  "standb.y":   "备用；待命",
  "whereb.y":   "借此",
  "hereb.y":    "特此；据此",
  "thereb.y":   "因此；从而",
  "nearb.y":    "附近",
  "flyb.y":     "飞越；飞过",

  // ── .eu domain hacks ───────────────────────────────────────────────────────
  "qu.eu.e": "队列；排队",
  "mili.eu": "社会环境；圈子",
  "tablea.u":"小插曲；静态画面",
  "plate.au":"高原；停滞期",
  "bure.au": "局；办公室",
  "adieu":   "告别",

  // ── .uk domain hacks ───────────────────────────────────────────────────────
  "luc.k":   "运气",
  "truc.k":  "卡车",
  "plu.ck":  "勇气；拔除",
  "chu.ck":  "扔；丢弃",

  // ── .lv domain hacks ───────────────────────────────────────────────────────
  "so.lve":   "解决；溶解",
  "evo.lve":  "进化；演变",
  "revo.lve": "旋转；思考",
  "invo.lve": "涉及；包含",
  "reso.lve": "决心；解决",
  "abso.lve": "赦免；免除",
  "disso.lve":"溶解；解散",
  "two.lve":  "十二",

  // ── .af domain hacks ───────────────────────────────────────────────────────
  "le.af":   "叶子；树叶",
  "lo.af":   "面包条；懒汉",
  "behal.f": "代表；利益",
  "hal.f":   "一半",
  "cal.f":   "小牛；腿肚",

  // ── .uy domain hacks ───────────────────────────────────────────────────────
  "b.uy":  "购买",
  "g.uy":  "家伙",

  // ── .py domain hacks ───────────────────────────────────────────────────────
  "hap.py":  "快乐的",
  "chop.py": "波涛汹涌；断断续续",
  "slop.py": "邋遢的；不精确",
  "yap.py":  "叫嚣的；时髦的",
  "zip.py":  "活泼的；快速",
  "hip.py":  "嬉皮士",
  "dip.py":  "蘸的；笨蛋",
  "nip.py":  "寒冷刺鼻的",
  "whis.py": "低语的",

  // ── .ee supplement ─────────────────────────────────────────────────────────
  "sn.ee.ze": "打喷嚏",
  "br.ee.ze": "微风",
  "fr.ee.ze": "冻结",
  "squ.ee.ze":"挤压",

  // ── .ne supplement ─────────────────────────────────────────────────────────
  "onli.ne":    "在线的",
  "airli.ne":   "航空公司",
  "sunshi.ne":  "阳光",
  "deadli.ne":  "截止日期",
  "pipeli.ne":  "管道；流水线",
  "timeli.ne":  "时间线",
  "baseli.ne":  "基准线",
  "headli.ne":  "头条新闻",
  "skyli.ne":   "天际线",
  "engi.ne":    "引擎；发动机",
  "routi.ne":   "例行；常规",
  "mari.ne":    "海洋的；海军",
  "vacci.ne":   "疫苗",
  "machin.e":   "机器",
  "pho.ne":     "电话",
  "sto.ne":     "石头；结石",
  "bo.ne":      "骨头",
  "zo.ne":      "区域；地带",
  "dro.ne":     "无人机；嗡嗡声",
  "thro.ne":    "王位；宝座",
  "ozo.ne":     "臭氧",
  "backbo.ne":  "脊梁；骨干",
  "milesto.ne": "里程碑",

  // ── .re supplement ─────────────────────────────────────────────────────────
  "softwa.re":  "软件",
  "hardwa.re":  "硬件",
  "shareware":  "共享软件",
  "freewa.re":  "免费软件",
  "middlewa.re":"中间件",
  "healthca.re":"医疗保健",
  "requireme.nt":"需求",
  "inspir.e":   "激励；启发",
  "acquir.e":   "获取；习得",
  "admir.e":    "欣赏；钦佩",
  "retir.e":    "退休",
  "evermor.e":  "永远",
  "herbivo.re": "草食动物",
  "carnivo.re": "肉食动物",
  "omnivo.re":  "杂食动物",

  // ── .de supplement ─────────────────────────────────────────────────────────
  "homicid.e":  "杀人罪",
  "pesticid.e": "农药；杀虫剂",
  "herbicid.e": "除草剂",
  "fungicid.e": "杀菌剂",
  "genocid.e":  "种族灭绝",
  "peroxid.e":  "过氧化物",
  "dioxid.e":   "二氧化物",
  "encod.e":    "编码",
  "decod.e":    "解码",
  "explod.e":   "爆炸",
  "insid.e":    "内部；里面",
  "outsid.e":   "外部；外面",
  "worldwid.e": "全球的",
  "overrid.e":  "覆盖；压倒",
  "homemad.e":  "自制的",
  "handmad.e":  "手工制作",

  // ── .sh supplement ─────────────────────────────────────────────────────────
  "vanqui.sh":   "征服；击败",
  "distingui.sh":"区分；辨别",
  "extingui.sh": "熄灭；扑灭",
  "aston.ish":   "使惊奇",
  "demol.ish":   "拆毁；摧毁",
  "pol.ish":     "擦亮；波兰的",
  "pubi.sh":     "发布；出版",
  "brai.nwash":  "洗脑",
  "mouthwa.sh":  "漱口水",

  // ── .ve supplement ─────────────────────────────────────────────────────────
  "na.ive":      "天真的",
  "bra.ve":      "勇敢的",
  "cra.ve":      "渴望",
  "gra.ve":      "严肃的；墓穴",
  "wa.ve":       "波浪；挥手",
  "sla.ve":      "奴隶",
  "engra.ve":    "雕刻",
  "slee.ve":     "袖子",
  "achie.ve":    "实现；达到",
  "belie.ve":    "相信",
  "concei.ve":   "构想；怀孕",
  "decei.ve":    "欺骗",
  "percei.ve":   "感知",
  "recei.ve":    "接收",
  "reprie.ve":   "暂缓执行",
  "retrie.ve":   "检索；找回",
  "relie.ve":    "减轻；救济",

  // ── .ge supplement ─────────────────────────────────────────────────────────
  "ag.e":        "年龄；时代",
  "ca.ge":       "笼子",
  "ra.ge":       "愤怒；风靡",
  "sta.ge":      "阶段；舞台",
  "pa.ge":       "页面",
  "hu.ge":       "巨大的",
  "kno.wledge":  "知识",
  "privile.ge":  "特权",
  "acknowled.ge":"承认",
  "dama.ge":     "损坏；损失",
  "banda.ge":    "绷带",
  "bonda.ge":    "束缚",
  "blocka.ge":   "阻塞",
  "foota.ge":    "镜头；面积",
  "shorta.ge":   "短缺；不足",
  "hostа.ge":    "人质",
  "postа.ge":    "邮资",
  "stoра.ge":    "存储；仓储",
  "cleava.ge":   "劈开；沟壑",
  "heri.ta.ge":  "遗产；传统",

  // ── .se supplement ─────────────────────────────────────────────────────────
  "choo.se":    "选择",
  "abу.se":     "滥用；虐待",
  "amu.se":     "娱乐；逗笑",
  "confu.se":   "混淆；迷惑",
  "concis.e":   "简洁的",
  "precis.e":   "精确的",
  "enterpri.se":"企业；事业",
  "merchand.ise":"商品",
  "exerci.se":  "锻炼；练习",
  "paradi.se":  "天堂",
  "recogni.ze": "认识；承认",
  "organi.ze":  "组织；整理",
  "adverti.se": "广告；宣传",
  "emphasi.ze": "强调",
  "memori.ze":  "记忆；背诵",

  // ── .pe supplement ─────────────────────────────────────────────────────────
  "genoty.pe":   "基因型",
  "phenoty.pe":  "表现型",
  "proto.ty.pe": "原型",
  "stereoты.pe": "刻板印象",
  "archetу.pe":  "原型；典型",
  "pi.pe":       "管道；笛子",
  "ty.pe":       "类型；输入",
  "hy.pe":       "炒作；过度宣传",
  "elo.pe":      "私奔",
  "tro.pe":      "比喻；修辞手法",
  "antelo.pe":   "羚羊",
  "tele.sco.pe": "望远镜",
  "kaleido.sco.pe":"万花筒",
  "horosco.pe":  "星座运势",

  // ── .al supplement ─────────────────────────────────────────────────────────
  "internation.al": "国际的",
  "convention.al":  "传统的；惯例",
  "exception.al":   "例外的；卓越",
  "fundament.al":   "基本的；根本",
  "environment.al": "环境的",
  "government.al":  "政府的",
  "departement.al": "部门的",
  "experiment.al":  "实验性的",
  "monument.al":    "宏伟的；纪念",
  "emotion.al":     "情感的；感性",
  "option.al":      "可选的",
  "nation.al":      "国家的",
  "person.al":      "个人的",
  "season.al":      "季节性的",
  "glob.al":        "全球的",
  "loc.al":         "本地的；局部",
  "voc.al":         "声乐的；有声",
  "tot.al":         "总计；完全",
  "vit.al":         "至关重要的",
  "digit.al":       "数字的",
  "capit.al":       "首都；资本",
  "hospit.al":      "医院",
  "port.al":        "门户网站",
  "visu.al":        "视觉的",
  "virtu.al":       "虚拟的",
  "spir.itu.al":    "精神的",
  "intellect.u.al": "智力的；知识分子",
  "individu.al":    "个人；个体",
  "arriv.al":       "到达",
  "surviv.al":      "生存",
  "festiv.al":      "节日；庆典",
  "carniv.al":      "狂欢节",
  "approv.al":      "批准；认可",
  "remov.al":       "移除；免职",
  "renew.al":       "更新；续约",
  "revers.al":      "逆转；撤销",
  "dispos.al":      "处置；安排",
  "propos.al":      "提案；求婚",
  "refus.al":       "拒绝",

  // ── .me supplement ─────────────────────────────────────────────────────────
  "handso.me":   "英俊的",
  "wholeso.me":  "有益健康的",
  "loneso.me":   "孤独的",
  "aweso.me":    "令人惊叹的",
  "fearso.me":   "令人恐惧的",
  "troubleso.me":"麻烦的",
  "overco.me":   "克服；战胜",
  "anı.me":      "日本动漫",
  "geno.me":     "基因组",
  "progra.mme":  "程序；节目",
  "regi.me":     "政权；制度",
  "me.me":       "表情包；梗",
  "resu.me":     "简历；恢复",
  "presu.me":    "假定；推测",
  "consu.me":    "消费；消耗",

  // ── .in supplement ─────────────────────────────────────────────────────────
  "peng.uin":    "企鹅",
  "dolp.hin":    "海豚",
  "pump.kin":    "南瓜",
  "muff.in":     "松饼",
  "napk.in":     "餐巾纸",
  "gob.lin":     "哥布林；小妖精",
  "cous.in":     "表兄弟姐妹",
  "adrenalin":   "肾上腺素",
  "insul.in":    "胰岛素",
  "aspir.in":    "阿司匹林",
  "penicil.lin": "青霉素",
  "mелатонин":   "褪黑素",
  "seroton.in":  "血清素",
  "endorphin":   "内啡肽",

  // ── .am supplement ─────────────────────────────────────────────────────────
  "aquar.ium":   "水族馆",
  "millen.nium": "千禧年",
  "auditor.ium": "礼堂",
  "consort.ium": "联盟；财团",
  "empor.ium":   "大商场",
  "gymnas.ium":  "体育馆",
  "planetar.ium":"天文馆",
  "solar.ium":   "日光浴室",
  "vibrar.ium":  "生态缸",
  "memoriam":    "悼念；纪念",

  // ── .at supplement ─────────────────────────────────────────────────────────
  "diplom.at":   "外交官",
  "technocr.at": "技术官僚",
  "bureaucr.at": "官僚",
  "autocr.at":   "独裁者",
  "plutocr.at":  "财阀",
  "democrat":    "民主党人",
  "aristocrat":  "贵族",
  "form.at":     "格式；格式化",
  "comb.at":     "战斗；对抗",
  "acrob.at":    "杂技演员",
  "habit.at":    "栖息地",
  "thermostаt":  "温控器",
  "doorm.at":    "门垫",
  "overco.at":   "外套；大衣",
  "throаt":      "喉咙",
  "flo.at":      "漂浮",
  "bo.at":       "船",
  "go.at":       "山羊",

  // ── .it supplement ─────────────────────────────────────────────────────────
  "circuіt":    "电路；巡回",
  "cred.it":    "信用；学分",
  "deb.it":     "借记；扣款",
  "aud.it":     "审计",
  "vis.it":     "访问；参观",
  "spir.it":    "精神；灵魂",
  "mer.it":     "优点；功绩",
  "lim.it":     "限制；极限",
  "vomit":      "呕吐",
  "herm.it":    "隐士",
  "gambit":     "开局策略",
  "hab.it":     "习惯",
  "rabb.it":    "兔子",
  "band.it":    "强盗；歹徒",
  "pund.it":    "专家；评论员",
  "verd.ict":   "裁决；判决",
  "pred.ict":   "预测；预言",
  "restr.ict":  "限制；约束",
  "conflіct":   "冲突；矛盾",
  "distr.ict":  "地区；区域",
  "ext.inct":   "灭绝的",
  "dist.inct":  "独特的；明显",

  // ── .us supplement ─────────────────────────────────────────────────────────
  "octop.us":   "章鱼",
  "platyp.us":  "鸭嘴兽",
  "omnibs.us":  "公共汽车",
  "cact.us":    "仙人掌",
  "stat.us":    "状态；身份",
  "nex.us":     "核心；联系",
  "cens.us":    "人口普查",
  "imрet.us":   "动力；势头",
  "hiат.us":    "中断；空档",
  "appar.atus": "仪器；装置",
  "prosp.ect.us":"说明书",
  "syll.ab.us": "课程大纲",
  "stimul.us":  "刺激物；激励",
  "termin.us":  "终点站",
  "camp.us":    "校园",
  "foc.us":     "焦点；集中",
  "bоn.us":     "奖金；红利",

  // ── .ly supplement ─────────────────────────────────────────────────────────
  "exact.ly":        "确切地",
  "direct.ly":       "直接地",
  "perfect.ly":      "完美地",
  "correct.ly":      "正确地",
  "current.ly":      "目前；当前",
  "frequent.ly":     "频繁地",
  "constant.ly":     "不断地",
  "efficient.ly":    "有效地",
  "sufficient.ly":   "充分地",
  "significant.ly":  "显著地",
  "independent.ly":  "独立地",
  "consistent.ly":   "一贯地",
  "transparent.ly":  "透明地",
  "effectively":     "有效地",
  "essentially":     "本质上",
  "particular.ly":   "尤其",
  "occasion.al.ly":  "偶尔地",
  "extreme.ly":      "极其",
  "entire.ly":       "完全地",
  "increasing.ly":   "越来越",
  "surprising.ly":   "令人惊讶地",
  "overwhelm.ing.ly":"压倒性地",

  // ── .rs supplement ─────────────────────────────────────────────────────────
  "hack.ers":    "黑客们",
  "cod.ers":     "程序员们",
  "mak.ers":     "创造者们",
  "found.ers":   "创始人们",
  "build.ers":   "建设者们",
  "lead.ers":    "领导者们",
  "teach.ers":   "教师们",
  "think.ers":   "思想家们",
  "dream.ers":   "梦想者们",
  "creat.ors":   "创造者们",
  "network.ers": "网络人脉",
  "framew.orks": "框架",
  "bookm.arks":  "书签",

  // ── .er supplement ─────────────────────────────────────────────────────────
  "hack.er":       "黑客",
  "cod.er":        "程序员",
  "stream.er":     "主播；流媒体",
  "gam.er":        "玩家",
  "design.er":     "设计师",
  "contribut.or":  "贡献者",
  "administrat.or":"管理员",
  "monster":       "怪物",
  "lobst.er":      "龙虾",
  "gangst.er":     "歹徒",
  "hipst.er":      "时髦人士",
  "found.er":      "创始人",
  "wond.er":       "奇迹；想知道",
  "thund.er":      "雷；雷声",
  "surrend.er":    "投降；放弃",
  "def.end.er":    "捍卫者",
  "calendаr":      "日历",
  "cylind.er":     "圆柱体",
  "lavend.er":     "薰衣草",
  "record.er":     "录音机；记录者",
  "disord.er":     "失调；混乱",
  "encount.er":    "遭遇；邂逅",
  "togeth.er":     "一起；共同",
  "feath.er":      "羽毛",
  "leath.er":      "皮革",
  "weath.er":      "天气",
  "superpower":    "超级力量",
  "cyb.er":        "网络的",
  "sup.er":        "超级的",
  "hyp.er":        "过度兴奋的",
  "remem.ber":     "记住；记得",
  "numb.er":       "数字；号码",
  "chamb.er":      "室；腔室",
  "memb.er":       "成员；成员",
};
