// Extra Chinese meanings for domain hack words — merged at runtime
// Avoids duplicate key issues with the base file

export const WORD_MEANINGS_EXTRA: Record<string, string> = {
  // .ve words
  "lo.ve": "爱",
  "mo.ve": "移动",
  "li.ve": "生活/直播",
  "gi.ve": "给予",
  "ha.ve": "拥有",
  "sa.ve": "保存/节省",
  "wa.ve": "波浪",
  "ca.ve": "洞穴",
  "bra.ve": "勇敢的",
  "gra.ve": "严肃/坟墓",
  "sla.ve": "奴隶",
  "sha.ve": "剃须",
  "cra.ve": "渴望",
  "pro.ve": "证明",
  "appro.ve": "批准",
  "impro.ve": "改善",
  "remo.ve": "移除",
  "resol.ve": "解决",
  "invol.ve": "涉及",
  "evol.ve": "进化",
  "obser.ve": "观察",
  "preser.ve": "保存",
  "conser.ve": "保护",
  "deser.ve": "值得",
  "ser.ve": "服务",
  "ner.ve": "神经",
  "cur.ve": "曲线",
  "archi.ve": "档案",
  "acti.ve": "积极的",
  "massi.ve": "巨大的",
  "nati.ve": "本地的",
  "creati.ve": "创造性的",
  "negati.ve": "消极的",
  "positi.ve": "积极的",
  "sensiti.ve": "敏感的",
  "exclusi.ve": "独家的",
  "impressi.ve": "令人印象深刻的",
  "ali.ve": "活着的",
  "arri.ve": "到达",
  "dri.ve": "驾驶/驱动",
  "di.ve": "潜水",
  "fi.ve": "五",
  "thri.ve": "茁壮成长",
  "survi.ve": "生存",

  // .om words
  "ro.om": "房间",
  "bro.om": "扫帚",
  "blo.om": "开花",
  "do.om": "厄运",
  "bo.om": "繁荣/爆炸",
  "zo.om": "缩放",
  "glo.om": "忧郁",
  "kingd.om": "王国",
  "freed.om": "自由",
  "bored.om": "无聊",
  "rand.om": "随机的",
  "wisd.om": "智慧",
  "cust.om": "自定义/习俗",
  "bott.om": "底部",
  "at.om": "原子",
  "idi.om": "习语",
  "axi.om": "公理",
  "h.om": "家(缩)",
  "d.om": "DOM",

  // .to words
  "pho.to": "照片",
  "au.to": "自动",
  "pota.to": "土豆",
  "toma.to": "番茄",
  "ve.to": "否决",
  "mot.to": "座右铭",
  "lot.to": "彩票",
  "burri.to": "卷饼",
  "incogni.to": "隐身",

  // .er words
  "mak.er": "制造者",
  "play.er": "玩家",
  "hack.er": "黑客",
  "cod.er": "程序员",
  "lead.er": "领导者",
  "build.er": "建造者",
  "read.er": "读者",
  "think.er": "思想者",
  "work.er": "工作者",
  "help.er": "帮手",
  "driv.er": "驱动/司机",
  "writ.er": "作家",
  "design.er": "设计师",
  "develop.er": "开发者",
  "engine.er": "工程师",
  "manag.er": "经理",
  "found.er": "创始人",
  "creat.er": "创造者",
  "serv.er": "服务器",
  "brows.er": "浏览器",
  "rout.er": "路由器",
  "dock.er": "容器化平台",
  "compil.er": "编译器",
  "contain.er": "容器",
  "pow.er": "力量/电力",
  "tow.er": "塔",
  "flow.er": "花",
  "nev.er": "永不",
  "ev.er": "曾经",
  "forev.er": "永远",
  "discov.er": "发现",
  "wat.er": "水",
  "aft.er": "之后",
  "bett.er": "更好",
  "mast.er": "大师",

  // .ge words
  "pa.ge": "页面",
  "sta.ge": "舞台",
  "ima.ge": "图像",
  "chan.ge": "改变",
  "ran.ge": "范围",
  "challen.ge": "挑战",
  "messa.ge": "消息",
  "packa.ge": "包",
  "stora.ge": "存储",
  "langua.ge": "语言",
  "avera.ge": "平均",
  "covera.ge": "覆盖",
  "mana.ge": "管理",
  "dama.ge": "损坏",
  "gara.ge": "车库",
  "coura.ge": "勇气",
  "knowled.ge": "知识",
  "brid.ge": "桥梁",
  "jud.ge": "法官/判断",
  "ed.ge": "边缘",
  "pled.ge": "承诺",

  // .ng words
  "codi.ng": "编程",
  "gami.ng": "游戏",
  "maki.ng": "制作",
  "buildi.ng": "建筑/建造",
  "readi.ng": "阅读",
  "worki.ng": "工作",
  "learni.ng": "学习",
  "runni.ng": "跑步",
  "streami.ng": "流媒体",
  "ki.ng": "国王",
  "ri.ng": "戒指/铃声",
  "si.ng": "唱歌",
  "spri.ng": "春天/弹簧",
  "stri.ng": "字符串",
  "thi.ng": "事物",
  "bri.ng": "带来",
  "morni.ng": "早晨",
  "meeti.ng": "会议",

  // .de words
  "co.de": "代码",
  "mo.de": "模式",
  "no.de": "节点",
  "gui.de": "指南",
  "insi.de": "内部",
  "outsi.de": "外部",
  "tra.de": "贸易",
  "gra.de": "等级",
  "bla.de": "刀片",
  "sha.de": "阴影",
  "para.de": "游行",
  "arca.de": "街机",
  "deca.de": "十年",
  "upgra.de": "升级",
  "crusa.de": "远征",
  "ri.de": "骑",
  "hi.de": "隐藏",
  "si.de": "侧面",
  "pri.de": "骄傲",
  "divi.de": "分割",
  "provi.de": "提供",
  "deci.de": "决定",

  // .al words
  "digit.al": "数字的",
  "glob.al": "全球的",
  "loc.al": "本地的",
  "soci.al": "社交的",
  "natur.al": "自然的",
  "virtu.al": "虚拟的",
  "centr.al": "中央的",
  "gener.al": "一般的",
  "capit.al": "资本/首都",
  "hospit.al": "医院",
  "festiv.al": "节日",
  "arriv.al": "到达",
  "surviv.al": "生存",
  "approv.al": "批准",
  "propos.al": "提案",
  "fin.al": "最终的",
  "sign.al": "信号",
  "person.al": "个人的",
  "origin.al": "原始的",
  "crimin.al": "犯罪的",
  "norm.al": "正常的",
  "form.al": "正式的",
  "leg.al": "法律的",
  "equ.al": "平等的",
  "loy.al": "忠诚的",
  "roy.al": "皇家的",
  "tot.al": "总计",
  "fat.al": "致命的",
  "ment.al": "精神的",
  "met.al": "金属",
  "vit.al": "重要的",
  "brut.al": "残酷的",
  "cryst.al": "水晶",

  // .st words
  "be.st": "最好的",
  "te.st": "测试",
  "re.st": "休息",
  "we.st": "西方",
  "ea.st": "东方",
  "fa.st": "快速",
  "la.st": "最后",
  "pa.st": "过去",
  "co.st": "成本",
  "lo.st": "迷失",
  "ho.st": "主人/主机",
  "po.st": "邮件/帖子",
  "mo.st": "最多",
  "gho.st": "鬼",
  "toa.st": "吐司",
  "boo.st": "提升",
  "tru.st": "信任",
  "ju.st": "公正/仅仅",
  "mu.st": "必须",
  "li.st": "列表",
  "exi.st": "存在",
  "resi.st": "抵抗",
  "arti.st": "艺术家",
  "fir.st": "第一",
  "wor.st": "最差",
  "que.st": "追求",
  "gue.st": "客人",
  "intere.st": "兴趣/利息",
  "fore.st": "森林",
  "hone.st": "诚实的",

  // .at words
  "ch.at": "聊天",
  "fl.at": "平的/公寓",
  "c.at": "猫",
  "h.at": "帽子",
  "b.at": "蝙蝠/球棒",
  "bo.at": "船",
  "co.at": "外套",
  "go.at": "山羊",
  "tre.at": "对待/款待",
  "he.at": "热量",
  "se.at": "座位",
  "gre.at": "伟大的",

  // .ch words
  "sear.ch": "搜索",
  "laun.ch": "发射/启动",
  "bran.ch": "分支",
  "mat.ch": "匹配",
  "wat.ch": "手表/观看",
  "cat.ch": "抓住",
  "swit.ch": "开关",
  "ri.ch": "富有的",
  "tea.ch": "教",
  "rea.ch": "到达",
  "bea.ch": "海滩",
  "spee.ch": "演讲",
  "resear.ch": "研究",
  "lun.ch": "午餐",

  // .id words
  "rap.id": "快速的",
  "val.id": "有效的",
  "viv.id": "生动的",
  "sol.id": "固体/坚固",
  "liqu.id": "液体",
  "hybr.id": "混合",
  "andro.id": "安卓",
  "avo.id": "避免",
  "gr.id": "网格",
  "k.id": "小孩",
  "b.id": "出价/投标",
  "flu.id": "流体",
  "pyram.id": "金字塔",
  "splend.id": "壮丽的",

  // .pe words
  "ty.pe": "类型",
  "sha.pe": "形状",
  "esca.pe": "逃脱",
  "ho.pe": "希望",
  "ro.pe": "绳子",
  "slo.pe": "斜坡",
  "sco.pe": "范围",
  "reci.pe": "食谱",
  "prototy.pe": "原型",
  "pi.pe": "管道",
  "stri.pe": "条纹",

  // .is words
  "th.is": "这个",
  "h.is": "他的",
  "cris.is": "危机",
  "bas.is": "基础",
  "analys.is": "分析",
  "thes.is": "论文",
  "genes.is": "起源",
  "oas.is": "绿洲",
  "tenn.is": "网球",
  "ax.is": "轴",

  // .se words
  "clo.se": "关闭",
  "choo.se": "选择",
  "brow.se": "浏览",
  "cour.se": "课程",
  "hor.se": "马",
  "hou.se": "房子",
  "mou.se": "鼠标/老鼠",
  "cau.se": "原因",
  "pau.se": "暂停",
  "phra.se": "短语",
  "cha.se": "追逐",
  "ca.se": "案例/箱子",
  "ba.se": "基础",
  "relea.se": "发布",
  "promi.se": "承诺",
  "surpri.se": "惊喜",
  "pul.se": "脉搏",
  "purpo.se": "目的",
  "respon.se": "回应",
  "inten.se": "强烈的",
  "sen.se": "感觉",
  "defen.se": "防御",
  "rever.se": "反转",
  "univer.se": "宇宙",
  "nur.se": "护士",
  "ro.se": "玫瑰",
  "no.se": "鼻子",
  "expo.se": "暴露",
  "propo.se": "提议",

  // .re words
  "sha.re": "分享",
  "ca.re": "关心",
  "da.re": "敢",
  "ra.re": "稀有的",
  "compa.re": "比较",
  "prepa.re": "准备",
  "awa.re": "意识到的",
  "softwa.re": "软件",
  "hardwa.re": "硬件",
  "befo.re": "之前",
  "explo.re": "探索",
  "resto.re": "恢复",
  "sto.re": "商店",
  "sco.re": "分数",
  "co.re": "核心",
  "mo.re": "更多",
  "futu.re": "未来",
  "natu.re": "自然",
  "cultu.re": "文化",
  "structu.re": "结构",
  "featu.re": "特征",
  "pictu.re": "图片",
  "captu.re": "捕获",
  "inspi.re": "激励",
  "requi.re": "需要",
  "reti.re": "退休",
  "enti.re": "整个",
  "fi.re": "火",
  "hi.re": "雇佣",
  "wi.re": "电线",
  "empi.re": "帝国",
  "admi.re": "钦佩",
  "he.re": "这里",
  "whe.re": "哪里",
  "the.re": "那里",
  "cu.re": "治愈",
  "pu.re": "纯净的",
  "secu.re": "安全的",

  // .tf words
  "cra.tf": "工艺(缩)",
  "dra.tf": "草稿(缩)",
  "gi.tf": "礼物(缩)",
  "shi.tf": "转移(缩)",
  "swi.tf": "迅速(缩)",
  "li.tf": "提升(缩)",

  // .fm words
  "perfor.fm": "表演(缩)",
  "transfor.fm": "变革(缩)",
  "platfor.fm": "平台(缩)",

  // .sm words
  "pri.sm": "棱镜",
  "touri.sm": "旅游",
  "journali.sm": "新闻业",
  "optimi.sm": "乐观主义",
  "reali.sm": "现实主义",
  "enthusia.sm": "热情",
  "sarca.sm": "讽刺",

  // .sc words
  "mu.sc": "音乐(缩)",
  "ba.sc": "基本(缩)",
  "epi.sc": "史诗(缩)",
  "organi.sc": "有机(缩)",
  "dynami.sc": "动态(缩)",
};
