// Word Library Extra 21 - 7+ letter gTLD expansions
// Auto-generated from 370K English word corpus
// 117 TLDs, 486 total words

export const WORD_LIBRARY_EXTRA21: Record<string, string[]> = {
  android: ["gynandroid", "maeandroid", "salamandroid"],
  auction: ["proauction"],
  audible: ["inaudible", "unaudible", "nonaudible", "subaudible"],
  banking: ["embanking", "interbanking"],
  booking: ["overbooking"],
  brother: ["bebrother", "cobrother", "outbrother", "gudebrother", "stepbrother"],
  capital: ["noncapital", "procapital", "anticapital", "supercapital"],
  channel: ["enchannel", "rechannel", "upchannel", "midchannel", "subchannel", "overchannel", "semichannel", "interchannel", "multichannel", "transchannel"],
  charity: ["incharity", "uncharity", "discharity", "procharity", "overcharity"],
  citadel: ["encitadel"],
  college: ["precollege", "subcollege", "intercollege"],
  company: ["accompany", "encompany", "subcompany", "reaccompany", "intercompany", "intracompany", "countercompany"],
  compare: ["recompare", "miscompare", "precompare", "intercompare"],
  contact: ["recontact", "noncontact", "precontact", "postcontact"],
  cooking: ["recooking", "miscooking", "outcooking", "precooking", "overcooking", "undercooking"],
  country: ["upcountry", "outcountry", "backcountry", "semicountry"],
  courses: ["recourses", "concourses", "discourses", "racecourses", "watercourses"],
  cricket: ["outcricket"],
  dentist: ["irredentist"],
  digital: ["predigital", "sexdigital", "basidigital", "polydigital", "postdigital", "interdigital", "mediodigital", "radiodigital", "cubitodigital", "humerodigital", "prestidigital"],
  domains: ["subdomains"],
  exposed: ["reexposed", "unexposed", "preexposed", "overexposed", "semiexposed", "underexposed"],
  express: ["inexpress", "reexpress", "unexpress", "misexpress", "preexpress", "overexpress"],
  fashion: ["refashion", "unfashion", "disfashion", "misfashion", "prefashion", "semifashion", "transfashion"],
  finance: ["refinance", "prefinance", "superfinance", "underfinance"],
  fishing: ["unfishing", "codfishing", "crawfishing", "crayfishing", "overfishing", "blackfishing", "sportfishing", "swordfishing", "electrofishing"],
  fitness: ["unfitness"],
  flights: ["overflights", "spaceflights"],
  flowers: ["beflowers", "deflowers", "reflowers", "dayflowers", "mayflowers", "safflowers", "sunflowers", "cornflowers", "wallflowers", "wildflowers", "windflowers", "cauliflowers"],
  gallery: ["foregallery"],
  grocery: ["greengrocery"],
  heating: ["cheating", "reheating", "escheating", "oilheating", "preheating", "uncheating", "outcheating", "overheating", "superheating"],
  holiday: ["unholiday", "preholiday", "proholiday", "antiholiday", "semiholiday"],
  hosting: ["ghosting", "cohosting"],
  kitchen: ["outkitchen"],
  limited: ["delimited", "illimited", "unlimited", "prelimited", "bandlimited", "undelimited"],
  markets: ["supermarkets"],
  monster: ["bemonster", "semimonster"],
  network: ["garnetwork", "cabinetwork", "metanetwork", "internetwork", "intranetwork"],
  organic: ["morganic", "anorganic", "enorganic", "exorganic", "inorganic", "unorganic", "disorganic", "homorganic", "monorganic", "nonorganic", "preorganic", "suborganic", "cosmorganic", "polyorganic", "semiorganic", "teleorganic", "hyperorganic", "metalorganic", "microorganic", "pseudorganic", "superorganic", "metallorganic", "pseudoorganic", "psychoorganic"],
  recipes: ["precipes"],
  reviews: ["previews"],
  science: ["inscience", "nescience", "unscience", "bioscience", "nonscience", "proscience", "subscience", "antiscience", "autoscience", "transcience", "imprescience", "inconscience", "interscience", "multiscience", "nonnescience", "omninescience", "pseudoscience", "subconscience", "anticonscience"],
  support: ["resupport", "nonsupport", "presupport", "prosupport", "undersupport"],
  surgery: ["presurgery", "cryosurgery", "chemosurgery", "dermasurgery", "microsurgery", "neurosurgery", "radiosurgery", "psychosurgery", "electrosurgery", "galvanosurgery"],
  systems: ["ecosystems", "subsystems", "microsystems"],
  theater: ["ampitheater", "autotheater", "amphitheater"],
  trading: ["retrading", "untrading", "nontrading", "outtrading", "overtrading", "balustrading", "intertrading", "undertrading"],
  watches: ["swatches", "dogwatches", "midwatches", "outwatches", "stopwatches", "deathwatches", "wristwatches"],
  weather: ["aweather", "bellweather", "overweather", "breakweather"],
  winners: ["cowinners", "breadwinners", "prizewinners"],
  attorney: ["subattorney"],
  bargains: ["outbargains"],
  baseball: ["probaseball"],
  builders: ["bodybuilders", "homebuilders", "shipbuilders"],
  business: ["unbusiness", "nonbusiness", "probusiness", "agribusiness", "overbusiness"],
  catering: ["uncatering"],
  catholic: ["acatholic", "uncatholic", "anticatholic", "misocatholic", "philocatholic", "supercatholic"],
  cleaning: ["recleaning", "precleaning", "housecleaning"],
  clothing: ["beclothing", "reclothing", "unclothing", "bedclothing", "preclothing", "underclothing"],
  computer: ["minicomputer", "telecomputer", "microcomputer", "multicomputer", "supercomputer", "multimicrocomputer"],
  delivery: ["redelivery", "undelivery", "misdelivery", "nondelivery", "predelivery"],
  democrat: ["prodemocrat", "antidemocrat"],
  discount: ["rediscount", "prediscount", "overdiscount", "superdiscount"],
  discover: ["rediscover", "prediscover"],
  engineer: ["subengineer", "archengineer", "paraengineer"],
  exchange: ["reexchange", "preexchange", "interexchange"],
  feedback: ["biofeedback"],
  fidelity: ["infidelity", "unfidelity", "nonfidelity"],
  frontier: ["semifrontier", "transfrontier"],
  graphics: ["airgraphics", "diagraphics", "geographics", "aerographics", "demographics", "semigraphics", "telegraphics", "topographics"],
  holdings: ["landholdings", "withholdings", "stockholdings"],
  hospital: ["unhospital"],
  lighting: ["alighting", "blighting", "flighting", "plighting", "slighting", "delighting", "relighting", "uplighting", "daylighting", "gaslighting", "mislighting", "backlighting", "headlighting", "highlighting", "moonlighting", "undelighting", "floodlighting", "candlelighting", "counterlighting"],
  memorial: ["immemorial", "promemorial"],
  mortgage: ["remortgage", "unmortgage", "dismortgage", "submortgage", "overmortgage"],
  observer: ["radiobserver"],
  partners: ["copartners"],
  pharmacy: ["zoopharmacy", "polypharmacy"],
  property: ["disproperty"],
  research: ["presearch", "bioresearch", "proresearch"],
  security: ["insecurity", "unsecurity", "nonsecurity", "subsecurity", "oversecurity", "countersecurity"],
  services: ["disservices", "foodservices"],
  software: ["microsoftware"],
  training: ["straining", "detraining", "entraining", "distraining", "nontraining", "pretraining", "restraining", "constraining", "overtraining", "overstraining", "unconstraining", "nonconstraining"],
  vacation: ["prevacation"],
  ventures: ["adventures", "misadventures"],
  analytics: ["cryptanalytics", "cryptoanalytics"],
  architect: ["subarchitect", "archarchitect", "protoarchitect"],
  chronicle: ["enchronicle"],
  community: ["discommunity", "procommunity", "subcommunity", "intercommunity"],
  directory: ["subdirectory"],
  education: ["coeducation", "ineducation", "reeducation", "maleducation", "miseducation", "noneducation", "preeducation", "proeducation", "antieducation", "autoeducation", "overeducation", "supereducation", "undereducation"],
  financial: ["unfinancial", "nonfinancial", "prefinancial"],
  furniture: ["disfurniture"],
  institute: ["reinstitute", "superinstitute"],
  insurance: ["coinsurance", "reinsurance", "noninsurance", "preinsurance", "proinsurance", "overinsurance", "interinsurance", "underinsurance"],
  marketing: ["dismarketing", "premarketing"],
  solutions: ["absolutions", "resolutions", "dissolutions"],
  associates: ["disassociates"],
  basketball: ["probasketball"],
  consulting: ["unconsulting"],
  foundation: ["refoundation", "prefoundation", "subfoundation"],
  industries: ["superindustries"],
  management: ["remanagement", "mismanagement", "nonmanagement"],
  protection: ["reprotection", "unprotection", "nonprotection", "overprotection", "radioprotection", "counterprotection"],
  prudential: ["imprudential", "unprudential", "nonprudential", "antiprudential", "jurisprudential"],
  republican: ["irrepublican", "unrepublican", "nonrepublican", "prerepublican", "prorepublican", "antirepublican", "semirepublican", "ultrarepublican", "pseudorepublican"],
  technology: ["biotechnology", "cytotechnology", "terotechnology", "radiotechnology", "psychotechnology", "electrotechnology"],
  university: ["ununiversity", "nonuniversity", "prouniversity", "interuniversity"],
  advertising: ["readvertising", "unadvertising", "preadvertising", "proadvertising"],
  contractors: ["subcontractors"],
  engineering: ["bioengineering", "nonengineering", "preengineering", "chemicoengineering"],
  productions: ["reproductions"],
  progressive: ["improgressive", "unprogressive", "nonprogressive", "antiprogressive", "autoprogressive", "semiprogressive"],
  construction: ["reconstruction", "malconstruction", "misconstruction", "nonconstruction", "preconstruction"],
  international: ["uninternational", "noninternational", "pseudointernational"],
};
