/**
 * word-meanings-extra13.ts — Chinese meanings for new library words
 * Covers words added in extra13 / extra14 / extra15
 */

export const WORD_MEANINGS_EXTRA13: Record<string, string> = {
  // ── .ba words ─────────────────────────────────────────────────────────────
  "samba": "桑巴舞",
  "rumba": "伦巴舞",
  "mamba": "曼巴蛇",
  "tuba": "大号（乐器）",
  "amoeba": "变形虫",
  "scuba": "水肺潜水",

  // ── .be words ─────────────────────────────────────────────────────────────
  "globe": "地球仪",
  "probe": "探测器",
  "scribe": "抄写员",
  "tribe": "部落",
  "vibe": "氛围",
  "cube": "立方体",
  "tube": "管道",
  "robe": "长袍",
  "lobe": "耳垂",
  "bribe": "贿赂",
  "adobe": "土坯砖",
  "wardrobe": "衣橱",
  "microbe": "微生物",
  "strobe": "频闪灯",

  // ── .bi words ─────────────────────────────────────────────────────────────
  "alibi": "不在场证明",
  "rabbi": "拉比（犹太法学家）",

  // ── .bo words ─────────────────────────────────────────────────────────────
  "combo": "组合",
  "mambo": "曼波舞",
  "limbo": "不确定状态",
  "turbo": "涡轮",
  "gazebo": "凉亭",
  "placebo": "安慰剂",
  "jumbo": "超大型",

  // ── .bt words ─────────────────────────────────────────────────────────────
  "debt": "债务",
  "doubt": "疑问",

  // ── .by words ─────────────────────────────────────────────────────────────
  "baby": "婴儿",
  "hobby": "爱好",
  "lobby": "大厅",
  "tabby": "虎斑猫",
  "derby": "德比赛",
  "standby": "备用",
  "lullaby": "摇篮曲",
  "rugby": "橄榄球",
  "nearby": "附近",

  // ── .ca words ─────────────────────────────────────────────────────────────
  "replica": "复制品",
  "circa": "大约（年代）",
  "alpaca": "羊驼",
  "silica": "二氧化硅",
  "basilica": "大教堂",

  // ── .cy words ─────────────────────────────────────────────────────────────
  "policy": "政策",
  "agency": "机构",
  "urgency": "紧急",
  "currency": "货币",
  "privacy": "隐私",
  "accuracy": "准确性",
  "legacy": "遗产",
  "democracy": "民主",
  "efficiency": "效率",
  "emergency": "紧急情况",
  "frequency": "频率",
  "literacy": "识字率",
  "pharmacy": "药房",
  "prophecy": "预言",
  "secrecy": "保密",
  "supremacy": "至高权力",
  "bankruptcy": "破产",
  "conspiracy": "阴谋",
  "diplomacy": "外交",
  "advocacy": "倡导",
  "idiocy": "愚蠢",
  "lunacy": "疯狂",
  "piracy": "海盗行为",
  "fallacy": "谬论",
  "adequacy": "充分性",
  "delicacy": "精致",
  "efficacy": "功效",
  "intimacy": "亲密",
  "aristocracy": "贵族制度",
  "bureaucracy": "官僚主义",
  "theocracy": "神权政治",
  "autocracy": "专制",

  // ── .do words ─────────────────────────────────────────────────────────────
  "avocado": "牛油果",
  "torpedo": "鱼雷",
  "libido": "性欲",
  "condo": "公寓",
  "pseudo": "伪造的",
  "bravado": "虚张声势",
  "crescendo": "渐强",
  "innuendo": "暗语",
  "hairdo": "发型",
  "judo": "柔道",
  "aikido": "合气道",
  "bushido": "武士道",

  // ── .ec words ─────────────────────────────────────────────────────────────
  "spec": "规格",
  "Aztec": "阿兹特克",

  // ── .ee words ─────────────────────────────────────────────────────────────
  "free": "免费",
  "tree": "树",
  "degree": "学位",
  "refugee": "难民",
  "absentee": "缺席者",
  "trainee": "实习生",
  "trustee": "受托人",
  "nominee": "被提名人",
  "invitee": "被邀请人",
  "devotee": "忠实者",
  "goatee": "山羊胡",
  "jamboree": "大型聚会",
  "chimpanzee": "黑猩猩",
  "honeybee": "蜜蜂",
  "bumblebee": "大黄蜂",

  // ── .eg words ─────────────────────────────────────────────────────────────
  "peg": "钉子",
  "leg": "腿",
  "beg": "乞讨",
  "keg": "小桶",
  "nutmeg": "肉豆蔻",
  "bootleg": "非法的",

  // ── .eu words ─────────────────────────────────────────────────────────────
  "lieu": "代替（in lieu of）",
  "milieu": "环境",
  "adieu": "再见（法语）",

  // ── .fi words ─────────────────────────────────────────────────────────────
  "wifi": "无线网络",
  "hifi": "高保真音响",
  "scifi": "科幻",
  "amalfi": "阿马尔菲",

  // ── .ga words ─────────────────────────────────────────────────────────────
  "yoga": "瑜伽",
  "omega": "欧米伽",
  "saga": "传说",
  "toga": "托加袍",
  "manga": "漫画",
  "mega": "超大",
  "raga": "拉格（印度音乐）",

  // ── .ie words ─────────────────────────────────────────────────────────────
  "cookie": "饼干",
  "rookie": "新手",
  "brownie": "布朗尼",
  "zombie": "僵尸",
  "auntie": "阿姨",
  "selfie": "自拍",
  "techie": "技术宅",
  "veggie": "蔬菜",
  "hoodie": "连帽衫",
  "junkie": "瘾君子",
  "newbie": "新手",

  // ── .jo words ─────────────────────────────────────────────────────────────
  "banjo": "班卓琴",
  "mojo": "魔力",
  "dojo": "道场",

  // ── .ky words ─────────────────────────────────────────────────────────────
  "risky": "有风险的",
  "rocky": "崎岖的",
  "lucky": "幸运的",
  "spooky": "鬼怪的",
  "tricky": "棘手的",
  "silky": "丝滑的",
  "bulky": "笨重的",
  "milky": "乳白的",
  "funky": "时髦的",
  "chunky": "粗短的",
  "murky": "阴暗的",
  "quirky": "古怪的",
  "perky": "活泼的",
  "tacky": "俗气的",
  "wacky": "怪异的",
  "husky": "嘶哑的",
  "whisky": "威士忌",
  "Kentucky": "肯塔基",
  "turkey": "火鸡",
  "monkey": "猴子",
  "donkey": "驴",
  "jockey": "骑师",
  "hockey": "曲棍球",

  // ── .mo words ─────────────────────────────────────────────────────────────
  "memo": "备忘录",
  "demo": "演示",
  "sumo": "相扑",
  "cosmo": "宇宙",
  "dynamo": "发电机",
  "alamo": "阿拉莫",
  "palermo": "巴勒莫",
  "primo": "首要的",
  "nemo": "尼莫",

  // ── .mu words ─────────────────────────────────────────────────────────────
  "emu": "鸸鹋",

  // ── .pa words ─────────────────────────────────────────────────────────────
  "spa": "温泉",
  "sherpa": "夏尔巴人",
  "pampa": "潘帕草原",

  // ── .py words ─────────────────────────────────────────────────────────────
  "happy": "快乐的",
  "copy": "复制",
  "puppy": "小狗",
  "nappy": "纸尿裤",
  "zippy": "活泼的",
  "grumpy": "脾气暴躁的",
  "lumpy": "凹凸不平的",
  "bumpy": "颠簸的",
  "choppy": "波浪起伏的",
  "floppy": "松软的",
  "sloppy": "马虎的",
  "crispy": "脆的",
  "gypsy": "吉普赛人",
  "autopsy": "验尸",
  "biopsy": "活检",
  "heresy": "异端",
  "fantasy": "幻想",
  "ecstasy": "极度兴奋",
  "epilepsy": "癫痫",

  // ── .sk words ─────────────────────────────────────────────────────────────
  "disk": "磁盘",
  "mask": "口罩",
  "task": "任务",
  "dusk": "黄昏",
  "musk": "麝香",
  "husk": "外壳",
  "risk": "风险",
  "brisk": "活跃的",
  "flask": "烧瓶",
  "desk": "书桌",
  "tusk": "象牙",
  "whisk": "搅拌器",
  "kiosk": "亭子",
  "asterisk": "星号",

  // ── .ss words ─────────────────────────────────────────────────────────────
  "access": "访问",
  "process": "过程",
  "success": "成功",
  "address": "地址",
  "stress": "压力",
  "press": "按压",
  "class": "类",
  "mass": "质量",
  "cross": "交叉",
  "chess": "国际象棋",
  "dress": "连衣裙",
  "mess": "混乱",
  "excess": "过量",
  "express": "快递",
  "assess": "评估",
  "suppress": "抑制",
  "obsess": "困扰",
  "compass": "指南针",
  "bypass": "绕过",
  "abyss": "深渊",
  "embarrass": "尴尬",

  // ── .sy words ─────────────────────────────────────────────────────────────
  "daisy": "雏菊",
  "easy": "容易的",
  "busy": "忙碌的",
  "noisy": "嘈杂的",
  "classy": "有格调的",
  "bossy": "爱发号施令的",
  "messy": "混乱的",
  "fussy": "挑剔的",
  "glossy": "有光泽的",
  "tipsy": "微醉的",
  "jealousy": "嫉妒",
  "controversy": "争议",
  "ecstasy": "欢喜",
  "embassy": "大使馆",
  "prophecy": "预言",

  // ── .to words ─────────────────────────────────────────────────────────────
  "auto": "汽车",
  "photo": "照片",
  "crypto": "加密货币",
  "proto": "原型",
  "lotto": "乐透",
  "motto": "座右铭",
  "risotto": "意大利烩饭",
  "ghetto": "贫民区",
  "pronto": "迅速地",
  "manifesto": "宣言",
  "incognito": "隐姓埋名",
  "veto": "否决权",
  "mosquito": "蚊子",
  "burrito": "墨西哥卷饼",

  // ── .ua words ─────────────────────────────────────────────────────────────
  "aqua": "水",

  // ── .ug words ─────────────────────────────────────────────────────────────
  "bug": "虫子",
  "drug": "药物",
  "hug": "拥抱",
  "mug": "马克杯",
  "plug": "插头",
  "slug": "蛞蝓",
  "shrug": "耸肩",
  "thug": "暴徒",
  "debug": "调试",

  // ── .um words ─────────────────────────────────────────────────────────────
  "forum": "论坛",
  "album": "专辑",
  "medium": "媒介",
  "maximum": "最大值",
  "minimum": "最小值",
  "quantum": "量子",
  "museum": "博物馆",
  "aquarium": "水族馆",
  "podium": "讲台",
  "stadium": "体育场",
  "calcium": "钙",
  "helium": "氦",
  "sodium": "钠",
  "premium": "溢价",
  "vacuum": "真空",
  "platinum": "铂金",
  "auditorium": "礼堂",
  "curriculum": "课程",
  "millennium": "千年",
  "moratorium": "暂缓",
  "spectrum": "光谱",
  "opium": "鸦片",
  "radium": "镭",
  "uranium": "铀",
  "titanium": "钛",

  // ── .uy words ─────────────────────────────────────────────────────────────
  "buy": "购买",
  "guy": "家伙",

  // ── .va words ─────────────────────────────────────────────────────────────
  "java": "Java语言",
  "lava": "熔岩",
  "larva": "幼虫",
  "saliva": "唾液",
  "nova": "新星",
  "supernova": "超新星",
  "diva": "歌剧女主角",
  "Casanova": "花花公子",
  "Geneva": "日内瓦",

  // ── .ws words ─────────────────────────────────────────────────────────────
  "news": "新闻",
  "views": "观点",
  "laws": "法律",
  "flows": "流动",
  "shows": "节目",
  "claws": "爪子",
  "flaws": "缺陷",
  "straws": "稻草",
  "crews": "船员",
  "brews": "酿造",
  "meadows": "草地",
  "pillows": "枕头",
  "shadows": "阴影",
  "windows": "窗户",
  "arrows": "箭",
  "borrows": "借用",
  "follows": "跟随",
  "sorrows": "悲伤",

  // ── .ye words ─────────────────────────────────────────────────────────────
  "bye": "再见",
  "dye": "染料",
  "eye": "眼睛",
  "rye": "黑麦",
  "lye": "碱液",
  "goodbye": "再见",
  "aye": "是",

  // ── .za words ─────────────────────────────────────────────────────────────
  "pizza": "披萨",
  "plaza": "广场",
  "piazza": "广场（意）",
  "bonanza": "意外之财",
  "stanza": "诗节",
  "extravaganza": "盛大演出",
  "influenza": "流感",
  "organza": "欧根纱",

  // ── gTLD words ────────────────────────────────────────────────────────────
  "alphabet": "字母表",
  "Tibet": "西藏",
  "robot": "机器人",
  "chatbot": "聊天机器人",
  "nanobot": "纳米机器人",
  "sandbox": "沙盒",
  "mailbox": "邮箱",
  "toolbox": "工具箱",
  "inbox": "收件箱",
  "outbox": "发件箱",
  "gearbox": "变速箱",
  "jukebox": "自动点唱机",
  "beatbox": "节奏盒",
  "medical": "医疗的",
  "local": "本地的",
  "vocal": "声乐的",
  "logical": "合乎逻辑的",
  "ethical": "道德的",
  "typical": "典型的",
  "tropical": "热带的",
  "musical": "音乐的",
  "radical": "激进的",
  "physical": "物理的",
  "critical": "批判的",
  "magical": "神奇的",
  "practical": "实践的",
  "political": "政治的",
  "technical": "技术的",
  "vertical": "垂直的",
  "chemical": "化学的",
  "optical": "光学的",
  "surgical": "外科的",
  "comical": "滑稽的",
  "nautical": "航海的",
  "analytical": "分析的",
  "numerical": "数字的",
  "reciprocal": "互惠的",
  "fiscal": "财政的",
  "pascal": "帕斯卡",
  "webcam": "网络摄像头",
  "bodycam": "随身摄像机",
  "dashcam": "行车记录仪",
  "racecar": "赛车",
  "sidecar": "侧车",
  "Baghdad": "巴格达",
  "Trinidad": "特立尼达",
  "Monday": "星期一",
  "Tuesday": "星期二",
  "Wednesday": "星期三",
  "Thursday": "星期四",
  "Friday": "星期五",
  "Saturday": "星期六",
  "Sunday": "星期日",
  "birthday": "生日",
  "holiday": "假期",
  "today": "今天",
  "payday": "发薪日",
  "polkadot": "波尔卡圆点",
  "heat": "热",
  "meat": "肉",
  "beat": "节拍",
  "treat": "款待",
  "wheat": "小麦",
  "defeat": "打败",
  "repeat": "重复",
  "nucleus": "细胞核",
  "firefly": "萤火虫",
  "butterfly": "蝴蝶",
  "dragonfly": "蜻蜓",
  "mayfly": "蜉蝣",
  "Portugal": "葡萄牙",
  "frugal": "节俭的",
  "regal": "王室的",
  "illegal": "非法的",
  "Senegal": "塞内加尔",
  "zinc": "锌",
  "enjoy": "享受",
  "killjoy": "煞风景的人",
  "outlaw": "罪犯",
  "bylaw": "附则",
  "woman": "女人",
  "human": "人类",
  "shaman": "萨满",
  "roadmap": "路线图",
  "sitemap": "站点地图",
  "heatmap": "热力图",
  "bitmap": "位图",
  "mindmap": "思维导图",
  "abdomen": "腹部",
  "acumen": "洞察力",
  "specimen": "标本",
  "omen": "预兆",
  "know": "知道",
  "snow": "雪",
  "phone": "电话",
  "zone": "区域",
  "bone": "骨头",
  "stone": "石头",
  "throne": "宝座",
  "clone": "克隆",
  "drone": "无人机",
  "cyclone": "飓风",
  "hormone": "激素",
  "milestone": "里程碑",
  "microphone": "麦克风",
  "saxophone": "萨克斯管",
  "telephone": "电话",
  "headphone": "耳机",
  "backbone": "脊梁",
  "ozone": "臭氧层",
  "repay": "偿还",
  "prepay": "预付",
  "overpay": "多付",
  "carpet": "地毯",
  "puppet": "傀儡",
  "trumpet": "小号",
  "hundred": "百",
  "hatred": "仇恨",
  "kindred": "亲属",
  "sacred": "神圣的",
  "syntax": "语法",
  "hotel": "酒店",
  "motel": "汽车旅馆",
  "hostel": "青年旅舍",
  "pastel": "蜡笔",
  "cartel": "卡特尔",
  "laptop": "笔记本电脑",
  "rooftop": "屋顶",
  "nonstop": "不间断的",
  "hilltop": "山顶",
  "desktop": "桌面",
  "Darwin": "达尔文",
  "Edwin": "埃德温",
  "husband": "丈夫",
  "headband": "头带",
  "broadband": "宽带",
  "contraband": "违禁品",
  "motorbike": "摩托车",
  "vagabond": "流浪汉",
  "textbook": "教科书",
  "notebook": "笔记本",
  "handbook": "手册",
  "cookbook": "食谱",
  "guidebook": "指南",
  "yearbook": "年鉴",
  "storybook": "故事书",
  "scrapbook": "剪贴簿",
  "electricity": "电力",
  "publicity": "公众知名度",
  "capacity": "容量",
  "ferocity": "凶猛",
  "simplicity": "简单",
  "audacity": "大胆",
  "velocity": "速度",
  "tenacity": "韧性",
  "complicity": "同谋",
  "authenticity": "真实性",
  "ethnicity": "民族",
  "barcode": "条形码",
  "postcode": "邮政编码",
  "passcode": "密码",
  "ordeal": "磨难",
  "campfire": "篝火",
  "crossfire": "交叉火力",
  "wildfire": "野火",
  "backfire": "适得其反",
  "ceasefire": "停火",
  "blowfish": "河豚",
  "starfish": "海星",
  "swordfish": "剑鱼",
  "catfish": "鲶鱼",
  "goldfish": "金鱼",
  "jellyfish": "水母",
  "selfish": "自私的",
  "seafood": "海鲜",
  "carefree": "无忧无虑",
  "refund": "退款",
  "endgame": "残局",
  "navigate": "导航",
  "investigate": "调查",
  "propagate": "传播",
  "forgive": "原谅",
  "marigold": "万寿菊",
  "bauhaus": "包豪斯",
  "Iceland": "冰岛",
  "Finland": "芬兰",
  "Ireland": "爱尔兰",
  "Scotland": "苏格兰",
  "England": "英格兰",
  "island": "岛屿",
  "mainland": "大陆",
  "homeland": "故乡",
  "Greenland": "格陵兰",
  "Disneyland": "迪士尼乐园",
  "wildlife": "野生动物",
  "nightlife": "夜生活",
  "afterlife": "来世",
  "hyperlink": "超链接",
  "backlink": "反向链接",
  "alive": "活着的",
  "glove": "手套",
  "email": "电子邮件",
  "airmail": "航空邮件",
  "voicemail": "语音信箱",
  "small": "小的",
  "hallmark": "标志",
  "trademark": "商标",
  "Denmark": "丹麦",
  "watermark": "水印",
  "bookmark": "书签",
  "benchmark": "基准",
  "earmark": "专款专用",
  "undermine": "破坏",
  "examine": "检查",
  "determine": "决定",
  "peppermint": "薄荷",
  "spearmint": "留兰香",
  "keynote": "主旨",
  "banknote": "纸币",
  "footnote": "脚注",
  "homepage": "主页",
  "webpage": "网页",
  "spark": "火花",
  "warpath": "征战之路",
  "footpath": "人行道",
  "display": "展示",
  "interplay": "相互作用",
  "replay": "回放",
  "foreplay": "前奏",
  "gameplay": "游戏玩法",
  "unplug": "拔掉插头",
  "surplus": "剩余",
  "outpost": "前哨",
  "signpost": "路标",
  "goalpost": "球门柱",
  "lamppost": "路灯柱",
  "grace": "优雅",
  "brace": "支架",
  "trace": "痕迹",
  "embrace": "拥抱",
  "terrace": "露台",
  "spread": "传播",
  "thread": "线程",
  "parent": "父母",
  "transparent": "透明的",
  "forest": "森林",
  "interest": "兴趣",
  "arrest": "逮捕",
  "ostrich": "鸵鸟",
  "override": "覆盖",
  "joyride": "兜风",
  "bride": "新娘",
  "pride": "骄傲",
  "spring": "春天",
  "string": "字符串",
  "earring": "耳环",
  "offering": "供品",
  "shamrock": "三叶草",
  "bedrock": "基础",
  "casserole": "砂锅",
  "parole": "假释",
  "bedroom": "卧室",
  "classroom": "教室",
  "bathroom": "浴室",
  "showroom": "展厅",
  "mushroom": "蘑菇",
  "boardroom": "董事会室",
  "courtroom": "法庭",
  "darkroom": "暗室",
  "newsroom": "新闻室",
  "failsafe": "故障安全",
  "wholesale": "批发",
  "resale": "转售",
  "website": "网站",
  "parasite": "寄生虫",
  "birdsong": "鸟鸣",
  "superstar": "超级明星",
  "nonstop": "不停歇的",
  "doorstop": "门挡",
  "windsurf": "风帆冲浪",
  "smalltalk": "闲聊",
  "hightech": "高科技",
  "nanotech": "纳米技术",
  "biotech": "生物技术",
  "fintech": "金融科技",
  "detour": "绕道",
  "downtown": "市区",
  "uptown": "上城区",
  "Chinatown": "唐人街",
  "YouTube": "油管",
  "fortune": "财富",
  "Neptune": "海王星",
  "velvet": "丝绒",
  "interview": "采访",
  "review": "审查",
  "overview": "概述",
  "preview": "预览",
  "devote": "投身于",
  "microwave": "微波炉",
  "airwave": "广播",
  "network": "网络",
  "framework": "框架",
  "teamwork": "团队协作",
  "homework": "家庭作业",
  "artwork": "艺术作品",
  "clockwork": "钟表机构",
  "paperwork": "文书工作",
  "fieldwork": "实地工作",
  "overwork": "超负荷工作",
  "timezone": "时区",
  "dropzone": "降落区",
  "warzone": "战区",
};
