// Word library batch 7 — curated words for new E-Z gTLDs
// Each key is a TLD without dot; values are words that END in those letters
// Meanings map covers domain/word → Chinese description

export const WORD_LIBRARY_EXTRA7: Record<string, string[]> = {

  // ── .site ────────────────────────────────────────────────────────────────
  site: ["campsite","website","composite","opposite","parasite","offsite",
         "onsite","worksite","jobsite","moonsite","microsite","daysite",
         "townsite","homesite","buildsite","mediasite","socialsite"],

  // ── .life ────────────────────────────────────────────────────────────────
  life: ["wildlife","nightlife","afterlife","midlife","halflife","streetlife",
         "highlife","lowlife","citylife","worklife","homelife","farmlife",
         "dreamlife","goodlife","nextlife","ecolife","lovelife","starlife"],

  // ── .zone ────────────────────────────────────────────────────────────────
  zone: ["ozone","rezone","endzone","timezone","dropzone","warzone","killzone",
         "deadzone","safezone","netzone","webzone","datazone","techzone",
         "ecozone","firezone","darkzone","coolzone","freezone","eurozone"],

  // ── .show ────────────────────────────────────────────────────────────────
  show: ["airshow","gameshow","roadshow","sideshow","slideshow","talkshow",
         "peepshow","floorshow","lightshow","motorshow","autoshow","webshow",
         "netshow","openshow","liveshow","techshow","cabshow"],

  // ── .game ────────────────────────────────────────────────────────────────
  game: ["endgame","pregame","ballgame","wargame","boardgame","minigame",
         "videogame","wordgame","mindgame","fairgame","freegame","netgame",
         "webgame","opengame","arcadegame","tabletopgame"],

  // ── .star ────────────────────────────────────────────────────────────────
  star: ["rockstar","popstar","superstar","allstar","megastar","lodestar",
         "northstar","daystar","moonstar","sunstar","filmstar","moviestar",
         "webstar","goldstar","darkstar","coldstar","hotstar","topstar",
         "openstar","ultrastar"],

  // ── .house ───────────────────────────────────────────────────────────────
  house: ["penthouse","alehouse","icehouse","farmhouse","storehouse",
          "greenhouse","treehouse","jailhouse","firehouse","gatehouse",
          "boathouse","warehouse","clubhouse","courthouse","outhouse",
          "powerhouse","steakhouse","coffeehouse","roadhouse","cookhouse",
          "smokehouse","schoolhouse","workhouse","chophouse","playhouse",
          "glasshouse","summerhouse","safehouse","clearinghouse"],

  // ── .fish ────────────────────────────────────────────────────────────────
  fish: ["starfish","swordfish","blowfish","jellyfish","catfish","goldfish",
         "pufferfish","cuttlefish","oafish","selfish","devilfish","lionfish",
         "clownfish","crawfish","crayfish","sunfish","monkfish","roughfish",
         "bonefish","hagfish","dogfish","batfish","garfish","rockfish",
         "flatfish","cowfish","frogfish","drumfish","needlefish","glassfish"],

  // ── .man ─────────────────────────────────────────────────────────────────
  man: ["human","doorman","mailman","milkman","fireman","airman","batman",
        "hitman","lawman","horseman","chairman","salesman","spokesman",
        "craftsman","marksman","statesman","businessman","gentleman",
        "handyman","middleman","cameraman","policeman","congressman",
        "ombudsman","strongman","frontman","clergyman","tradesman",
        "sportsman","nobleman","snowman","sandman","ironman","superman",
        "taxman","foreman","workman","pitman","tugman","postman","batman",
        "batman","iceman","ragman","flagman","boatman","bondsman",
        "watchman","landsman","yachtsman","rifleman","talisman","sherman",
        "truman","roman","german","packman","spiderman"],

  // ── .men ─────────────────────────────────────────────────────────────────
  men: ["women","firemen","horsemen","swordsmen","craftsmen","airmen",
        "foremen","spokesmen","statesmen","businessmen","gentlemen","acumen",
        "abdomen","semen","specimen","hymen","omen","ramen","lumen","amen",
        "horsemen","guardsmen","marksmen","kinsmen","oarsmen","riflemen",
        "bondsmen","tradesmen","sportsmen","noblemen","barmen","firemen"],

  // ── .love ────────────────────────────────────────────────────────────────
  love: ["glove","clove","trove","cove","grove","stove","dove","wove",
         "foxglove","earlylove","selflove","truelove","onelove","landlove",
         "skylove","freelove","purelove"],

  // ── .gold ────────────────────────────────────────────────────────────────
  gold: ["marigold","leopold","mangold","manifold","stronghold","threshold",
         "household","behold","blindfold","handhold","foothold","stranglehold",
         "toehold","uphold","withhold","twofold","threefold","tenfold"],

  // ── .sky ─────────────────────────────────────────────────────────────────
  sky: ["whisky","risky","frisky","husky","dusky","musky","pesky","alaska",
        "nebraska","whiskey"],

  // ── .song ────────────────────────────────────────────────────────────────
  song: ["birdsong","lovesong","folksong","swansong","evensong","plainsong",
         "worksong","warsong","herosong","battlesong","themesong","oldsong",
         "goldsong"],

  // ── .work ────────────────────────────────────────────────────────────────
  work: ["teamwork","network","framework","homework","artwork","metalwork",
         "paperwork","patchwork","woodwork","fieldwork","clockwork","footwork",
         "groundwork","guesswork","hardwork","headwork","legwork","needlework",
         "piecework","stonework","lacework","wirework","ironwork","brickwork",
         "craftwork","glasswork","handwork","latticework","leatherwork",
         "openwork","overwork","plasterwork","roadwork","scrollwork",
         "underwork","gridwork","lifework","rework","firework","fretwork",
         "casework","coursework","deskwork","earthwork","facework","flatwork",
         "bodywork","bookwork","brainwork","bridgework","busywork","chainwork"],

  // ── .market ──────────────────────────────────────────────────────────────
  market: ["supermarket","hypermarket","stockmarket","freemarket","openmarket",
           "webmarket","fleamarket","darkmarket","blackmarket","freshmarket",
           "farmmarket","netmarket","techmarket","smartmarket","euromarket",
           "globalmarket","cybermarket"],

  // ── .social ──────────────────────────────────────────────────────────────
  social: ["antisocial","psychosocial","unsocial","presocial","parasocial",
           "biosocial","hypersocial","supersocial","ecosocial","geosocial",
           "techsocial","metasocial"],

  // ── .style ───────────────────────────────────────────────────────────────
  style: ["lifestyle","freestyle","hairstyle","oldstyle","newstyle",
          "streetstyle","homestyle","farmstyle","retrostyle","cyberstyle",
          "urbanstyle","darkstyle","rockstyle","techstyle","webstyle",
          "minimalstyle","classicstyle"],

  // ── .trade ───────────────────────────────────────────────────────────────
  trade: ["fairtrade","freetrade","overtrade","ecotrade","globaltrade",
          "webtrade","opentrade","megatrade","agritrade","techtrade",
          "nettrade","freetrade","softtrade","hardtrade"],

  // ── .legal ───────────────────────────────────────────────────────────────
  legal: ["illegal","paralegal","extralegal","superlegal","nonlegal",
          "cyberlegal","techlegal","medlegal","biolegal","ecolegal",
          "infralegal","sublegal"],

  // ── .sport ───────────────────────────────────────────────────────────────
  sport: ["motorsport","watersport","esport","teamsport","airsport",
          "netsport","cybersport","supersport","parasport","multisport",
          "ecosport","techsport","urbansport","supersport"],

  // ── .care ────────────────────────────────────────────────────────────────
  care: ["healthcare","skincare","daycare","childcare","haircare","selfcare",
         "medicare","eldercare","eyecare","aftercare","homecare","petcare",
         "dentalcare","mentalcare","netcare","telecare","ecocare","bodycare",
         "babycare","techcare","ultracare","lifecare","carcare","vetcare",
         "fostercare","urgentcare","primarycare","starcare","socialcare"],

  // ── .link ────────────────────────────────────────────────────────────────
  link: ["hyperlink","deeplink","crosslink","shortlink","interlink","hotlink",
         "weblink","netlink","airlink","earthlink","openlink","freelink",
         "smartlink","infolink","darklink","starlink","skylink","microlink"],

  // ── .tech ────────────────────────────────────────────────────────────────
  tech: ["edtech","fintech","biotech","cleantech","medtech","proptech",
         "legaltech","insurtech","adtech","regtech","agritech","govtech",
         "hrtech","martech","climatetech","deeptech","nanotech","greentech",
         "infotech","hightech","logitech","healthtech","foodtech","autotech",
         "ecotech","geotech","spacetech","energytech","safetech","smarttech",
         "cybertech","opentech","ultratech","supertech","megatech","teletech",
         "microtech"],

  // ── .red ─────────────────────────────────────────────────────────────────
  red: ["infrared","hatred","hundred","kindred","sacred","anchored","powered",
        "covered","delivered","recovered","gathered","scattered","rendered",
        "offered","ordered","wondered","sheltered","thundered","remembered",
        "mothered","fathered","bothered"],

  // ── .run ─────────────────────────────────────────────────────────────────
  run: ["outrun","rerun","homerun","dryrun","shortrun","longrun","endrun",
        "sunrun","freshrun","freerun","fastrun","webrun","netrun","skyrun",
        "starrun","ultrarun","nightrun","crossrun","prorun"],

  // ── .win ─────────────────────────────────────────────────────────────────
  win: ["darwin","irwin","erwin","alvin","calvin","kevin","marvin","devin",
        "gavin","kelvin","melvin","sherwin","goodwin","corwin","unwin",
        "oswin","baldwin","lewin","pengwin","godwin"],

  // ── .tax ─────────────────────────────────────────────────────────────────
  tax: ["syntax","pretax","posttax","aftertax","retax","overtax","nontax",
        "subtax"],

  // ── .fan ─────────────────────────────────────────────────────────────────
  fan: ["stefan","caravan","artisan","partisan","christian","american","trojan",
        "sedan","titan","alan","julian","ocean","orphan","urban","tarzan",
        "slogan","wuhan","milan","yuan","rican","toucan","pelican","guardian"],

  // ── .fun ─────────────────────────────────────────────────────────────────
  fun: ["sunfun","webfun","netfun","freefun","openfun","darkfun","superfun",
        "ultrafun","maxfun","megafun","playfun","gayfun","coolfun"],

  // ── .film ────────────────────────────────────────────────────────────────
  film: ["shortfilm","microfilm","megafilm","darkfilm","slowfilm","webfilm",
         "netfilm","openfilm","ultrafilm","cyberfilm","techfilm","quickfilm"],

  // ── .farm ────────────────────────────────────────────────────────────────
  farm: ["datafarm","cloudfarm","webfarm","netfarm","serverfarm","solarpanel",
         "windfarm","algaefarm","seafarm","treefarm","organicfarm","techfarm",
         "robofarm","smartfarm","openfarm","ecomfarm","darkfarm","megafarm"],

  // ── .food ────────────────────────────────────────────────────────────────
  food: ["seafood","fastfood","slowfood","rawfood","realfood","superfood",
         "petfood","babyood","dogfood","catfood","healthfood","streetfood",
         "webfood","techfood","darkfood","openbox","prepfood","farmfood"],

  // ── .gold (brand) ─────────────────────────────────────────────────────────
  // .pub ────────────────────────────────────────────────────────────────────
  pub: ["micropub","nightpub","webpub","epub","digipub","cyberpub","openbar",
        "darkpub","hotpub","techpub","ultrapub","megapub","freepub"],

  // ── .yoga ────────────────────────────────────────────────────────────────
  yoga: ["hathayoga","bikramyoga","hotryoga","kundaliniyoga","vinyasayoga",
         "poweryoga","ashtangayoga","inyoga","doyoga","tryyoga","openyoga",
         "newyoga","goodyoga","darkoga","techyoga","flyyoga","airyoga"],

  // ── .news ────────────────────────────────────────────────────────────────
  news: ["goodnews","badnews","newnews","hotews","latenews","livenews",
         "realnews","technews","webnews","netnews","opennews","dailynews",
         "localnews","worldnews","fastews","truenews","smartnews","darknews"],

  // ── .map ─────────────────────────────────────────────────────────────────
  map: ["roadmap","sitemap","heatmap","mindmap","bitmap","basemap","skymap",
        "starmap","worldmap","geomap","datamap","treemap","cloudmap","netmap",
        "openmap","smartmap","brainmap","techmap","lifemap","citymap",
        "riskmap","warmap","dreammap","lovemap","airmap"],

  // ── .bar ─────────────────────────────────────────────────────────────────
  bar: ["sidebar","toolbar","taskbar","scrollbar","menubar","statusbar",
        "titlebar","handlebar","crossbar","crowbar","rebar","minibar",
        "megabar","superbar","webbar","cyberbar","techbar","metabar",
        "searchbar","launchbar","darkbar","sportsbar","smartbar"],

  // ── .red / .net / .org overlaps ──────────────────────────────────────────
  // .ink ────────────────────────────────────────────────────────────────────
  ink: ["think","drink","link","wink","rethink","hyperlink","interlink",
        "crosslink","deeplink","shortlink","hotlink","unthink","groupthink",
        "freethink","hardlink","backlink","permalink","sidelink","tracklink",
        "primelink","bioink","nanoink","smartink","techink","netink",
        "overthink","doublethink","brink","blink","shrink","stink","kink",
        "pink","sink","zinc","rethink","outthink","overthink"],

  // ── .fit ─────────────────────────────────────────────────────────────────
  fit: ["outfit","benefit","profit","misfit","retrofit","legit","summit",
        "permit","admit","commit","submit","transmit","emit","omit","acquit",
        "drawfit","goodfit","hotfit","techfit","netfit","comfit","forfeit",
        "counterfeit","befit","unfit","overfit","sportfit","lifefit","bodyfit"],

  // ── .fund ────────────────────────────────────────────────────────────────
  fund: ["refund","endowfund","trustfund","hedgefund","mutualfund","seedfund",
         "webfund","netfund","openfund","darkfund","techfund","econfund",
         "greenfund","startupfund","vcfund","altfund","crowdfund"],

  // ── .art ─────────────────────────────────────────────────────────────────
  art: ["heart","start","smart","cart","dart","part","tart","mart","restart",
        "counterpart","depart","apart","impart","upstart","kickstart","walmart",
        "flipchart","multipart","sweetheart","braveheart","lionheart","oxcart",
        "rampart","stockmart","bookmark","streetart","modernart","folkart",
        "popart","bodyart","fineart","darkart","pixelart","cryptoart","nftart",
        "webart","netart","flashart","tattooart","urbanart","photoart","fanart",
        "gamestart","lifestart","flowchart","pie-chart","barchart","gantt",
        "pie","flowchart"],

  // ── .pet ─────────────────────────────────────────────────────────────────
  pet: ["carpet","trumpet","puppet","target","planet","muppet","blanket",
        "basket","bracket","racket","ticket","pocket","socket","rocket",
        "bucket","tablet","basket","closet","buffet","inlet","outlet",
        "eyelet","helmet","velvet","wallet","mallet","violet","banquet",
        "bouquet","croquet","cornet","clarinet","cabinet","rivet","gadget",
        "magnet","sonnet","bayonet","garnet","bonnet","crumpet","trumpet",
        "internet","dragnet","fishnet","hairnet","coronet","bayonet"],

  // ── .red (more) ───────────────────────────────────────────────────────────
  // .gold (TLD just needs marigold) already covered

  // ── .one ─────────────────────────────────────────────────────────────────
  one: ["phone","zone","bone","tone","stone","alone","clone","cone","drone",
        "hone","prone","throne","milestone","cornerstone","limestone","keystone",
        "earphone","microphone","saxophone","trombone","hormone","chromosome",
        "cyclone","ozone","everyone","someone","anyone","backbone","jawbone",
        "wishbone","headphone","smartphone","ringtone","monotone","overtone",
        "undertone","capstone","sandstone","cobblestone","brownstone","gemstone",
        "touchstone","gravestone","shinbone","balcone","prozone","iphone",
        "handphone","megaphone","xylophone","homophone","interphone",
        "videophone","speakerphone","payphone","cellphone","dumbphone"],

  // ── .win more ─────────────────────────────────────────────────────────────
  // .top ────────────────────────────────────────────────────────────────────
  top: ["rooftop","desktop","laptop","tabletop","mountaintop","countertop",
        "skintop","overtop","treetop","hilltop","nonstop","airdrop","raindrop",
        "backdrop","workshop","teardrop","raindrop","waterdrop","bookshop",
        "coffeeshop","workshop","webshop","netshop","openshop","smartshop",
        "topnotch","hardtop","softtop","flattop","spintop"],

  // ── .pro ─────────────────────────────────────────────────────────────────
  pro: ["maestro","metro","retro","intro","nitro","micro","gastro","hydro",
        "gyro","pyro","afro","zero","hero","nero","superhero","antihero",
        "macro","sacro","fibro","vibro","electro","neutro","astro","castro",
        "maestro","bilbao","sandro","sandro","theatro","centro"],

  // ── .io (more) ────────────────────────────────────────────────────────────
  io: ["radio","studio","audio","patio","ratio","trio","scenario","portfolio",
       "folio","mario","pistachio","oratorio","impresario","ontario","cameo",
       "romeo","video","stereo","tattoo","bamboo","taboo","voodoo","shampoo",
       "igloo","tomato","potato","burrito","risotto","falsetto","stiletto",
       "libretto","spaghetti","amaretto","cornetto","ghetto","grotto","lotto",
       "motto","mosquito","bandito","incognito","vibrato","staccato","manifesto",
       "concerto","allegretto","pizzicato"],

  // ── .me (more) ────────────────────────────────────────────────────────────
  me: ["home","name","game","fame","time","rhyme","theme","scheme","extreme",
       "supreme","welcome","awesome","become","outcome","handsome","syndrome",
       "genome","chrome","dome","costume","resume","perfume","volume","consume",
       "assume","presume","income","overcome","username","nickname","surname",
       "hostname","fullname","frame","blame","flame","claim","tame","same",
       "shame","overtime","sometime","halftime","wartime","peacetime","bedtime",
       "daytime","nighttime","lifetime","longtime","pastime","springtime",
       "summertime","wintertime","anytime","lunchtime","overtime","prime",
       "crime","climb","dime","lime","mime","slime","sublime","rename","codename",
       "tradename"],

  // ── .us (more) ───────────────────────────────────────────────────────────
  us: ["bonus","campus","focus","nexus","virus","status","circus","minus",
       "census","genius","famous","various","previous","curious","glorious",
       "obvious","serious","numerous","nervous","dangerous","generous",
       "enormous","vigorous","notorious","prosperous","adventurous","ambitious",
       "outrageous","gorgeous","glamorous","humorous","fabulous","marvelous",
       "wondrous","zealous","jealous","luminous","unanimous","spontaneous",
       "apparatus","stratus","impetus","prospectus","syllabus","omnibus",
       "cactus","octopus","platypus","exodus","radius","sinus","ruckus",
       "caucus","lexus","versus","consensus","nimbus","cumulus","stimulus",
       "calculus","modulus","animus","corpus","locus","murderous","monstrous",
       "hazardous","ridiculous","miraculous","tremendous","stupendous",
       "victorious","glorious","harmonious","erroneous","aquarius","taurus",
       "scorpius","sagittarius"],
};

export const WORD_MEANINGS_EXTRA7: Record<string, string> = {
  // .site
  "camp.site": "营地域名",
  "web.site": "网站",
  "compo.site": "综合网站",
  "oppo.site": "对立面",
  "para.site": "寄生/创意域名",
  "off.site": "场外/线下",
  "on.site": "现场/在线",
  "work.site": "工作场地",
  // .life
  "wild.life": "野生动物",
  "night.life": "夜生活",
  "after.life": "来世",
  "mid.life": "中年",
  "half.life": "半衰期",
  "street.life": "街头文化",
  "high.life": "奢华生活",
  "low.life": "底层/社会边缘",
  "eco.life": "生态生活",
  "dream.life": "梦想生活",
  // .zone
  "o.zone": "臭氧层",
  "re.zone": "重新分区",
  "end.zone": "终区",
  "time.zone": "时区",
  "drop.zone": "降落区",
  "war.zone": "战区",
  "safe.zone": "安全区",
  "free.zone": "自由区",
  "euro.zone": "欧元区",
  "dark.zone": "暗区",
  // .show
  "air.show": "航展",
  "game.show": "游戏节目",
  "road.show": "路演",
  "side.show": "附场表演",
  "slide.show": "幻灯展示",
  "talk.show": "脱口秀",
  "live.show": "现场直播",
  // .game
  "end.game": "终局",
  "pre.game": "赛前",
  "ball.game": "球赛",
  "war.game": "战争游戏",
  "board.game": "桌游",
  "mini.game": "小游戏",
  "word.game": "文字游戏",
  "mind.game": "心理博弈",
  "free.game": "免费游戏",
  "video.game": "电子游戏",
  // .star
  "rock.star": "摇滚明星",
  "pop.star": "流行歌手",
  "super.star": "超级明星",
  "all.star": "全明星",
  "mega.star": "巨星",
  "north.star": "北极星",
  "day.star": "启明星",
  "gold.star": "金星/优秀标志",
  "film.star": "影星",
  "movie.star": "电影明星",
  "top.star": "顶级明星",
  "dark.star": "暗星",
  // .house
  "pent.house": "顶层豪宅",
  "green.house": "温室",
  "ware.house": "仓库",
  "power.house": "动力中心",
  "tree.house": "树屋",
  "fire.house": "消防站",
  "club.house": "会所",
  "farm.house": "农舍",
  "store.house": "储藏室",
  "steak.house": "牛排餐厅",
  "coffee.house": "咖啡馆",
  "safe.house": "安全屋",
  // .fish
  "star.fish": "海星",
  "sword.fish": "旗鱼",
  "blow.fish": "河豚",
  "jelly.fish": "水母",
  "cat.fish": "鲶鱼",
  "gold.fish": "金鱼",
  "sel.fish": "自私",
  "clown.fish": "小丑鱼",
  "sun.fish": "翻车鱼",
  "dog.fish": "角鲨",
  "lion.fish": "狮子鱼",
  "cray.fish": "小龙虾",
  // .man
  "hu.man": "人类",
  "wo.man": "女人",
  "door.man": "门卫",
  "fire.man": "消防员",
  "air.man": "飞行员",
  "batman": "蝙蝠侠",
  "chair.man": "主席",
  "sales.man": "销售员",
  "spokes.man": "发言人",
  "crafts.man": "工匠",
  "states.man": "政治家",
  "business.man": "商人",
  "gentle.man": "绅士",
  "handy.man": "万能工",
  "middle.man": "中间人",
  "snow.man": "雪人",
  "sand.man": "睡魔",
  "iron.man": "钢铁侠",
  "super.man": "超人",
  "spider.man": "蜘蛛侠",
  "tax.man": "税务员",
  "fore.man": "工头",
  "marks.man": "神枪手",
  "watch.man": "守卫",
  // .men
  "wo.men": "女人们",
  "acumen": "洞察力",
  "abdo.men": "腹部",
  "spe.cimen": "标本",
  "o.men": "预兆",
  // .love
  "g.love": "手套",
  "c.love": "丁香",
  "self.love": "自爱",
  "one.love": "同一个爱",
  "sky.love": "天空之爱",
  "free.love": "自由恋爱",
  // .gold
  "mari.gold": "万寿菊",
  "thres.hold": "门槛",
  "house.hold": "家庭户",
  "strong.hold": "要塞",
  "be.hold": "注视",
  "with.hold": "扣留",
  // .sky
  "whi.sky": "威士忌",
  "ri.sky": "有风险",
  "fri.sky": "活泼的",
  "hu.sky": "哈士奇",
  "du.sky": "暗淡的",
  "mu.sky": "麝香的",
  "pe.sky": "讨厌的",
  // .song
  "bird.song": "鸟鸣声",
  "love.song": "情歌",
  "folk.song": "民谣",
  "swan.song": "绝唱",
  "even.song": "晚祷",
  "plain.song": "素歌",
  "battle.song": "战歌",
  "theme.song": "主题曲",
  // .work
  "team.work": "团队合作",
  "net.work": "网络",
  "frame.work": "框架",
  "home.work": "家庭作业",
  "art.work": "艺术作品",
  "field.work": "实地考察",
  "paper.work": "文书工作",
  "ground.work": "基础工作",
  "clock.work": "精密机构",
  "foot.work": "步法",
  "life.work": "毕生事业",
  "fire.work": "烟花",
  "body.work": "车身",
  "case.work": "案件工作",
  "over.work": "过度劳累",
  "book.work": "文案工作",
  "brain.work": "脑力工作",
  // .market
  "super.market": "超市",
  "hyper.market": "大型超市",
  "stock.market": "股市",
  "free.market": "自由市场",
  "black.market": "黑市",
  "fresh.market": "生鲜市场",
  "farm.market": "农贸市场",
  "flea.market": "跳蚤市场",
  // .social
  "anti.social": "反社会",
  "psycho.social": "心理社会",
  "bio.social": "生物社会",
  "geo.social": "地理社交",
  "eco.social": "生态社会",
  // .style
  "life.style": "生活方式",
  "free.style": "自由式",
  "hair.style": "发型",
  "street.style": "街头风格",
  "home.style": "家居风格",
  "retro.style": "复古风格",
  "urban.style": "都市风格",
  "cyber.style": "赛博风格",
  // .trade
  "fair.trade": "公平贸易",
  "free.trade": "自由贸易",
  "eco.trade": "环保贸易",
  "global.trade": "全球贸易",
  // .legal
  "il.legal": "非法的",
  "para.legal": "法律助理",
  "extra.legal": "法外的",
  "cyber.legal": "网络法律",
  // .sport
  "motor.sport": "赛车运动",
  "water.sport": "水上运动",
  "e.sport": "电竞",
  "team.sport": "团队运动",
  "air.sport": "空中运动",
  "cyber.sport": "电子竞技",
  "para.sport": "残疾人运动",
  "multi.sport": "综合运动",
  // .care
  "health.care": "医疗保健",
  "skin.care": "护肤",
  "day.care": "日托",
  "child.care": "儿童保育",
  "hair.care": "护发",
  "self.care": "自我保养",
  "medi.care": "医保",
  "elder.care": "养老护理",
  "eye.care": "护眼",
  "after.care": "售后关怀",
  "home.care": "居家护理",
  "pet.care": "宠物护理",
  "dental.care": "牙科护理",
  "mental.care": "心理健康",
  "baby.care": "婴儿护理",
  "body.care": "身体护理",
  // .link
  "hyper.link": "超链接",
  "deep.link": "深层链接",
  "cross.link": "交叉链接",
  "short.link": "短链接",
  "inter.link": "互联",
  "hot.link": "热链接",
  "web.link": "网页链接",
  "star.link": "星链",
  "sky.link": "天空链路",
  "smart.link": "智能链接",
  "back.link": "反向链接",
  "nano.link": "纳米链接",
  // .tech
  "ed.tech": "教育科技",
  "fin.tech": "金融科技",
  "bio.tech": "生物技术",
  "clean.tech": "清洁技术",
  "med.tech": "医疗技术",
  "prop.tech": "房产科技",
  "legal.tech": "法律科技",
  "insur.tech": "保险科技",
  "ad.tech": "广告技术",
  "reg.tech": "监管科技",
  "agri.tech": "农业科技",
  "gov.tech": "政务科技",
  "climate.tech": "气候科技",
  "deep.tech": "深科技",
  "nano.tech": "纳米技术",
  "green.tech": "绿色技术",
  "high.tech": "高科技",
  "info.tech": "信息技术",
  "health.tech": "健康科技",
  "food.tech": "食品科技",
  "space.tech": "航天科技",
  "energy.tech": "能源科技",
  "smart.tech": "智慧科技",
  "cyber.tech": "网络科技",
  "ultra.tech": "超级科技",
  "super.tech": "超级技术",
  "micro.tech": "微型技术",
  // .red
  "infra.red": "红外线",
  "hat.red": "仇恨",
  "hund.red": "一百",
  "kind.red": "同族",
  "sac.red": "神圣的",
  // .run
  "out.run": "超越/跑赢",
  "re.run": "重播/再跑",
  "home.run": "本垒打",
  "dry.run": "彩排",
  "free.run": "自由跑",
  "ultra.run": "超级马拉松",
  "night.run": "夜跑",
  "star.run": "明星跑",
  "sky.run": "天空跑",
  // .win
  "dar.win": "达尔文",
  "al.vin": "阿尔文",
  "cal.vin": "卡尔文",
  "ke.vin": "凯文",
  "good.win": "好赢",
  "bald.win": "鲍德温",
  // .tax
  "syn.tax": "语法/句法",
  "pre.tax": "税前",
  "over.tax": "过度征税",
  // .fan
  "ste.fan": "斯特凡",
  "caravan": "大篷车",
  "artisan": "工匠",
  "partisan": "党派的/游击队员",
  "christian": "基督徒",
  "guardian": "守护者",
  "trojan": "特洛伊",
  // .fish (more)
  "oa.fish": "蠢笨的",
  "dog.fish": "角鲨",
  "bat.fish": "蝙蝠鱼",
  "gar.fish": "雀鳝",
  // .pub
  "micro.pub": "小型酒吧",
  "night.pub": "夜间酒吧",
  "web.pub": "网络出版",
  "e.pub": "电子书",
  "digi.pub": "数字出版",
  // .yoga
  "hatha.yoga": "哈他瑜伽",
  "bikram.yoga": "高温瑜伽",
  "hot.yoga": "热瑜伽",
  "kundalini.yoga": "昆达利尼瑜伽",
  "power.yoga": "力量瑜伽",
  "open.yoga": "开放式瑜伽",
  "fly.yoga": "空中瑜伽",
  "air.yoga": "悬浮瑜伽",
  // .bar
  "side.bar": "侧边栏",
  "tool.bar": "工具栏",
  "task.bar": "任务栏",
  "scroll.bar": "滚动条",
  "menu.bar": "菜单栏",
  "status.bar": "状态栏",
  "title.bar": "标题栏",
  "handle.bar": "车把",
  "cross.bar": "横杆",
  "crow.bar": "撬棍",
  "mini.bar": "小酒吧",
  "search.bar": "搜索栏",
  "smart.bar": "智能栏",
  // .top
  "roof.top": "屋顶",
  "desk.top": "桌面",
  "lap.top": "笔记本",
  "table.top": "桌面",
  "mountain.top": "山顶",
  "counter.top": "台面",
  "tree.top": "树顶",
  "hill.top": "山丘顶",
  // .map
  "road.map": "路线图",
  "site.map": "站点地图",
  "heat.map": "热图",
  "mind.map": "思维导图",
  "sky.map": "星图",
  "star.map": "星图",
  "world.map": "世界地图",
  "geo.map": "地理图",
  "data.map": "数据图",
  "tree.map": "树状图",
  "brain.map": "脑图",
  "risk.map": "风险图",
  "life.map": "人生规划",
  "city.map": "城市地图",
  "air.map": "航图",
  // .art
  "heart": "心/核心",
  "start": "开始",
  "smart": "聪明/智能",
  "re.start": "重新开始",
  "kick.start": "启动",
  "up.start": "新兴/初创",
  "counter.part": "对应物",
  "sweet.heart": "甜心",
  "brave.heart": "勇敢的心",
  "lion.heart": "雄心",
  "street.art": "街头艺术",
  "modern.art": "现代艺术",
  "pop.art": "波普艺术",
  "pixel.art": "像素艺术",
  "web.art": "网络艺术",
  "fan.art": "粉丝创作",
  "photo.art": "摄影艺术",
  // .pet
  "car.pet": "地毯",
  "trump.et": "小号/王牌",
  "plan.et": "行星",
  "tar.get": "目标",
  "rock.et": "火箭",
  "tick.et": "票",
  "bask.et": "篮筐",
  "brack.et": "括号",
  "rack.et": "球拍",
  "pock.et": "口袋",
  "sock.et": "插座",
  "buck.et": "桶",
  "head.set": "耳机",
  "market": "市场",
  "internet": "互联网",
  "dragnet": "天罗地网",
  // .one
  "phone": "电话",
  "zone": "区域",
  "stone": "石头",
  "alone": "独自",
  "clone": "克隆",
  "mile.stone": "里程碑",
  "corner.stone": "基石",
  "lime.stone": "石灰石",
  "ear.phone": "耳机",
  "micro.phone": "麦克风",
  "saxo.phone": "萨克斯",
  "trom.bone": "长号",
  "chromo.some": "染色体",
  "every.one": "每个人",
  "some.one": "某人",
  "any.one": "任何人",
  "back.bone": "脊骨/骨气",
  "head.phone": "耳机",
  "smart.phone": "智能手机",
  "ring.tone": "铃声",
  "mono.tone": "单调",
  "over.tone": "弦外之音",
  "cap.stone": "压顶石/顶点",
  "gem.stone": "宝石",
  "touch.stone": "试金石",
  // .fund
  "re.fund": "退款",
  "crowd.fund": "众筹",
  "trust.fund": "信托基金",
  "hedge.fund": "对冲基金",
  "seed.fund": "种子基金",
  "open.fund": "开放式基金",
  "green.fund": "绿色基金",
  "startup.fund": "创业基金",
  // .film
  "short.film": "短片",
  "micro.film": "微胶卷",
  "dark.film": "黑色电影",
  "slow.film": "慢电影",
  "web.film": "网络影片",
  "open.film": "开放电影",
  "cyber.film": "网络电影",
  // .farm
  "wind.farm": "风力发电场",
  "data.farm": "数据农场",
  "cloud.farm": "云农场",
  "web.farm": "网络农场",
  "server.farm": "服务器农场",
  "sea.farm": "海洋农场",
  "tree.farm": "苗圃",
  "organic.farm": "有机农场",
  "smart.farm": "智慧农场",
  "robo.farm": "机器人农场",
  // .food
  "sea.food": "海鲜",
  "fast.food": "快餐",
  "slow.food": "慢食",
  "raw.food": "生食",
  "real.food": "真实食物",
  "super.food": "超级食物",
  "street.food": "街头食物",
  "pet.food": "宠物食品",
  "baby.food": "婴儿食品",
  "dog.food": "狗粮",
  "health.food": "健康食品",
  // .ink
  "think": "思考",
  "drink": "喝/饮料",
  "re.think": "重新思考",
  "hyper.link": "超链接",
  "deep.link": "深度链接",
  "inter.link": "互链",
  "cross.link": "交叉链接",
  "hot.link": "热链",
  "over.think": "过度思考",
  "group.think": "群体思维",
  "free.think": "自由思考",
  "hard.link": "硬链接",
  "back.link": "反向链",
  "per.malink": "永久链接",
  "bio.ink": "生物墨水",
  "nano.ink": "纳米墨水",
  "smart.ink": "智能墨水",
  // .fit
  "out.fit": "装备/全套服装",
  "ben.efit": "好处/利益",
  "pro.fit": "利润",
  "mis.fit": "不合适",
  "retro.fit": "改装",
  "sum.mit": "峰会",
  "per.mit": "许可",
  "com.mit": "承诺",
  "sub.mit": "提交",
  "trans.mit": "传输",
  "o.mit": "省略",
  "ad.mit": "承认",
  "acquit": "宣判无罪",
  "forfeit": "没收/放弃",
  "coun.terfeit": "伪造",
  "be.fit": "适合",
  "un.fit": "不适合",
  "sport.fit": "运动达人",
  "life.fit": "健康生活",
  "body.fit": "健身",
  // .ink (extra)
  "zinc": "锌/z.inc 创意",
  "pink": "粉红色",
  "sink": "水槽/下沉",
  "brink": "边缘",
  "blink": "眨眼",
  "shrink": "收缩",
  "stink": "臭味",
  "kink": "卷曲",
  "rink": "溜冰场",
  "wink": "眨眼",
};
