// Word Library Extra 19 - 5-letter gTLD expansions
// Auto-generated from 370K English word corpus
// 90 TLDs, 1251 total words

export const WORD_LIBRARY_EXTRA19: Record<string, string[]> = {
  actor: ["factor", "tactor", "abactor", "coactor", "enactor", "exactor", "reactor", "tractor", "cofactor", "impactor", "olfactor", "proactor", "redactor", "varactor", "attractor", "coenactor", "compactor", "contactor", "detractor", "effractor", "extractor", "infractor", "playactor", "prefactor", "refractor", "retractor", "subfactor", "abstractor", "benefactor", "calefactor", "contractor", "cornfactor", "idemfactor", "malefactor", "manufactor", "nonreactor", "postfactor", "protractor", "subtractor", "teletactor", "transactor", "underactor", "autotractor", "multifactor", "underfactor", "chiropractor", "cocontractor", "counteractor", "lithofractor", "subcontractor", "cephalotractor", "hydroextractor"],
  adult: ["unadult", "nonadult", "preadult", "subadult", "demiadult"],
  archi: ["bawarchi", "xenarchi", "antiarchi"],
  audio: ["claudio"],
  beats: ["upbeats", "offbeats", "backbeats", "browbeats", "deadbeats", "downbeats", "drumbeats", "hoofbeats", "heartbeats"],
  bible: ["rubible"],
  black: ["azoblack", "eyeblack", "forblack", "nonblack", "antiblack", "blueblack", "boneblack", "bootblack", "lampblack", "overblack", "shoeblack"],
  boats: ["airboats", "bumboats", "catboats", "flyboats", "gunboats", "iceboats", "pigboats", "rowboats", "towboats", "tugboats", "bareboats", "cockboats", "faltboats", "fireboats", "fishboats", "flatboats", "foldboats", "johnboats", "keelboats", "lifeboats", "longboats", "sailboats", "showboats", "surfboats", "workboats", "ferryboats", "houseboats", "motorboats", "powerboats", "speedboats", "steamboats", "whaleboats"],
  boots: ["reboots", "gumboots", "seaboots", "slyboots", "freeboots", "hardboots", "jackboots", "lazyboots", "smoothboots"],
  bosch: ["suikerbosch", "stellenbosch"],
  build: ["rebuild", "unbuild", "upbuild", "misbuild", "outbuild", "bodybuild", "homebuild", "overbuild", "shipbuild", "jerrybuild", "superbuild", "underbuild"],
  canon: ["demicanon", "nomocanon"],
  cards: ["scards", "discards", "placards", "bankcards", "filmcards", "flancards", "postcards", "timecards", "microcards"],
  chase: ["bechase", "enchase", "inchase", "rechase", "dischase", "forchase", "outchase", "purchase", "forechase", "overchase", "interchase", "repurchase", "mispurchase", "nonpurchase", "prepurchase", "propurchase", "overpurchase", "steeplechase"],
  cheap: ["overcheap"],
  cisco: ["francisco"],
  citic: ["ascitic", "dacitic", "calcitic", "leucitic", "helicitic", "sericitic", "preascitic", "anthracitic", "plebiscitic"],
  click: ["unclick"],
  cloud: ["acloud", "becloud", "encloud", "uncloud", "discloud", "stackencloud"],
  coach: ["cocoach", "encoach", "recoach", "uncoach", "aircoach", "discoach", "skycoach", "mailcoach", "slipcoach", "slowcoach", "tidecoach", "motorcoach", "stagecoach"],
  codes: ["decodes", "encodes", "lycodes", "recodes", "sarcodes", "microcodes", "balmarcodes"],
  crown: ["becrown", "decrown", "encrown", "recrown", "uncrown", "discrown", "archcrown", "baldcrown", "overcrown", "copplecrown", "yellowcrown", "cropplecrown"],
  dance: ["adance", "aidance", "abidance", "biddance", "outdance", "riddance", "tendance", "voidance", "abondance", "avoidance", "exundance", "hovedance", "impedance", "overdance", "ropedance", "stepdance", "yieldance", "accordance", "appendance", "ascendance", "attendance", "dependance", "intendance", "intrudance", "providance", "recordance", "redundance", "regardance", "retardance", "concordance", "contradance", "descendance", "discordance", "forbiddance", "misguidance", "nonguidance", "portendance", "preguidance", "prevoidance", "reavoidance", "unabundance", "counterdance", "foreguidance", "inaccordance", "nonavoidance", "preabundance", "reattendance", "unaccordance", "unattendance", "disaccordance", "disregardance", "nonappendance", "nonascendance", "nonattendance", "nondependance", "nonregardance", "outrecuidance", "overabundance", "preaccordance", "proattendance", "superabundance", "supersuperabundance"],
  deals: ["ideals", "ordeals", "misdeals"],
  dodge: ["outdodge"],
  drive: ["redrive", "fordrive", "misdrive", "outdrive", "predrive", "deerdrive", "overdrive", "pulldrive", "microdrive", "screwdrive", "underdrive", "counterdrive"],
  earth: ["dearth", "yearth", "inearth", "iwearth", "forehearth", "pennyearth", "underearth", "multihearth", "counterearth"],
  email: ["bemail", "remail", "kaltemail"],
  epson: ["stepson"],
  faith: ["unfaith", "disfaith", "misfaith", "overfaith", "interfaith"],
  final: ["affinal", "cofinal", "prefinal", "semifinal", "pseudofinal", "quarterfinal"],
  games: ["degames", "gilgames", "ballgames"],
  gives: ["ogives", "regives", "forgives", "misgives", "outgives"],
  glass: ["eyeglass", "owlglass", "spyglass", "sunglass", "tinglass", "hourglass", "isinglass", "overglass", "sandglass", "vitaglass", "wineglass", "brodeglass", "ferroglass", "fiberglass", "fibreglass", "galloglass", "nightglass", "plexiglass", "watchglass", "waterglass", "gallowglass", "weatherglass"],
  green: ["begreen", "engreen", "regreen", "ungreen", "ayegreen", "azogreen", "nongreen", "outgreen", "sengreen", "shagreen", "silgreen", "aquagreen", "mythogreen", "undergreen", "oystergreen", "sempergreen", "wintergreen", "subevergreen", "semievergreen"],
  gripe: ["begripe", "ungripe", "handygripe"],
  group: ["aggroup", "ingroup", "regroup", "outgroup", "subgroup", "newsgroup", "semigroup", "intergroup", "intragroup", "supergroup"],
  guide: ["reguide", "illguide", "outguide", "preguide", "waveguide"],
  homes: ["trichomes"],
  honda: ["rhonda"],
  horse: ["ahorse", "unhorse", "bathorse", "bawhorse", "dishorse", "redhorse", "sawhorse", "warhorse", "carthorse", "cockhorse", "demihorse", "drawhorse", "drayhorse", "forehorse", "overhorse", "packhorse", "rearhorse", "studhorse", "woodhorse", "hobbyhorse", "underhorse", "waterhorse", "wheelhorse", "clotheshorse"],
  house: ["chouse", "shouse", "thouse", "oxhouse", "rehouse", "unhouse", "baghouse", "beehouse", "bughouse", "carhouse", "cathouse", "cobhouse", "cophouse", "cothouse", "cowhouse", "deyhouse", "dishouse", "doghouse", "dryhouse", "dyehouse", "fanhouse", "gashouse", "ginhouse", "gunhouse", "henhouse", "hothouse", "joyhouse", "madhouse", "mughouse", "mumhouse", "nuthouse", "piehouse", "pothouse", "raghouse", "subhouse", "tanhouse", "taphouse", "teahouse", "tinhouse", "toyhouse", "tryhouse", "wayhouse", "almshouse", "archhouse", "babyhouse", "backhouse", "bakehouse", "bathhouse", "beadhouse", "beamhouse", "bedehouse", "beerhouse", "bellhouse", "birdhouse", "brewhouse", "bunkhouse", "cakehouse", "cardhouse", "casthouse", "coolhouse", "cornhouse", "deadhouse", "deckhouse", "dockhouse", "dosshouse", "dovehouse", "duckhouse", "fishhouse", "flophouse", "lathhouse", "limehouse", "longhouse", "malthouse", "milkhouse", "millhouse", "oasthouse", "overhouse", "packhouse", "peathouse", "peelhouse", "pesthouse", "pockhouse", "poorhouse", "porthouse", "posthouse", "purlhouse", "resthouse", "salthouse", "sliphouse", "snowhouse", "stadhouse", "stewhouse", "tirehouse", "tollhouse", "toolhouse", "townhouse", "warmhouse", "washhouse", "wellhouse", "winehouse", "woodhouse", "bargehouse", "bawdyhouse", "blockhouse", "bridehouse", "brinehouse", "charthouse", "clockhouse", "cubbyhouse", "ferryhouse", "goosehouse", "grasshouse", "guardhouse", "guesthouse", "jewelhouse", "pilothouse", "questhouse", "roughhouse", "roundhouse", "sheephouse", "shillhouse", "shirehouse", "speakhouse", "spicehouse", "stadthouse", "stagehouse", "statehouse", "stillhouse", "stockhouse", "stovehouse", "sugarhouse", "sweathouse", "watchhouse", "weighhouse", "wheelhouse", "whorehouse", "womanhouse", "barrelhouse", "bleachhouse", "boilerhouse", "chargehouse", "crucethouse", "culverhouse", "customhouse", "enginehouse", "hurleyhouse", "motherhouse", "oysterhouse", "porterhouse", "prisonhouse", "rewarehouse", "springhouse", "steaakhouse", "chapterhouse", "charterhouse", "customshouse", "draughthouse", "lodginghouse", "meetinghouse", "packinghouse", "puddinghouse", "westinghouse", "boardinghouse", "countinghouse"],
  intel: ["lintel", "pointel"],
  irish: ["airish", "mirish", "fairish", "squirish", "vampirish", "openairish", "voltairish", "millionairish"],
  lease: ["olease", "please", "malease", "release", "ewelease", "nuclease", "prelease", "sublease", "displease", "misplease", "outplease", "rerelease", "nonrelease", "overplease", "prerelease", "prorelease", "underlease", "exonuclease", "superplease", "endonuclease", "ribonuclease", "counterplease", "phosphonuclease", "deoxyribonuclease", "desoxyribonuclease"],
  legal: ["unlegal", "prelegal", "antelegal", "postlegal", "semilegal", "sociolegal", "supralegal", "medicolegal", "preterlegal", "pseudolegal", "biblicolegal", "philosophicolegal"],
  lexus: ["plexus", "amplexus", "complexus", "diaplexus", "proplexus", "neuroplexus", "ganglioplexus"],
  loans: ["reloans"],
  lotte: ["belotte", "calotte", "culotte", "charlotte", "gamelotte", "matelotte", "sansculotte"],
  lotto: ["blotto"],
  mango: ["chimango"],
  media: ["comedia", "premedia", "iphimedia", "postmedia", "intermedia"],
  money: ["commoney", "nonmoney", "almsmoney", "baldmoney", "hockmoney", "spurmoney", "undermoney"],
  music: ["undermusic"],
  nexus: ["connexus"],
  nikon: ["phonikon", "diakonikon"],
  paris: ["liparis", "capparis", "chamaecyparis"],
  parts: ["departs", "imparts", "comparts", "disparts", "misparts", "outparts", "ramparts", "subparts", "foreparts", "mouthparts", "underparts", "counterparts"],
  phone: ["dyphone", "euphone", "diaphone", "dyophone", "geophone", "isophone", "odophone", "osophone", "otophone", "sulphone", "trephone", "aerophone", "allophone", "audiphone", "auriphone", "autophone", "batyphone", "cinephone", "homophone", "ideophone", "idiophone", "melophone", "monophone", "motophone", "optophone", "polyphone", "pyrophone", "telephone", "tisiphone", "topophone", "tubaphone", "tubuphone", "vitaphone", "xylophone", "dentaphone", "dentiphone", "dictaphone", "disulphone", "gramaphone", "gramophone", "housephone", "hydrophone", "interphone", "lithophone", "mellophone", "nautophone", "osteophone", "persephone", "phonophone", "photophone", "radiophone", "sousaphone", "vibraphone", "vibrophone", "videophone", "waterphone", "actinophone", "buzzerphone", "calliophone", "chordophone", "dynamophone", "francophone", "glassophone", "graphophone", "heckelphone", "kinetophone", "mellowphone", "organophone", "pseudophone", "retelephone", "sonorophone", "stereophone", "stethophone", "techniphone", "thermophone", "trisulphone", "aluminaphone", "ceraunophone", "dermatophone", "detectaphone", "electrophone", "harmoniphone", "inductophone", "kaleidophone", "keraulophone", "keraunophone", "magnetophone", "metallophone", "monosulphone", "pantelephone", "picturephone", "pretelephone", "sarrusophone", "speakerphone", "spectrophone", "sphygmophone", "stentorphone", "telegraphone", "theatrophone", "tracheophone", "biophotophone", "membranophone", "monotelephone", "microtelephone", "phototelephone", "radiotelephone", "teleradiophone", "radiomicrophone", "telegraphophone", "thermotelephone", "magnetotelephone", "seismomicrophone"],
  photo: ["aerophoto", "telephoto", "wirephoto", "radiophoto"],
  place: ["aplace", "biplace", "byplace", "deplace", "emplace", "unplace", "anyplace", "outplace", "preplace", "supplace", "farmplace", "foreplace", "homeplace", "monoplace", "overplace", "postplace", "showplace", "someplace", "everyplace", "interplace", "transplace", "predisplace", "uncommonplace"],
  power: ["impower", "repower", "unpower", "gunpower", "nonpower", "warpower", "brainpower", "disempower", "hydropower", "underpower", "waterpower", "womanpower", "candlepower", "thermopower", "electropower", "prowaterpower"],
  press: ["adpress", "appress", "bepress", "cypress", "depress", "empress", "express", "impress", "oppress", "repress", "acupress", "compress", "dispress", "harpress", "hotpress", "keypress", "nonpress", "outpress", "subpress", "suppress", "bookpress", "derepress", "handpress", "inexpress", "overpress", "reexpress", "reimpress", "reoppress", "uncypress", "unexpress", "usurpress", "winepress", "woolpress", "decompress", "misexpress", "preexpress", "preimpress", "preoppress", "recompress", "resuppress", "letterpress", "overdepress", "overexpress", "overimpress", "overrepress", "precompress", "presuppress", "clothespress"],
  quest: ["acquest", "sequest", "barquest", "chiquest", "opaquest", "perquest", "uniquest", "brusquest", "chicquest", "unrequest", "prerequest", "reconquest", "unconquest", "forerequest", "preconquest", "proconquest", "postconquest", "counterconquest"],
  radio: ["exradio", "preradio", "photoradio"],
  rocks: ["brocks", "crocks", "frocks", "trocks", "bedrocks", "caprocks", "defrocks", "lavrocks", "mudrocks", "outrocks", "rimrocks", "unfrocks", "disfrocks", "jumprocks", "laverocks", "shamrocks", "traprocks"],
  sharp: ["unsharp", "outsharp", "cardsharp", "oversharp", "undersharp"],
  shell: ["beshell", "enshell", "inshell", "unshell", "earshell", "eggshell", "figshell", "jusshell", "nutshell", "seashell", "subshell", "bombshell", "clamshell", "hardshell", "lampshell", "shotshell", "slitshell", "papershell", "toothshell", "cockleshell", "oystershell", "tortoiseshell"],
  shoes: ["reshoes", "gumshoes", "toeshoes", "overshoes", "snowshoes", "horseshoes"],
  smile: ["asmile", "besmile", "resmile", "outsmile", "subsmile", "semismile", "countersmile"],
  solar: ["unsolar", "nonsolar", "presolar", "subsolar", "antisolar", "lunisolar", "extrasolar", "supersolar", "suprasolar", "circumsolar", "typhlosolar"],
  space: ["aspace", "espace", "dispace", "respace", "getspace", "midspace", "misspace", "subspace", "antispace", "freespace", "monospace", "crawlspace", "eigenspace", "hydrospace", "interspace", "microspace", "whitespace", "letterspace", "nobackspace", "quarterspace"],
  sport: ["asport", "disport", "gosport", "outsport", "prosport", "semisport", "spoilsport", "retransport", "pretransport"],
  store: ["astore", "fstore", "bestore", "enstore", "instore", "unstore", "prestore", "substore", "nanostore", "overstore", "uprestore", "disrestore", "microstore", "overrestore"],
  study: ["estudy", "restudy", "nonstudy", "outstudy", "prestudy", "forestudy", "overstudy", "afterstudy", "understudy"],
  style: ["distyle", "enstyle", "eustyle", "instyle", "restyle", "systyle", "axostyle", "diastyle", "dyostyle", "epistyle", "misstyle", "neostyle", "prostyle", "substyle", "surstyle", "urostyle", "areostyle", "decastyle", "endostyle", "gonostyle", "hexastyle", "hypostyle", "mesostyle", "metastyle", "octastyle", "parastyle", "peristyle", "polystyle", "pygostyle", "tylostyle", "zygostyle", "araeostyle", "cyclostyle", "cyrtostyle", "enneastyle", "heptastyle", "macrostyle", "metrostyle", "orthostyle", "pentastyle", "pycnostyle", "sarcostyle", "tetrastyle", "areosystyle", "blastostyle", "dodecastyle", "araeosystyle", "cephalostyle", "duodecastyle", "amphiprostyle", "tetraprostyle", "pseudoprostyle"],
  sucks: ["tussucks", "waesucks"],
  tires: ["attires", "entires", "retires", "satires", "saltires", "overtires"],
  tools: ["retools", "barstools", "campstools", "footstools", "toadstools"],
  tours: ["stours", "detours", "contours", "faitours", "santours", "alentours"],
  trade: ["strade", "estrade", "retrade", "contrade", "nontrade", "outtrade", "protrade", "antitrade", "balustrade", "intertrade", "pilastrade", "undertrade"],
  trust: ["betrust", "entrust", "intrust", "retrust", "untrust", "distrust", "mistrust", "nontrust", "wantrust", "antitrust", "overtrust", "predistrust"],
  tunes: ["attunes", "retunes", "untunes", "fortunes", "mistunes", "importunes", "misfortunes"],
  video: ["montevideo"],
  wales: ["swales", "gunwales", "pinwales"],
  watch: ["awatch", "dogwatch", "midwatch", "outwatch", "birdwatch", "overwatch", "deathwatch", "ninnywatch", "paddywatch", "scoutwatch", "underwatch", "wristwatch"],
  weber: ["megaweber", "microweber", "milliweber"],
  wells: ["dwells", "swells", "fowells", "upwells", "indwells", "inkwells", "maxwells", "upswells", "farewells", "gromwells", "speedwells", "stairwells", "groundswells"],
  works: ["byworks", "inworks", "reworks", "artworks", "cutworks", "gasworks", "legworks", "networks", "outworks", "pinworks", "setworks", "tanworks", "tarworks", "tinworks", "topworks", "tryworks", "warworks", "waxworks", "beadworks", "bodyworks", "buhlworks", "busyworks", "capeworks", "caseworks", "cribworks", "deadworks", "fireworks", "fishworks", "flatworks", "footworks", "fretworks", "gateworks", "hackworks", "hairworks", "handworks", "headworks", "homeworks", "ironworks", "laceworks", "lathworks", "leadworks", "lifeworks", "linkworks", "meatworks", "meshworks", "millworks", "openworks", "overworks", "rackworks", "roadworks", "rockworks", "saltworks", "seatworks", "semiworks", "silkworks", "slopworks", "soapworks", "studworks", "taskworks", "teamworks", "tileworks", "timeworks", "tubeworks", "wireworks", "woodworks", "yardworks", "brassworks", "clockworks", "earthworks", "frameworks", "glassworks", "interworks", "metalworks", "printworks", "scrapworks", "slateworks", "steelworks", "sternworks", "stoneworks", "sugarworks", "upperworks", "watchworks", "waterworks", "wheelworks", "bleachworks", "boilerworks", "breastworks", "copperworks", "masterworks", "starchworks", "subnetworks", "internetworks"],
  world: ["unworld", "outworld", "antiworld", "demiworld", "foreworld", "overworld", "afterworld", "interworld", "otherworld", "supraworld", "cumberworld"],
};
