// Additional Chinese meanings for domain hack words — batch 2
// Merged at runtime via domain-hack.ts

export const WORD_MEANINGS_EXTRA2: Record<string, string> = {
  // .cc words
  "so.cc": "足球(缩)",
  "a.cc": "账户(缩)",

  // .mt words
  "amo.mt": "数量(缩)",
  "mome.mt": "时刻(缩)",
  "comme.mt": "评论(缩)",
  "eleme.mt": "元素(缩)",
  "payme.mt": "支付(缩)",
  "docume.mt": "文档(缩)",
  "moveme.mt": "运动(缩)",
  "achieveme.mt": "成就(缩)",
  "agreeme.mt": "协议(缩)",
  "manageme.mt": "管理(缩)",
  "governme.mt": "政府(缩)",
  "investme.mt": "投资(缩)",
  "developme.mt": "发展(缩)",
  "environme.mt": "环境(缩)",
  "equipme.mt": "设备(缩)",
  "stateme.mt": "声明(缩)",
  "treatme.mt": "治疗(缩)",
  "monume.mt": "纪念碑(缩)",
  "parliame.mt": "议会(缩)",

  // .hm words
  "rhyth.hm": "节奏(缩)",
  "algorith.hm": "算法(缩)",

  // .fi words
  "wi.fi": "无线网络",
  "sel.fi": "自拍(缩)",
  "sa.fi": "安全(缩)",
  "gra.fi": "涂鸦(缩)",
  "beauti.fi": "美化(缩)",
  "classi.fi": "分类(缩)",
  "clari.fi": "澄清(缩)",
  "identi.fi": "识别(缩)",
  "justi.fi": "证明(缩)",
  "magni.fi": "放大(缩)",
  "modi.fi": "修改(缩)",
  "noti.fi": "通知(缩)",
  "quali.fi": "合格(缩)",
  "satis.fi": "满足(缩)",
  "simpli.fi": "简化(缩)",
  "speci.fi": "指定(缩)",
  "veri.fi": "验证(缩)",
  "ampli.fi": "放大(缩)",
  "certi.fi": "认证(缩)",
  "puri.fi": "净化(缩)",
  "uni.fi": "统一(缩)",

  // .bi words
  "ali.bi": "不在场证明",
  "wasa.bi": "芥末",
  "zom.bi": "僵尸(缩)",
  "hob.bi": "爱好(缩)",
  "lob.bi": "大厅(缩)",
  "ba.bi": "宝贝(缩)",
  "ru.bi": "红宝石(缩)",
  "near.bi": "附近(缩)",
  "lulla.bi": "摇篮曲(缩)",

  // .do words
  "ju.do": "柔道",
  "torna.do": "龙卷风",
  "avoca.do": "牛油果",
  "torpe.do": "鱼雷",
  "tuxe.do": "燕尾服",
  "crescen.do": "渐强",
  "innuen.do": "暗示",
  "cre.do": "信条",
  "weir.do": "怪人",
  "re.do": "重做",
  "un.do": "撤销",
  "sha.do": "影子(缩)",
  "win.do": "窗户(缩)",

  // .no words
  "pia.no": "钢琴",
  "casi.no": "赌场",
  "volca.no": "火山",
  "tech.no": "科技音乐",
  "rhi.no": "犀牛",
  "albi.no": "白化",
  "domi.no": "多米诺",
  "sopra.no": "女高音",
  "cappucci.no": "卡布奇诺",
  "lati.no": "拉丁的",
  "di.no": "恐龙(缩)",
  "demo.no": "恶魔(缩)",
  "kimo.no": "和服",
  "mo.no": "单声道",
  "chro.no": "时间(缩)",

  // .ee words
  "fr.ee": "免费/自由",
  "tr.ee": "树",
  "thr.ee": "三",
  "agr.ee": "同意",
  "degr.ee": "学位/度",
  "employ.ee": "员工",
  "guarant.ee": "保证",
  "refug.ee": "难民",
  "nomin.ee": "被提名者",
  "b.ee": "蜜蜂",
  "f.ee": "费用",
  "s.ee": "看见",
  "kn.ee": "膝盖",
  "coff.ee": "咖啡",
  "jubil.ee": "周年纪念",
  "refer.ee": "裁判",
  "for.ee": "预见(缩)",
  "overs.ee": "监督(缩)",

  // .nc words
  "pri.nc": "王子(缩)",
  "si.nc": "自从(缩)",
  "da.nc": "舞蹈(缩)",
  "cha.nc": "机会(缩)",
  "roma.nc": "浪漫(缩)",
  "bala.nc": "平衡(缩)",
  "fina.nc": "金融(缩)",
  "dista.nc": "距离(缩)",
  "guida.nc": "指导(缩)",
  "tolera.nc": "容忍(缩)",
  "scie.nc": "科学(缩)",
  "sile.nc": "沉默(缩)",
  "viole.nc": "暴力(缩)",
  "patie.nc": "耐心(缩)",
  "evide.nc": "证据(缩)",
  "seque.nc": "序列(缩)",
  "influe.nc": "影响(缩)",
  "audie.nc": "观众(缩)",
  "confide.nc": "信心(缩)",
  "experie.nc": "经验(缩)",
  "independe.nc": "独立(缩)",
  "intellige.nc": "智慧(缩)",
  "excelle.nc": "卓越(缩)",
  "performa.nc": "表现(缩)",
  "appeara.nc": "外表(缩)",
  "insura.nc": "保险(缩)",
  "entra.nc": "入口(缩)",
  "fragra.nc": "芳香(缩)",

  // .gy words
  "ener.gy": "能量",
  "strate.gy": "策略",
  "technolo.gy": "技术",
  "biolo.gy": "生物学",
  "geolo.gy": "地质学",
  "ecolo.gy": "生态学",
  "psycholo.gy": "心理学",
  "theolo.gy": "神学",
  "mytholo.gy": "神话学",
  "antholo.gy": "选集",
  "analo.gy": "类比",
  "trilo.gy": "三部曲",
  "aller.gy": "过敏",
  "cler.gy": "神职人员",
  "syner.gy": "协同效应",
  "prodi.gy": "天才",
  "zoolo.gy": "动物学",
  "archaeolo.gy": "考古学",
  "ideolo.gy": "意识形态",
  "methodolo.gy": "方法论",
  "chronolo.gy": "年代学",
  "terminolo.gy": "术语学",
  "sociolo.gy": "社会学",
  "cosmolo.gy": "宇宙学",
  "neurolo.gy": "神经学",
  "oncolo.gy": "肿瘤学",
  "cardiolo.gy": "心脏病学",
  "radiolo.gy": "放射学",
  "physiolo.gy": "生理学",
  "patholo.gy": "病理学",
  "pharmacolo.gy": "药理学",

  // .ky words
  "mon.ky": "猴子(缩)",
  "tur.ky": "火鸡(缩)",
  "don.ky": "驴(缩)",
  "hoc.ky": "曲棍球(缩)",
  "joc.ky": "骑师(缩)",
  "smo.ky": "烟雾缭绕的",
  "roc.ky": "岩石的",
  "luc.ky": "幸运的",
  "fun.ky": "时髦的",
  "ris.ky": "冒险的",
  "fris.ky": "活泼的",
  "hus.ky": "哈士奇",
  "quir.ky": "古怪的",
  "mil.ky": "乳白色的",
  "sil.ky": "丝滑的",
  "chun.ky": "矮胖的",
  "cran.ky": "暴躁的",
  "whis.ky": "威士忌(缩)",
  "kid.ky": "肾脏(缩)",
  "tric.ky": "棘手的",
  "stic.ky": "粘的",
  "pic.ky": "挑剔的",
  "s.ky": "天空",

  // .sy words
  "ea.sy": "容易的",
  "bu.sy": "忙碌的",
  "no.sy": "好管闲事的",
  "ro.sy": "玫瑰色的",
  "co.sy": "舒适的",
  "dai.sy": "雏菊",
  "la.sy": "懒惰的(缩)",
  "cra.sy": "疯狂的(缩)",
  "fanta.sy": "幻想",
  "ecsta.sy": "狂喜",
  "jealo.sy": "嫉妒",
  "controver.sy": "争议",
  "embas.sy": "大使馆",
  "clum.sy": "笨拙的",
  "chee.sy": "俗气的",
  "bree.sy": "微风的",
  "grea.sy": "油腻的",
  "unea.sy": "不安的",

  // .py words
  "hap.py": "快乐的",
  "co.py": "复制",
  "thera.py": "治疗",
  "cano.py": "天篷",
  "entro.py": "熵",
  "pup.py": "小狗",
  "cris.py": "脆的",
  "cree.py": "恐怖的",
  "slee.py": "困倦的",
  "grum.py": "暴躁的",
  "bum.py": "颠簸的",
  "snap.py": "活泼的/爽快的",
  "unhap.py": "不快乐的",

  // .th words
  "ma.th": "数学",
  "ba.th": "浴室",
  "pa.th": "路径",
  "fai.th": "信仰",
  "heal.th": "健康",
  "weal.th": "财富",
  "steal.th": "隐身",
  "grow.th": "增长",
  "you.th": "青年",
  "tru.th": "真相",
  "sou.th": "南方",
  "nor.th": "北方",
  "wor.th": "价值",
  "ear.th": "地球",
  "bir.th": "出生",
  "dea.th": "死亡",
  "brea.th": "呼吸",
  "streng.th": "力量",
  "leng.th": "长度",
  "dep.th": "深度",
  "warm.th": "温暖",
  "slo.th": "树懒/懒惰",
  "bro.th": "肉汤",
  "fro.th": "泡沫",
  "mo.th": "飞蛾",
  "bandwid.th": "带宽",
  "rebir.th": "重生",

  // .ir words
  "a.ir": "空气",
  "ha.ir": "头发",
  "fa.ir": "公平的",
  "pa.ir": "一对",
  "cha.ir": "椅子",
  "sta.ir": "楼梯",
  "repa.ir": "修理",
  "affa.ir": "事务",
  "despa.ir": "绝望",
  "st.ir": "搅拌",
  "s.ir": "先生",
  "souen.ir": "纪念品",
  "memo.ir": "回忆录",
  "reservo.ir": "水库",
  "fla.ir": "天赋/才华",
  "la.ir": "巢穴",
  "ecla.ir": "闪电泡芙",
  "em.ir": "酋长",

  // .ec words
  "sp.ec": "规格(缩)",
  "ch.ec": "检查(缩)",
  "d.ec": "甲板(缩)",
  "n.ec": "脖子(缩)",
  "t.ec": "技术(缩)",
  "dir.ec": "直接(缩)",
  "corr.ec": "正确(缩)",
  "conn.ec": "连接(缩)",
  "prot.ec": "保护(缩)",
  "det.ec": "检测(缩)",
  "resp.ec": "尊重(缩)",
  "eff.ec": "效果(缩)",
  "perf.ec": "完美(缩)",
  "coll.ec": "收集(缩)",
  "refl.ec": "反映(缩)",
  "sel.ec": "选择(缩)",
  "proj.ec": "项目(缩)",
  "archit.ec": "建筑师(缩)",
  "intell.ec": "智慧(缩)",
  "ins.ec": "昆虫(缩)",

  // .za words
  "piz.za": "披萨",
  "pla.za": "广场",
  "bonan.za": "繁荣/大发现",
  "extravagan.za": "盛会",
  "influen.za": "流感",
  "stan.za": "诗节",

  // .ag words
  "b.ag": "包/袋",
  "t.ag": "标签",
  "fl.ag": "旗帜",
  "dr.ag": "拖拽",
  "br.ag": "吹嘘",
  "sw.ag": "赃物/酷",
  "st.ag": "雄鹿",
  "r.ag": "破布",
  "n.ag": "唠叨",
  "sn.ag": "障碍",
  "zigz.ag": "之字形",

  // .ad words
  "b.ad": "坏的",
  "s.ad": "悲伤的",
  "m.ad": "疯狂的",
  "gl.ad": "高兴的",
  "p.ad": "垫/平板",
  "d.ad": "爸爸",
  "ro.ad": "道路",
  "lo.ad": "载入/负荷",
  "bro.ad": "宽的",
  "he.ad": "头",
  "le.ad": "领导",
  "re.ad": "阅读",
  "de.ad": "死的",
  "bre.ad": "面包",
  "spre.ad": "展开",
  "thre.ad": "线程",
  "inste.ad": "代替",
  "ahe.ad": "前方",
  "downlo.ad": "下载",
  "uplo.ad": "上传",
  "abro.ad": "国外",
  "nom.ad": "游牧民",
  "sal.ad": "沙拉",

  // .nz words
  "bro.nz": "青铜(缩)",
  "fre.nz": "狂热(缩)",
  "bona.nz": "大发现(缩)",

  // .lk words
  "mi.lk": "牛奶",
  "si.lk": "丝绸",
  "bu.lk": "散装/大量",
  "hu.lk": "绿巨人",
  "fo.lk": "人们",
  "wa.lk": "走路",
  "ta.lk": "说话",
  "cha.lk": "粉笔",
  "sta.lk": "跟踪",
  "e.lk": "麋鹿",
  "yo.lk": "蛋黄",

  // .lt words
  "sa.lt": "盐",
  "bo.lt": "螺栓/闪电",
  "vo.lt": "伏特",
  "resu.lt": "结果",
  "adu.lt": "成人",
  "defau.lt": "默认",
  "assau.lt": "攻击",
  "consu.lt": "咨询",
  "insu.lt": "侮辱",
  "be.lt": "腰带",
  "fe.lt": "感觉(过去式)",
  "me.lt": "融化",
  "bui.lt": "建造(过去式)",
  "gui.lt": "内疚",
  "qui.lt": "被子",
  "fau.lt": "错误",
  "vau.lt": "金库",
  "revo.lt": "反抗",

  // .lv words
  "so.lv": "解决(缩)",
  "reso.lv": "决心(缩)",
  "evo.lv": "进化(缩)",
  "invo.lv": "涉及(缩)",
  "disso.lv": "溶解(缩)",
  "va.lv": "阀门(缩)",
  "twe.lv": "十二(缩)",
  "she.lv": "搁置(缩)",
  "de.lv": "挖掘(缩)",
};
