// Chinese meanings for domain hack words
// Format: "full_word" -> "中文释义"

export const WORD_MEANINGS: Record<string, string> = {
  // Common & popular domain hacks
  "hello.world": "你好世界",
  "tom.cat": "汤姆猫",
  "bit.ly": "比特缩短",
  "goo.gl": "谷歌缩短",
  "love.ly": "可爱地",
  "friend.ly": "友好的",
  "week.ly": "每周的",
  "dai.ly": "每日的",
  "month.ly": "每月的",
  "quick.ly": "快速地",
  "safe.ly": "安全地",
  "live.ly": "生动地",
  "final.ly": "最终地",
  "actual.ly": "实际上",
  "total.ly": "完全地",
  "natural.ly": "自然地",
  "virtual.ly": "虚拟地",
  "tru.ly": "真实地",
  "ho.ly": "神圣的",
  "ear.ly": "早期的",
  "near.ly": "几乎",
  "clear.ly": "清楚地",
  "exact.ly": "恰好",
  "definite.ly": "肯定地",
  "bare.ly": "仅仅",
  "rare.ly": "很少地",
  "mere.ly": "仅仅",
  "sure.ly": "确实",
  "pure.ly": "纯粹地",
  "late.ly": "最近",
  "wide.ly": "广泛地",
  "deep.ly": "深深地",
  "bad.ly": "严重地",
  "sad.ly": "悲伤地",
  "mad.ly": "疯狂地",
  "glad.ly": "高兴地",
  "kind.ly": "善良地",
  "cost.ly": "昂贵的",
  "ghost.ly": "幽灵般的",
  "most.ly": "主要地",
  "like.ly": "可能的",
  "lone.ly": "孤独的",
  "home.ly": "朴素的",
  "ug.ly": "丑陋的",
  "supp.ly": "供应",
  "app.ly": "申请/应用",
  "rep.ly": "回复",
  "multip.ly": "乘以/增多",
  "imp.ly": "暗示",
  "comp.ly": "遵守",
  "re.ly": "依赖",
  "f.ly": "飞",
  "s.ly": "狡猾的",
  "bul.ly": "霸凌",
  "jel.ly": "果冻",
  "bel.ly": "肚子",
  "sil.ly": "愚蠢的",
  "fami.ly": "家庭",
  "ita.ly": "意大利",
  "anomal.ly": "异常",
  "assemb.ly": "集会/组装",
  "butterf.ly": "蝴蝶",
  "smart.ly": "聪明地",
  "part.ly": "部分地",
  "soft.ly": "柔软地",
  "gent.ly": "温柔地",
  "simp.ly": "简单地",
  "open.ly": "公开地",
  "absolute.ly": "绝对地",
  "complete.ly": "完全地",
  "entire.ly": "完全地",
  "perfect.ly": "完美地",
  "certain.ly": "当然",
  "probab.ly": "可能",
  "possib.ly": "可能",
  "current.ly": "目前",
  "recent.ly": "最近",
  "frequent.ly": "频繁地",
  "constant.ly": "不断地",
  "apparent.ly": "显然",
  "obvious.ly": "明显地",
  "serious.ly": "严肃地",
  
  // .in words
  "doma.in": "域名",
  "jo.in": "加入",
  "tra.in": "火车/训练",
  "bra.in": "大脑",
  "ga.in": "获得",
  "cha.in": "链条",
  "ma.in": "主要的",
  "pla.in": "朴素的",
  "aga.in": "再次",
  "rema.in": "保持",
  "conta.in": "包含",
  "obta.in": "获得",
  "log.in": "登录",
  "plug.in": "插件",
  "beg.in": "开始",
  "w.in": "赢",
  "sk.in": "皮肤",
  "sp.in": "旋转",
  "tw.in": "双胞胎",
  "p.in": "别针/固定",
  "b.in": "箱子",
  "th.in": "薄的",
  "gr.in": "露齿笑",
  "f.in": "鳍",
  "cab.in": "小屋/机舱",
  "sat.in": "缎子",
  "res.in": "树脂",
  "bas.in": "盆地",
  "ru.in": "废墟/毁灭",
  "co.in": "硬币",
  "lat.in": "拉丁语",
  "marg.in": "边距/利润",
  "orig.in": "起源",
  "virg.in": "处女/原始的",
  "certa.in": "确定的",
  "capta.in": "队长/船长",
  "mounta.in": "山",
  "founta.in": "喷泉",
  "curta.in": "窗帘",
  "villa.in": "恶棍",
  "terra.in": "地形",
  "expla.in": "解释",
  "compla.in": "抱怨",
  "mainta.in": "维护",
  "enterta.in": "娱乐",
  "susta.in": "维持",
  "atta.in": "达到",
  "deta.in": "拘留",
  "reta.in": "保留",
  "stra.in": "拉紧/压力",
  "adm.in": "管理员",
  "bullet.in": "公告",
  "dolph.in": "海豚",
  "pengu.in": "企鹅",
  "pumpk.in": "南瓜",
  "napk.in": "餐巾",
  "vitam.in": "维生素",
  "insul.in": "胰岛素",
  "berl.in": "柏林",
  "darw.in": "达尔文",
  "prote.in": "蛋白质",
  "pa.in": "疼痛",
  "ra.in": "雨",
  "va.in": "徒劳的",
  "gra.in": "谷物/颗粒",
  "dra.in": "排水",
  "spa.in": "西班牙",
  "sta.in": "污渍",
  "barga.in": "讨价还价",
  "refra.in": "克制",
  "constra.in": "限制",
  "restra.in": "约束",
  "absta.in": "禁戒",
  "perta.in": "属于",
  "ascerta.in": "查明",
  "disda.in": "蔑视",
  "orda.in": "任命",
  "muff.in": "松饼",
  "coff.in": "棺材",
  "gobl.in": "哥布林",
  "merl.in": "梅林",
  "kreml.in": "克里姆林宫",
  "greml.in": "小精灵",
  "urch.in": "顽童",
  "viol.in": "小提琴",
  "mandol.in": "曼陀铃",
  "javel.in": "标枪",
  "aspir.in": "阿司匹林",
  "submar.in": "潜水艇",
  
  // .is words
  "th.is": "这个",
  "h.is": "他的",

  // .it words
  "b.it": "比特/位",
  "h.it": "打击/热门",
  "f.it": "适合",
  "k.it": "套件",
  "s.it": "坐",
  "w.it": "机智",
  "sp.it": "吐",
  "sl.it": "切割",
  "kn.it": "编织",
  "subm.it": "提交",
  "comm.it": "承诺",
  "adm.it": "承认",
  "perm.it": "许可",
  "lim.it": "限制",
  "vis.it": "访问",
  "depos.it": "存款/押金",
  "prof.it": "利润",
  "cred.it": "信用",
  "ed.it": "编辑",
  "un.it": "单元/单位",
  "orb.it": "轨道",
  "hab.it": "习惯",
  "rabb.it": "兔子",
  "sp.ir.it": "精神",
  "inhab.it": "居住",
  "exhib.it": "展览",
  "prohib.it": "禁止",
  "inhib.it": "抑制",

  // .me words
  "ho.me": "家",
  "na.me": "名字",
  "ga.me": "游戏",
  "ti.me": "时间",
  "co.me": "来",
  "so.me": "一些",
  "fra.me": "框架",
  "fla.me": "火焰",
  "fa.me": "名声",
  "bla.me": "责备",
  "sha.me": "羞耻",
  "sa.me": "相同的",
  "volu.me": "音量/卷",
  "resu.me": "简历/恢复",
  "costu.me": "服装",
  "perfu.me": "香水",
  "welco.me": "欢迎",
  "beco.me": "成为",
  "overco.me": "克服",
  "outco.me": "结果",
  "inco.me": "收入",
  "aweso.me": "极好的",
  "handso.me": "英俊的",
  "wholeso.me": "有益健康的",
  "tireho.me": "烦人的",
  "progra.me": "程序",
  "sche.me": "方案/计划",
  "the.me": "主题",
  "extre.me": "极端的",
  "supre.me": "至高无上的",

  // .am words
  "dre.am": "梦想",
  "te.am": "团队",
  "stre.am": "流/溪流",
  "cre.am": "奶油",
  "ste.am": "蒸汽",
  "be.am": "光束",
  "se.am": "缝",
  "fo.am": "泡沫",
  "ro.am": "漫游",
  "cl.am": "蛤蜊",
  "j.am": "果酱/堵塞",
  "h.am": "火腿",
  "d.am": "水坝",
  "r.am": "公羊/内存",
  "sl.am": "猛击",
  "sw.am": "游泳(过去式)",
  "progr.am": "程序",
  "diagr.am": "图表",
  "telegr.am": "电报",
  "inst.am": "即时",

  // .io words
  "rat.io": "比率",
  "stud.io": "工作室",
  "rad.io": "收音机",
  "aud.io": "音频",
  "portfol.io": "作品集",
  "scenar.io": "场景",
  "patron.io": "赞助人",

  // .ai words
  "br.ai": "大脑(缩)",
  "th.ai": "泰国的",
  "sam.ai": "武士",
  "bons.ai": "盆景",
  "shor.ai": "短(缩)",

  // .co words  
  "ta.co": "墨西哥卷",
  "e.co": "生态",
  "dis.co": "迪斯科",

  // .us words
  "foc.us": "聚焦",
  "bon.us": "奖金",
  "stat.us": "状态",
  "gen.us": "天才/属",
  "camp.us": "校园",
  "circ.us": "马戏团",
  "radi.us": "半径",
  "minim.us": "最小",
  "maxim.us": "最大",
  "vir.us": "病毒",
  "fung.us": "真菌",
  "cact.us": "仙人掌",
  "octop.us": "章鱼",
  "plat.us": "鸭嘴兽",

  // .es words
  "not.es": "笔记",
  "gam.es": "游戏",
  "fil.es": "文件",
  "cod.es": "代码",
  "nod.es": "节点",
  "vot.es": "投票",
  "typ.es": "类型",
  "shar.es": "分享",
  "wav.es": "波浪",
  "flam.es": "火焰",
  "fram.es": "框架",
  "nam.es": "名字",
  "gat.es": "大门",
  "pag.es": "页面",
  "lin.es": "线条",
  "phas.es": "阶段",
  "spac.es": "空间",
  "plac.es": "地方",
  "fac.es": "面孔",

  // .be words
  "may.be": "也许",
  "glo.be": "地球仪",
  "pro.be": "探测",
  "tri.be": "部落",
  "scri.be": "抄写员",
  "descri.be": "描述",
  "prescri.be": "开处方",
  "su.be": "管",
  "cu.be": "立方体",
  "tu.be": "管子",
  "ro.be": "长袍",
  "wardro.be": "衣橱",

  // .al words
  "digit.al": "数字的",
  "glob.al": "全球的",
  "loc.al": "本地的",
  "norm.al": "正常的",
  "tot.al": "总共的",
  "fin.al": "最终的",
  "origin.al": "原始的",
  "natur.al": "自然的",
  "person.al": "个人的",
  "nation.al": "国家的",
  "anim.al": "动物",
  "hospit.al": "医院",
  "capit.al": "首都/资本",
  "crimin.al": "犯罪的",
  "tropic.al": "热带的",
  "music.al": "音乐的",
  "magic.al": "魔法的",
  "logic.al": "逻辑的",
  "technic.al": "技术的",
  "classic.al": "古典的",
  "physic.al": "物理的",
  "chemic.al": "化学的",
  "medic.al": "医学的",
  "politic.al": "政治的",
  "biologic.al": "生物的",
  "mathematic.al": "数学的",
  "mechanic.al": "机械的",
  "electric.al": "电气的",
  "historic.al": "历史的",
  "geographic.al": "地理的",

  // .at words
  "ch.at": "聊天",
  "fl.at": "公寓/平的",
  "he.at": "热",
  "se.at": "座位",
  "be.at": "节拍/打败",
  "me.at": "肉",
  "ne.at": "整洁的",
  "whe.at": "小麦",
  "thre.at": "威胁",
  "tre.at": "对待/款待",
  "swe.at": "汗水",
  "gre.at": "伟大的",
  "repe.at": "重复",
  "defe.at": "打败",
  "cre.at": "创造(缩)",
  "form.at": "格式",
  "h.at": "帽子",
  "c.at": "猫",
  "b.at": "蝙蝠",
  "r.at": "老鼠",
  "m.at": "垫子",
  "f.at": "胖的",

  // .to words
  "pho.to": "照片",
  "mo.to": "摩托",
  "au.to": "汽车",
  "pota.to": "土豆",
  "toma.to": "番茄",
  "mos.to": "葡萄汁",
  "ot.to": "奥托",

  // .re words
  "sco.re": "分数",
  "sto.re": "商店",
  "sha.re": "分享",
  "ca.re": "关心",
  "mo.re": "更多",
  "befo.re": "之前",
  "natu.re": "自然",
  "futu.re": "未来",
  "cultu.re": "文化",
  "structu.re": "结构",
  "adventu.re": "冒险",
  "figu.re": "数字/人物",
  "pictu.re": "图片",
  "captu.re": "捕获",
  "measu.re": "测量",
  "treasu.re": "宝藏",
  "pleasu.re": "快乐",

  // .de words
  "co.de": "代码",
  "mo.de": "模式",
  "no.de": "节点",
  "gui.de": "指南",
  "insi.de": "里面",
  "outsi.de": "外面",
  "provi.de": "提供",
  "deci.de": "决定",
  "upgra.de": "升级",
  "tra.de": "贸易",
  "sha.de": "阴影",
  "bla.de": "刀片",
  "gra.de": "年级/等级",
  "arca.de": "拱廊/游戏厅",
  "casca.de": "瀑布/级联",
  "para.de": "游行",
  "lemo.na.de": "柠檬水",

  // .ch words
  "ri.ch": "富有的",
  "ea.ch": "每个",
  "rea.ch": "到达",
  "tea.ch": "教",
  "bea.ch": "海滩",
  "sear.ch": "搜索",
  "resear.ch": "研究",
  "laun.ch": "发射/启动",
  "bran.ch": "分支",
  "mat.ch": "匹配/比赛",
  "wat.ch": "手表/观看",
  "cat.ch": "抓住",
  "swit.ch": "开关/切换",
  "mu.ch": "很多",
  "su.ch": "如此",
  "tou.ch": "触摸",
  "approa.ch": "接近/方法",

  // .se words
  "cau.se": "原因/引起",
  "becau.se": "因为",
  "pau.se": "暂停",
  "hou.se": "房子",
  "mou.se": "鼠标",
  "clau.se": "条款",
  "pur.se": "钱包",
  "cour.se": "课程",
  "hor.se": "马",
  "nur.se": "护士",
  "sen.se": "感觉/意义",
  "den.se": "密集的",
  "ten.se": "紧张的",
  "respon.se": "回应",
  "defen.se": "防御",
  "offen.se": "进攻",
  "licen.se": "许可证",
  "expen.se": "费用",
  "promi.se": "承诺",
  "surpri.se": "惊喜",
  "enterpri.se": "企业",
  "databa.se": "数据库",
  "purcha.se": "购买",
  "relea.se": "发布/释放",
  "increa.se": "增加",
  "decrea.se": "减少",

  // .ge words
  "pa.ge": "页面",
  "sta.ge": "舞台/阶段",
  "a.ge": "年龄",
  "hu.ge": "巨大的",
  "ima.ge": "图像",
  "messa.ge": "消息",
  "packa.ge": "包裹/套餐",
  "mana.ge": "管理",
  "dama.ge": "损坏",
  "stora.ge": "存储",
  "avera.ge": "平均",
  "coura.ge": "勇气",
  "langua.ge": "语言",
  "knowled.ge": "知识",
  "brid.ge": "桥",
  "jud.ge": "法官/判断",
  "pled.ge": "承诺",
  "ed.ge": "边缘",
  "char.ge": "充电/收费",

  // .sh words
  "fre.sh": "新鲜的",
  "cra.sh": "崩溃",
  "fla.sh": "闪光",
  "da.sh": "破折号/冲刺",
  "ca.sh": "现金",
  "pu.sh": "推",
  "ru.sh": "冲/赶",
  "cru.sh": "压碎/迷恋",
  "bru.sh": "刷子",
  "fi.sh": "鱼",
  "wi.sh": "愿望",
  "di.sh": "盘子/菜",
  "fini.sh": "完成",
  "publi.sh": "发布",
  "establi.sh": "建立",
  "accompli.sh": "完成",
  "dimini.sh": "减少",

  // .so words
  "al.so": "也",
  "rea.so": "原因(缩)",

  // .st words
  "be.st": "最好的",
  "te.st": "测试",
  "re.st": "休息",
  "fa.st": "快的",
  "la.st": "最后的",
  "pa.st": "过去",
  "va.st": "广阔的",
  "fir.st": "第一",
  "wor.st": "最差的",
  "ho.st": "主持/主机",
  "po.st": "邮寄/帖子",
  "co.st": "成本",
  "lo.st": "失去的",
  "mo.st": "最",
  "tru.st": "信任",
  "ju.st": "只是/公正",
  "mu.st": "必须",
  "du.st": "灰尘",
  "gu.st": "阵风",
  "ru.st": "锈",
  "bu.st": "胸像/破产",
  "fore.st": "森林",
  "hone.st": "诚实的",
  "mode.st": "谦虚的",
  "intere.st": "兴趣",
  "reque.st": "请求",
  "prote.st": "抗议",
  "sugge.st": "建议",
  "inve.st": "投资",
  "harve.st": "收获",
  "manife.st": "显示/清单",

  // .ng words
  "ki.ng": "国王",
  "si.ng": "唱歌",
  "ri.ng": "戒指/响",
  "bri.ng": "带来",
  "thi.ng": "事物",
  "stro.ng": "强壮的",
  "lo.ng": "长的",
  "so.ng": "歌曲",
  "amo.ng": "在…之中",
  "belo.ng": "属于",
  "alo.ng": "沿着",
  "wro.ng": "错误的",
  "yo.ng": "年轻(变体)",
  "spri.ng": "春天/弹簧",
  "stri.ng": "字符串/绳",
  "savi.ng": "储蓄",
  "meani.ng": "意义",
  "morni.ng": "早晨",
  "eveni.ng": "晚上",
  "beginni.ng": "开始",
  "openi.ng": "开放",
  "warni.ng": "警告",
  "planni.ng": "计划",
  "runni.ng": "跑步",
  "comi.ng": "到来",
  "landi.ng": "着陆",
  "cooki.ng": "烹饪",
  "banki.ng": "银行业",
  "tradi.ng": "交易",
  "codi.ng": "编程",
  "hacki.ng": "黑客",
  "gami.ng": "游戏",
  "streami.ng": "流媒体",
  "learni.ng": "学习",
  "buildi.ng": "建筑/构建",
  "designi.ng": "设计",
  "marketi.ng": "营销",
  "advertisi.ng": "广告",

  // .tv words
  "crea.tv": "创意TV",

  // .im words
  "sw.im": "游泳",
  "sl.im": "苗条的",
  "tr.im": "修剪",
  "cl.im": "攀登(缩)",
  "gr.im": "严酷的",
  "pr.im": "原始的(缩)",
  "v.im": "活力/Vim编辑器",
  "wh.im": "突发奇想",
  "a.im": "目标/瞄准",
  "cla.im": "声称",
  "prel.im": "预赛(缩)",
  "musl.im": "穆斯林",
  "inter.im": "临时的",
  "vict.im": "受害者",
  "pilgr.im": "朝圣者",
  "maxim.im": "格言",
  "denim.im": "牛仔布",

  // .la words
  "vi.la": "别墅(缩)",
  "go.la": "目标(缩)",
  "umbre.la": "雨伞(缩)",
  "formu.la": "公式",
  "gorilla": "大猩猩",
  "vanil.la": "香草",
  "cine.la": "电影(缩)",

  // .no words
  "tech.no": "电子音乐",
  "albi.no": "白化的",
  "casi.no": "赌场",
  "volca.no": "火山",
  "pia.no": "钢琴",

  // .nu words
  "me.nu": "菜单",

  // .pe words
  "ty.pe": "类型",
  "ho.pe": "希望",
  "sco.pe": "范围",
  "sha.pe": "形状",
  "reci.pe": "食谱",
  "landsca.pe": "风景",
  "esca.pe": "逃跑",

  // .er words
  "hack.er": "黑客",
  "mak.er": "创客",
  "design.er": "设计师",
  "play.er": "播放器/玩家",
  "us.er": "用户",
  "cod.er": "编程员",
  "found.er": "创始人",
  "lead.er": "领导者",
  "teach.er": "教师",
  "speak.er": "演讲者",
  "driv.er": "司机/驱动",
  "writ.er": "作家",
  "farm.er": "农民",
  "pow.er": "力量",
  "flow.er": "花",
  "tow.er": "塔",
  "show.er": "淋浴",
  "comput.er": "计算机",
  "print.er": "打印机",
  "serv.er": "服务器",
  "develop.er": "开发者",
  "manag.er": "经理",
  "custom.er": "客户",
  "consult.er": "顾问",
  "consum.er": "消费者",
  "anoth.er": "另一个",
  "togeth.er": "一起",
  "weath.er": "天气",
  "leath.er": "皮革",
  "feath.er": "羽毛",
  "gath.er": "聚集",
  "numb.er": "数字",
  "memb.er": "成员",
  "rememb.er": "记住",
  "septemb.er": "九月",
  "octob.er": "十月",
  "novemb.er": "十一月",
  "decemb.er": "十二月",
  "cent.er": "中心",
  "ent.er": "进入",
  "wint.er": "冬天",
  "summ.er": "夏天",
  "dinn.er": "晚餐",
  "inn.er": "内部的",
  "butt.er": "黄油",
  "matt.er": "事情/物质",
  "bett.er": "更好的",
  "lett.er": "信/字母",
  "aft.er": "之后",
  "chapt.er": "章节",
  "mast.er": "大师/主人",
  "disast.er": "灾难",
  "monst.er": "怪物",
  "clust.er": "集群",
  "filt.er": "过滤器",
  "boost.er": "助推器",

  // .ar words
  "st.ar": "星星",
  "c.ar": "车",
  "b.ar": "酒吧/条",
  "f.ar": "远的",
  "w.ar": "战争",
  "j.ar": "罐子",
  "sol.ar": "太阳的",
  "popul.ar": "流行的",
  "regul.ar": "规则的",
  "simil.ar": "相似的",
  "singul.ar": "单数的",
  "cellul.ar": "细胞的",
  "circul.ar": "圆形的",
  "sug.ar": "糖",
  "guit.ar": "吉他",
  "radi.ar": "辐射(缩)",
  "calend.ar": "日历",
  "pill.ar": "柱子",
  "doll.ar": "美元",
  "coll.ar": "衣领",
  "gramm.ar": "语法",

  // .ag words
  "fl.ag": "旗帜",
  "b.ag": "袋子",
  "t.ag": "标签",
  "dr.ag": "拖拽",

  // .og words
  "bl.og": "博客",
  "d.og": "狗",
  "f.og": "雾",
  "j.og": "慢跑",
  "l.og": "日志",
  "fr.og": "青蛙",
  "catal.og": "目录",
  "dial.og": "对话",

  // .gy words
  "ener.gy": "能量",
  "aller.gy": "过敏",
  "strate.gy": "策略",
  "technolo.gy": "技术",
  "biolo.gy": "生物学",
  "geolo.gy": "地质学",
  "psycholo.gy": "心理学",
  "mytholo.gy": "神话学",
  "ideolo.gy": "意识形态",
  "analo.gy": "类比",
  "trilo.gy": "三部曲",
  "prodi.gy": "天才/神童",
  "litur.gy": "礼拜仪式",
  "syner.gy": "协同效应",
  "cler.gy": "牧师/教士",

  // .tv words (deduped)

  // .io expanded (only new entries)
  "pat.io": "庭院",
  "pistach.io": "开心果",

  // .or words
  "maj.or": "主要的",
  "min.or": "次要的",
  "auth.or": "作者",
  "edit.or": "编辑",
  "act.or": "演员",
  "doct.or": "医生",
  "tut.or": "导师",
  "ment.or": "导师/顾问",
  "mot.or": "马达/发动机",
  "mirr.or": "镜子",
  "err.or": "错误",
  "terr.or": "恐怖",
  "hum.or": "幽默",
  "rum.or": "谣言",
  "tum.or": "肿瘤",
  "hon.or": "荣誉",
  "fav.or": "偏爱",
  "flav.or": "味道",
  "col.or": "颜色",
  "val.or": "英勇",
  "harb.or": "港口",
  "anch.or": "锚",
  "vend.or": "供应商",
  "invest.or": "投资者",
  "competi.or": "竞争者",
  "senat.or": "参议员",
  "navigat.or": "导航器",

  // .on words
  "reas.on": "原因",
  "seas.on": "季节",
  "less.on": "课程",
  "pers.on": "人",
  "pris.on": "监狱",
  "pois.on": "毒药",
  "comm.on": "共同的",
  "serm.on": "布道",
  "cany.on": "峡谷",
  "cray.on": "蜡笔",
  "citr.on": "柠檬",
  "prot.on": "质子",
  "neutr.on": "中子",
  "electr.on": "电子",
  "phot.on": "光子",
  "bost.on": "波士顿",
  "badmint.on": "羽毛球",

  // .en words
  "op.en": "打开",
  "brok.en": "破碎的",
  "chos.en": "选择的",
  "froz.en": "冰冻的",
  "gold.en": "金色的",
  "wood.en": "木制的",
  "writt.en": "书写的",
  "gard.en": "花园",
  "kitch.en": "厨房",
  "chick.en": "鸡",
  "hidd.en": "隐藏的",
  "sudd.en": "突然的",
  "oft.en": "经常",
  "list.en": "听",
  "giv.en": "给予的",
  "driv.en": "驱动的",
  "heav.en": "天堂",
  "sev.en": "七",
  "elev.en": "十一",

  // .an words
  "pl.an": "计划",
  "b.an": "禁止",
  "f.an": "粉丝/风扇",
  "m.an": "人",
  "v.an": "面包车",
  "cl.an": "氏族",
  "sc.an": "扫描",
  "oce.an": "海洋",
  "hum.an": "人类的",
  "urb.an": "城市的",
  "org.an": "器官",
  "rom.an": "罗马的",
  "jap.an": "日本",
  "slog.an": "口号",
  "sult.an": "苏丹",
  "carav.an": "大篷车",

  // .ad words
  "ro.ad": "道路",
  "lo.ad": "负载/加载",
  "he.ad": "头",
  "le.ad": "领导/铅",
  "re.ad": "阅读",
  "de.ad": "死的",
  "bre.ad": "面包",
  "thre.ad": "线程/线",
  "spre.ad": "传播",
  "inste.ad": "代替",
  "downlo.ad": "下载",
  "uplo.ad": "上传",

  // .ed words
  "spe.ed": "速度",
  "fe.ed": "喂/动态",
  "se.ed": "种子",
  "ne.ed": "需要",
  "ble.ed": "流血",
  "bre.ed": "品种/繁殖",
  "gre.ed": "贪婪",
  "we.ed": "杂草",

  // .id words
  "avo.id": "避免",
  "rap.id": "快速的",
  "val.id": "有效的",
  "sol.id": "固体的",
  "flu.id": "流体",
  "pyram.id": "金字塔",
  "aster.id": "小行星",
  "andro.id": "安卓",

  // .my words
  "ar.my": "军队",
  "stor.my": "暴风雨的",
  "drea.my": "梦幻的",
  "crea.my": "奶油的",
  "gloo.my": "阴暗的",
  "roo.my": "宽敞的",
  "econo.my": "经济",
  "autono.my": "自治",
  "astrono.my": "天文学",
  "taxono.my": "分类学",

  // .ph words
  "gra.ph": "图表",
  "telegra.ph": "电报",
  "photogra.ph": "照片",
  "paragra.ph": "段落",
  "trium.ph": "胜利",

  // .do words
  "ju.do": "柔道",
  "pseu.do": "伪/假的",
  "con.do": "公寓",

  // .ht words
  "lig.ht": "光/灯",
  "rig.ht": "右/正确",
  "nig.ht": "夜晚",
  "flig.ht": "飞行/航班",
  "sig.ht": "视野",
  "mig.ht": "力量/可能",
  "weig.ht": "重量",
  "heig.ht": "高度",
  "fig.ht": "战斗",
  "thoug.ht": "想法",

  // .aw words
  "l.aw": "法律",
  "r.aw": "原始的/生的",
  "dr.aw": "画/抽",
  "cl.aw": "爪子",
  "fl.aw": "缺陷",
  "str.aw": "稻草",
  "j.aw": "下巴",
  "s.aw": "锯/看见",
  "outl.aw": "歹徒",
  "jigs.aw": "拼图",

  // .ew words
  "n.ew": "新的",
  "f.ew": "少数",
  "d.ew": "露水",
  "br.ew": "酿造",
  "cr.ew": "船员/团队",
  "scr.ew": "螺丝",
  "st.ew": "炖菜",
  "vi.ew": "查看/景色",
  "revi.ew": "评论/复习",
  "previ.ew": "预览",
  "intervi.ew": "面试/采访",
  "overvi.ew": "概览",

  // .th expanded
  "grow.th": "成长",
  "heal.th": "健康",
  "weal.th": "财富",
  "steal.th": "隐身",
  "dept.th": "深度",
  "wid.th": "宽度",
  "leng.th": "长度",
  "streng.th": "力量",
  "you.th": "青春/年轻",
  "tru.th": "真理",
  "wor.th": "价值",
  "ear.th": "地球",
  "nor.th": "北方",
  "sou.th": "南方",
  "smi.th": "铁匠",
  "mou.th": "嘴",
  "too.th": "牙齿",
  "clo.th": "布料",
  "bo.th": "两者",

  // .nu expanded (only new)
  "ve.nu": "场地(缩)",
  "reve.nu": "收入(缩)",

  // .fm words
  "refor.fm": "改革(缩)",

  // more .co words (only new)
  "mo.co": "摩纳哥",
  "bron.co": "野马",
  "fias.co": "惨败",
  "fres.co": "壁画",
  "tobac.co": "烟草",

  // more .ai words (only new)
  "h.ai": "嗨(缩)",

  // more .us words (only new)
  "ambiti.us": "雄心(缩)",
  "gener.us": "慷慨的(缩)",
  "fam.us": "著名的(缩)",
  "glori.us": "光荣的(缩)",
  "nerv.us": "紧张的(缩)",
  "seri.us": "严肃的(缩)",
  "obvi.us": "明显的(缩)",
  "curio.us": "好奇的(缩)",
  "preci.us": "珍贵的(缩)",
};
  "mo.ve": "移动",
  "li.ve": "生活/直播",
  "gi.ve": "给予",
  "ha.ve": "拥有",
  "sa.ve": "保存/节省",
  "wa.ve": "波浪",
  "ca.ve": "洞穴",
  "bra.ve": "勇敢的",
  "gra.ve": "严肃/坟墓",
  "sla.ve": "奴隶",
  "sha.ve": "剃须",
  "cra.ve": "渴望",
  "pro.ve": "证明",
  "appro.ve": "批准",
  "impro.ve": "改善",
  "remo.ve": "移除",
  "resol.ve": "解决",
  "invol.ve": "涉及",
  "evol.ve": "进化",
  "obser.ve": "观察",
  "preser.ve": "保存",
  "conser.ve": "保护",
  "deser.ve": "值得",
  "ser.ve": "服务",
  "ner.ve": "神经",
  "cur.ve": "曲线",
  "archi.ve": "档案",
  "acti.ve": "积极的",
  "massi.ve": "巨大的",
  "nati.ve": "本地的",
  "creati.ve": "创造性的",
  "negati.ve": "消极的",
  "positi.ve": "积极的",
  "sensiti.ve": "敏感的",
  "exclusi.ve": "独家的",
  "impressi.ve": "令人印象深刻的",
  "ali.ve": "活着的",
  "arri.ve": "到达",
  "dri.ve": "驾驶/驱动",
  "di.ve": "潜水",
  "fi.ve": "五",
  "thri.ve": "茁壮成长",
  "survi.ve": "生存",

  // .om words
  "ro.om": "房间",
  "bro.om": "扫帚",
  "blo.om": "开花",
  "do.om": "厄运",
  "bo.om": "繁荣/爆炸",
  "zo.om": "缩放",
  "glo.om": "忧郁",
  "mushr.om": "蘑菇(缩)",
  "classr.om": "教室(缩)",
  "bedr.om": "卧室(缩)",
  "bathr.om": "浴室(缩)",
  "showro.om": "展厅(缩)",
  "ballro.om": "舞厅(缩)",
  "kingd.om": "王国",
  "freed.om": "自由",
  "bored.om": "无聊",
  "rand.om": "随机的",
  "wisd.om": "智慧",
  "phan.om": "幻影(缩)",
  "cust.om": "自定义/习俗",
  "bott.om": "底部",
  "at.om": "原子",
  "idi.om": "习语",
  "axi.om": "公理",
  "chr.om": "铬(缩)",
  "gen.om": "基因组(缩)",
  "h.om": "家(缩)",
  "d.om": "文档对象模型",

  // .to words
  "cry.to": "加密(缩)",
  "pho.to": "照片",
  "au.to": "自动",
  "pota.to": "土豆",
  "toma.to": "番茄",
  "ve.to": "否决",
  "mot.to": "座右铭",
  "lot.to": "彩票",
  "grot.to": "洞穴",
  "burri.to": "卷饼",
  "incogni.to": "隐身",

  // .er words (expanded)
  "mak.er": "制造者",
  "play.er": "玩家",
  "hack.er": "黑客",
  "cod.er": "程序员",
  "lead.er": "领导者",
  "build.er": "建造者",
  "read.er": "读者",
  "think.er": "思想者",
  "work.er": "工作者",
  "help.er": "帮手",
  "driv.er": "驱动/司机",
  "writ.er": "作家",
  "design.er": "设计师",
  "develop.er": "开发者",
  "engine.er": "工程师",
  "manag.er": "经理",
  "found.er": "创始人",
  "creat.er": "创造者",
  "serv.er": "服务器",
  "brows.er": "浏览器",
  "rout.er": "路由器",
  "dock.er": "容器化平台",
  "compil.er": "编译器",
  "contain.er": "容器",
  "pow.er": "力量/电力",
  "tow.er": "塔",
  "flow.er": "花",
  "nev.er": "永不",
  "ev.er": "曾经",
  "forev.er": "永远",
  "discov.er": "发现",
  "wat.er": "水",
  "aft.er": "之后",
  "bett.er": "更好",
  "mast.er": "大师",

  // .ge words
  "pa.ge": "页面",
  "sta.ge": "舞台",
  "ima.ge": "图像",
  "chan.ge": "改变",
  "ran.ge": "范围",
  "challen.ge": "挑战",
  "messa.ge": "消息",
  "packa.ge": "包",
  "stora.ge": "存储",
  "langua.ge": "语言",
  "avera.ge": "平均",
  "covera.ge": "覆盖",
  "mana.ge": "管理",
  "dama.ge": "损坏",
  "gara.ge": "车库",
  "coura.ge": "勇气",
  "knowled.ge": "知识",
  "brid.ge": "桥梁",
  "jud.ge": "法官/判断",
  "ed.ge": "边缘",
  "pled.ge": "承诺",

  // .ng words
  "codi.ng": "编程",
  "gami.ng": "游戏",
  "maki.ng": "制作",
  "buildi.ng": "建筑/建造",
  "readi.ng": "阅读",
  "worki.ng": "工作",
  "learni.ng": "学习",
  "runni.ng": "跑步",
  "streami.ng": "流媒体",
  "ki.ng": "国王",
  "ri.ng": "戒指/铃声",
  "si.ng": "唱歌",
  "spri.ng": "春天/弹簧",
  "stri.ng": "字符串",
  "thi.ng": "事物",
  "bri.ng": "带来",
  "morni.ng": "早晨",
  "meeti.ng": "会议",

  // .de words
  "co.de": "代码",
  "mo.de": "模式",
  "no.de": "节点",
  "gui.de": "指南",
  "insi.de": "内部",
  "outsi.de": "外部",
  "tra.de": "贸易",
  "gra.de": "等级",
  "bla.de": "刀片",
  "sha.de": "阴影",
  "para.de": "游行",
  "arca.de": "街机",
  "deca.de": "十年",
  "upgra.de": "升级",
  "crusa.de": "远征",
  "ri.de": "骑",
  "hi.de": "隐藏",
  "si.de": "侧面",
  "pri.de": "骄傲",
  "gui.de": "引导",
  "divi.de": "分割",
  "provi.de": "提供",
  "deci.de": "决定",

  // .al words
  "digit.al": "数字的",
  "glob.al": "全球的",
  "loc.al": "本地的",
  "soci.al": "社交的",
  "natur.al": "自然的",
  "virtu.al": "虚拟的",
  "centr.al": "中央的",
  "gener.al": "一般的",
  "capit.al": "资本/首都",
  "hospit.al": "医院",
  "festiv.al": "节日",
  "arriv.al": "到达",
  "surviv.al": "生存",
  "approv.al": "批准",
  "propos.al": "提案",
  "fin.al": "最终的",
  "sign.al": "信号",
  "person.al": "个人的",
  "origin.al": "原始的",
  "crimin.al": "犯罪的",
  "norm.al": "正常的",
  "form.al": "正式的",
  "leg.al": "法律的",
  "equ.al": "平等的",
  "loy.al": "忠诚的",
  "roy.al": "皇家的",
  "tot.al": "总计",
  "fat.al": "致命的",
  "ment.al": "精神的",
  "met.al": "金属",
  "vit.al": "重要的",
  "brut.al": "残酷的",
  "cryst.al": "水晶",

  // .st words
  "be.st": "最好的",
  "te.st": "测试",
  "re.st": "休息",
  "we.st": "西方",
  "ea.st": "东方",
  "fa.st": "快速",
  "la.st": "最后",
  "pa.st": "过去",
  "co.st": "成本",
  "lo.st": "迷失",
  "ho.st": "主人/主机",
  "po.st": "邮件/帖子",
  "mo.st": "最多",
  "gho.st": "鬼",
  "toa.st": "吐司",
  "roa.st": "烤",
  "boo.st": "提升",
  "tru.st": "信任",
  "ju.st": "公正/仅仅",
  "mu.st": "必须",
  "li.st": "列表",
  "fi.st": "拳头",
  "exi.st": "存在",
  "resi.st": "抵抗",
  "arti.st": "艺术家",
  "fir.st": "第一",
  "bur.st": "爆发",
  "wor.st": "最差",
  "thir.st": "渴望",
  "que.st": "追求",
  "gue.st": "客人",
  "intere.st": "兴趣/利息",
  "fore.st": "森林",
  "hone.st": "诚实的",

  // .at words
  "ch.at": "聊天",
  "fl.at": "平的/公寓",
  "c.at": "猫",
  "h.at": "帽子",
  "b.at": "蝙蝠/球棒",
  "m.at": "垫子",
  "r.at": "老鼠",
  "bo.at": "船",
  "co.at": "外套",
  "go.at": "山羊",
  "thro.at": "喉咙",
  "wh.at": "什么",
  "th.at": "那个",
  "tre.at": "对待/款待",
  "he.at": "热量",
  "se.at": "座位",
  "gre.at": "伟大的",
  "repe.at": "重复",
  "defe.at": "击败",

  // .ch words
  "sear.ch": "搜索",
  "laun.ch": "发射/启动",
  "bran.ch": "分支",
  "mat.ch": "匹配",
  "wat.ch": "手表/观看",
  "cat.ch": "抓住",
  "swit.ch": "开关",
  "ri.ch": "富有的",
  "tea.ch": "教",
  "rea.ch": "到达",
  "bea.ch": "海滩",
  "spee.ch": "演讲",
  "resear.ch": "研究",
  "ar.ch": "拱门",
  "chur.ch": "教堂",
  "lun.ch": "午餐",
  "ben.ch": "长凳",
  "fren.ch": "法语的",

  // .id words
  "rap.id": "快速的",
  "val.id": "有效的",
  "viv.id": "生动的",
  "sol.id": "固体/坚固",
  "liqu.id": "液体",
  "hybr.id": "混合",
  "andro.id": "安卓",
  "avo.id": "避免",
  "gr.id": "网格",
  "k.id": "小孩",
  "b.id": "出价/投标",
  "ac.id": "酸",
  "flu.id": "流体",
  "squ.id": "鱿鱼",
  "pyram.id": "金字塔",
  "splend.id": "壮丽的",

  // .pe words
  "ty.pe": "类型",
  "sha.pe": "形状",
  "esca.pe": "逃脱",
  "landsca.pe": "风景",
  "ta.pe": "磁带",
  "ca.pe": "海角/披风",
  "gra.pe": "葡萄",
  "reci.pe": "食谱",
  "ho.pe": "希望",
  "ro.pe": "绳子",
  "slo.pe": "斜坡",
  "sco.pe": "范围",
  "telesco.pe": "望远镜",
  "prototy.pe": "原型",
  "stereoty.pe": "刻板印象",
  "archety.pe": "原型",
  "pi.pe": "管道",
  "stri.pe": "条纹",
  "ri.pe": "成熟的",

  // .is words
  "th.is": "这个",
  "h.is": "他的",
  "cris.is": "危机",
  "bas.is": "基础",
  "analys.is": "分析",
  "thes.is": "论文",
  "genes.is": "起源",
  "oas.is": "绿洲",
  "tenn.is": "网球",
  "ax.is": "轴",
  "orb.is": "轨道(缩)",
  "bl.is": "幸福(缩)",
  "k.is": "亲吻(缩)",

  // .se words
  "clo.se": "关闭",
  "choo.se": "选择",
  "brow.se": "浏览",
  "cour.se": "课程",
  "hor.se": "马",
  "hou.se": "房子",
  "mou.se": "鼠标/老鼠",
  "cau.se": "原因",
  "pau.se": "暂停",
  "phra.se": "短语",
  "rai.se": "提高",
  "cha.se": "追逐",
  "ca.se": "案例/箱子",
  "ba.se": "基础",
  "relea.se": "发布",
  "plea.se": "请/取悦",
  "disea.se": "疾病",
  "promi.se": "承诺",
  "surpri.se": "惊喜",
  "exerci.se": "练习",
  "pul.se": "脉搏",
  "purpo.se": "目的",
  "respon.se": "回应",
  "expen.se": "费用",
  "inten.se": "强烈的",
  "sen.se": "感觉",
  "defen.se": "防御",
  "rever.se": "反转",
  "univer.se": "宇宙",
  "diver.se": "多样的",
  "nur.se": "护士",
  "cur.se": "诅咒",
  "ro.se": "玫瑰",
  "no.se": "鼻子",
  "po.se": "姿势",
  "expo.se": "暴露",
  "propo.se": "提议",

  // .re words
  "sha.re": "分享",
  "ca.re": "关心",
  "da.re": "敢",
  "ra.re": "稀有的",
  "spa.re": "备用的",
  "compa.re": "比较",
  "prepa.re": "准备",
  "decla.re": "声明",
  "awa.re": "意识到的",
  "softwa.re": "软件",
  "hardwa.re": "硬件",
  "malwa.re": "恶意软件",
  "nightma.re": "噩梦",
  "welfa.re": "福利",
  "befo.re": "之前",
  "explo.re": "探索",
  "resto.re": "恢复",
  "igno.re": "忽略",
  "ado.re": "崇拜",
  "sto.re": "商店",
  "sco.re": "分数",
  "co.re": "核心",
  "mo.re": "更多",
  "sho.re": "海岸",
  "futu.re": "未来",
  "natu.re": "自然",
  "cultu.re": "文化",
  "structu.re": "结构",
  "adventu.re": "冒险",
  "featu.re": "特征",
  "pictu.re": "图片",
  "captu.re": "捕获",
  "temperatu.re": "温度",
  "literatu.re": "文学",
  "manufactu.re": "制造",
  "architectu.re": "建筑",
  "inspi.re": "激励",
  "desi.re": "渴望",
  "requi.re": "需要",
  "acqui.re": "获得",
  "reti.re": "退休",
  "enti.re": "整个",
  "fi.re": "火",
  "hi.re": "雇佣",
  "wi.re": "电线",
  "empi.re": "帝国",
  "vampi.re": "吸血鬼",
  "admi.re": "钦佩",
  "he.re": "这里",
  "whe.re": "哪里",
  "the.re": "那里",
  "sphe.re": "球体",
  "atmosphe.re": "大气层",
  "cu.re": "治愈",
  "pu.re": "纯净的",
  "secu.re": "安全的",
  "matu.re": "成熟的",

  // .tf words
  "cra.tf": "工艺(缩)",
  "dra.tf": "草稿(缩)",
  "aircra.tf": "飞机(缩)",
  "so.tf": "柔软(缩)",
  "le.tf": "左(缩)",
  "the.tf": "盗窃(缩)",
  "gi.tf": "礼物(缩)",
  "shi.tf": "转移(缩)",
  "dri.tf": "漂流(缩)",
  "swi.tf": "迅速(缩)",
  "li.tf": "提升(缩)",

  // .fm words
  "refor.fm": "改革(缩)",
  "infor.fm": "通知(缩)",
  "perfor.fm": "表演(缩)",
  "transfor.fm": "变革(缩)",
  "platfor.fm": "平台(缩)",
  "stor.fm": "暴风雨(缩)",
  "for.fm": "形式(缩)",
  "nor.fm": "规范(缩)",
  "war.fm": "温暖(缩)",
  "far.fm": "农场(缩)",
  "char.fm": "魅力(缩)",
  "alar.fm": "警报(缩)",

  // .gl words
  "an.gl": "天使(缩)",
  "ba.gl": "百吉饼(缩)",
  "leve.gl": "水平(缩)",
  "mode.gl": "模型(缩)",
  "loca.gl": "本地(缩)",
  "trave.gl": "旅行(缩)",
  "tunne.gl": "隧道(缩)",

  // .gr words
  "an.gr": "愤怒(缩)",
  "dan.gr": "危险(缩)",
  "hun.gr": "饥饿(缩)",
  "powe.gr": "力量(缩)",
  "wate.gr": "水(缩)",

  // .mk words
  "bookmar.mk": "书签(缩)",
  "hallmar.mk": "标志(缩)",
  "landmar.mk": "地标(缩)",
  "trademar.mk": "商标(缩)",
  "benchmar.mk": "基准(缩)",
  "remar.mk": "评论(缩)",

  // .sg words
  "son.sg": "歌(缩)",
  "lon.sg": "长(缩)",
  "stron.sg": "强(缩)",
  "kin.sg": "国王(缩)",
  "rin.sg": "戒指(缩)",
  "sin.sg": "唱(缩)",
  "thin.sg": "事物(缩)",
  "strin.sg": "字符串(缩)",

  // .sm words
  "pri.sm": "棱镜",
  "organi.sm": "有机体",
  "mechanis.sm": "机制(缩)",
  "touri.sm": "旅游",
  "journali.sm": "新闻业",
  "capitali.sm": "资本主义",
  "optimi.sm": "乐观主义",
  "pessimi.sm": "悲观主义",
  "reali.sm": "现实主义",
  "ideali.sm": "理想主义",
  "patrioti.sm": "爱国主义",
  "magnetis.sm": "磁性(缩)",
  "altrui.sm": "利他主义",
  "nihili.sm": "虚无主义",
  "enthusia.sm": "热情",
  "sarca.sm": "讽刺",
  "spa.sm": "痉挛",

  // .sc words
  "mu.sc": "音乐(缩)",
  "ba.sc": "基本(缩)",
  "cla.sc": "经典(缩)",
  "magi.sc": "魔法(缩)",
  "logi.sc": "逻辑(缩)",
  "topi.sc": "话题(缩)",
  "epi.sc": "史诗(缩)",
  "toxi.sc": "有毒(缩)",
  "organi.sc": "有机(缩)",
  "dynami.sc": "动态(缩)",
  "romanti.sc": "浪漫(缩)",
  "fantasti.sc": "奇妙(缩)",
  "dramati.sc": "戏剧性(缩)",
  "electri.sc": "电的(缩)",
  "automati.sc": "自动(缩)",
};

