/**
 * word-meanings-extra9.ts — Chinese + English meanings for extra9 word library
 * Covers: .et .ke .ar .an .th .id .sk .ky .ph .gy .my .sy .ag .ug .bi .gi .ni .li .fi .ad .il
 */
export const WORD_MEANINGS_EXTRA9: Record<string, string> = {

  // ── .et domain hacks ───────────────────────────────────────────────────────
  "mark.et":   "市场",
  "rock.et":   "火箭",
  "tick.et":   "票；门票",
  "bask.et":   "篮子；篮筐",
  "crick.et":  "板球；蟋蟀",
  "blank.et":  "毯子",
  "brack.et":  "括号；支架",
  "jack.et":   "夹克；外套",
  "pack.et":   "数据包；小包",
  "rack.et":   "球拍；喧嚣",
  "sock.et":   "插座；眼眶",
  "wick.et":   "小门；检票口",
  "buck.et":   "桶；水桶",
  "lock.et":   "小圆盒吊坠",
  "pock.et":   "口袋",
  "dock.et":   "行程单；目录",
  "thick.et":  "灌木丛",
  "trink.et":  "小饰品",
  "gadg.et":   "小装置；小玩意",
  "budg.et":   "预算",
  "widg.et":   "小组件；控件",
  "nugg.et":   "金块；精华",
  "targ.et":   "目标",
  "plan.et":   "星球；行星",
  "magn.et":   "磁铁；吸引物",
  "intern.et": "互联网",
  "cabin.et":  "内阁；橱柜",
  "bonn.et":   "童帽；引擎盖",
  "sonn.et":   "十四行诗",
  "coron.et":  "小冠；头饰",
  "bayo.net":  "刺刀",
  "corn.et":   "短号；锥形筒",
  "garn.et":   "石榴石",
  "horn.et":   "大黄蜂",
  "ether.net": "以太网",
  "clarin.et": "单簧管",
  "tabl.et":   "平板电脑；药片",
  "dropl.et":  "小水滴",
  "bookl.et":  "小册子",
  "outl.et":   "出口；插座",
  "inl.et":    "入口；水湾",
  "eyel.et":   "小孔眼",
  "haml.et":   "哈姆雷特；小村",
  "mall.et":   "木槌",
  "wall.et":   "钱包",
  "bull.et":   "子弹",
  "gobl.et":   "高脚杯",
  "scarl.et":  "猩红色",
  "amul.et":   "护身符",
  "pamphlet":  "小册子",
  "leafl.et":  "传单；叶状体",
  "velv.et":   "天鹅绒",
  "helm.et":   "头盔",
  "com.et":    "彗星",
  "po.et":     "诗人",
  "buff.et":   "自助餐；冲击",
  "bouqu.et":  "花束",
  "cascett.e": "盒式录音带",
  "gazett.e":  "公报；官方报纸",
  "roulett.e": "轮盘赌",
  "etiqu.et":  "礼节；礼仪",

  // ── .ke domain hacks ───────────────────────────────────────────────────────
  "ma.ke":      "制作；使得",
  "ta.ke":      "拿取；带走",
  "la.ke":      "湖",
  "ca.ke":      "蛋糕",
  "fa.ke":      "假的；仿冒",
  "sa.ke":      "日本清酒；缘故",
  "ba.ke":      "烘焙",
  "wa.ke":      "唤醒；尾流",
  "sha.ke":     "摇动；握手",
  "bra.ke":     "刹车；制动",
  "sna.ke":     "蛇",
  "sta.ke":     "赌注；桩",
  "mista.ke":   "错误；失误",
  "cupca.ke":   "杯形蛋糕",
  "nameса.ke":  "同名者",
  "snowfla.ke": "雪花",
  "handsha.ke": "握手；协议",
  "earthqau.ke":"地震",
  "overta.ke":  "超越；超车",
  "underta.ke": "承担；从事",
  "forsa.ke":   "遗弃；放弃",
  "bi.ke":      "自行车",
  "li.ke":      "喜欢；像",
  "hi.ke":      "徒步；涨价",
  "spi.ke":     "尖峰；钉子",
  "stri.ke":    "罢工；打击",
  "stro.ke":    "笔画；中风",
  "spo.ke":     "辐条；说话",
  "smo.ke":     "烟；抽烟",
  "bro.ke":     "打破",
  "jo.ke":      "笑话",
  "po.ke":      "戳；指头",
  "yo.ke":      "轭；约束",
  "du.ke":      "公爵",
  "flu.ke":     "侥幸；偶然",
  "rebu.ke":    "训斥；斥责",
  "anti.que":   "古董；古玩",
  "uni.que":    "独特的；唯一的",
  "mysti.que":  "神秘感",
  "techni.que": "技术；技巧",
  "bouti.que":  "精品店",
  "criti.que":  "评论；批判",
  "physi.que":  "体格；体型",

  // ── .ar domain hacks ───────────────────────────────────────────────────────
  "st.ar":       "星星；明星",
  "sol.ar":      "太阳的；太阳能",
  "pol.ar":      "极地的；极性",
  "lun.ar":      "月亮的；月球",
  "popul.ar":    "受欢迎的",
  "regul.ar":    "规则的；常规",
  "simil.ar":    "相似的",
  "famili.ar":   "熟悉的",
  "molecul.ar":  "分子的",
  "nucle.ar":    "核的；核能",
  "circul.ar":   "圆形的；通知",
  "vascu.lar":   "血管的",
  "muscul.ar":   "肌肉的；强健",
  "spectacul.ar":"壮观的",
  "particul.ar": "特别的；特定",
  "perpendicular.": "垂直的",
  "doll.ar":     "美元",
  "coll.ar":     "衣领",
  "pill.ar":     "柱子；支柱",
  "schol.ar":    "学者",
  "cell.ar":     "地窖；酒窖",
  "malt.ar":     "砂浆；迫击炮",
  "gutar":       "吉他",
  "jagu.ar":     "美洲豹",
  "avat.ar":     "头像；化身",
  "webın.ar":    "网络研讨会",
  "semın.ar":    "研讨班",
  "baz.aar":     "集市；商场",
  "caviَار":      "鱼子酱",
  "rad.ar":      "雷达",
  "son.ar":      "声呐",
  "bipolَار":     "两极的",
  "sidebar":     "侧边栏",
  "toolbar":     "工具栏",
  "navbar":      "导航栏",
  "crowbar":     "撬棍",
  "racecar":     "赛车",
  "sidecar":     "边车",
  "handlebar":   "把手",

  // ── .an domain hacks ───────────────────────────────────────────────────────
  "pl.an":        "计划；平面图",
  "sc.an":        "扫描",
  "sp.an":        "跨度；时间段",
  "cl.an":        "氏族；宗族",
  "hum.an":       "人类的；人性",
  "urb.an":       "城市的；都市",
  "oce.an":       "海洋",
  "orph.an":       "孤儿",
  "artis.an":     "工匠；手艺人",
  "guardi.an":    "守卫者；监护人",
  "histori.an":   "历史学家",
  "musici.an":    "音乐家",
  "technici.an":  "技术员",
  "physici.an":   "医生",
  "librari.an":   "图书馆员",
  "vegetari.an":  "素食主义者",
  "humanitari.an":"人道主义者",
  "partis.an":    "游击队员；支持者",
  "veteran.":     "退伍军人；老手",
  "caravan":      "大篷车；商队",
  "pelican":      "鹈鹕",
  "median":       "中间的；中位数",
  "European":     "欧洲人；欧洲的",
  "Canadian":     "加拿大人",
  "Olympian":     "奥林匹克的",

  // ── .th domain hacks ───────────────────────────────────────────────────────
  "heal.th":    "健康",
  "weal.th":    "财富",
  "steal.th":   "隐身；潜行",
  "grow.th":    "增长；成长",
  "streng.th":  "力量；强度",
  "leng.th":    "长度",
  "wid.th":     "宽度",
  "dep.th":     "深度；深刻",
  "brea.dth":   "广度；宽广",
  "ear.th":     "地球；土地",
  "wor.th":     "价值；值得",
  "bir.th":     "出生；诞生",
  "nor.th":     "北方",
  "sou.th":     "南方",
  "tru.th":     "真相；真理",
  "you.th":     "青春；青年",
  "boo.th":     "亭子；展位",
  "too.th":     "牙齿",
  "fai.th":     "信仰；信心",
  "dea.th":     "死亡",
  "brea.th":    "呼吸；气息",
  "benea.th":   "在…之下",
  "pa.th":      "路径；道路",
  "ma.th":      "数学",
  "ba.th":      "洗澡；浴室",
  "mon.th":     "月份",
  "war.mth":    "温暖",
  "warm.th":    "温暖；热情",
  "zeni.th":    "顶点；天顶",
  "mammo.th":   "猛犸象；庞大的",
  "sabba.th":   "安息日",
  "afterma.th": "后果；余波",
  "behemo.th":  "庞然大物",

  // ── .id domain hacks ───────────────────────────────────────────────────────
  "rap.id":     "快速的",
  "val.id":     "有效的；合法",
  "viv.id":     "鲜明的；生动",
  "sol.id":     "固体的；坚实",
  "flu.id":     "流体；流动",
  "luc.id":     "清晰的；明白",
  "rig.id":     "僵硬的；严格",
  "tim.id":     "胆小的；羞怯",
  "hum.id":     "潮湿的",
  "morb.id":    "病态的；病的",
  "sord.id":    "肮脏的；低劣",
  "plac.id":    "平静的；温和",
  "stup.id":    "愚蠢的",
  "hyb.rid":    "混合的；杂交",
  "andro.id":   "安卓；类人机器人",
  "tablo.id":   "小报；通俗媒体",
  "stero.id":   "类固醇",
  "astero.id":  "小行星",
  "parano.id":  "偏执的；多疑",
  "humano.id":  "类人的",
  "inval.id":   "无效的；残废",
  "splend.id":  "壮丽的；杰出",
  "cand.id":    "坦率的；直白",
  "orchıd":     "兰花",
  "pyram.id":   "金字塔",
  "druid":      "德鲁伊",
  "squid":      "鱿鱼",
  "liquid":     "液体",
  "madr.id":    "马德里（西班牙首都）",

  // ── .sk domain hacks ───────────────────────────────────────────────────────
  "ri.sk":     "风险",
  "di.sk":     "磁盘",
  "de.sk":     "桌子；服务台",
  "ta.sk":     "任务",
  "ma.sk":     "面具；掩盖",
  "fla.sk":    "烧瓶；水壶",
  "whi.sk":    "搅拌；拂去",
  "fri.sk":    "搜查；嬉戏",
  "bri.sk":    "轻快的；清爽",
  "du.sk":     "黄昏",
  "mu.sk":     "麝香",
  "tu.sk":     "长牙",
  "ba.sk":     "沐浴（阳光）",
  "kio.sk":    "亭子；小卖部",
  "asteri.sk": "星号",
  "obeli.sk":  "方尖碑",

  // ── .ky domain hacks ───────────────────────────────────────────────────────
  "luc.ky":   "幸运的",
  "tric.ky":  "棘手的；诡计多",
  "ris.ky":   "冒险的；危险",
  "chee.ky":  "厚脸皮的",
  "fun.ky":   "时髦的；有趣",
  "wac.ky":   "古怪的",
  "spoo.ky":  "阴森的；诡异",
  "roc.ky":   "岩石的；崎岖",
  "coc.ky":   "自大的",
  "stoc.ky":  "矮壮的",
  "lan.ky":   "高挑瘦的",
  "cran.ky":  "暴躁的",
  "swin.ky":  "时尚的；潮酷",
  "mur.ky":   "昏暗的；不清晰",
  "quir.ky":  "古怪有趣的",
  "per.ky":   "精力充沛的",
  "jer.ky":   "生肉干；抽动",
  "tur.key":  "火鸡",
  "hoc.key":  "曲棍球",
  "joc.key":  "骑师",
  "mon.key":  "猴子",
  "don.key":  "驴",
  "whis.key": "威士忌",

  // ── .ph domain hacks ───────────────────────────────────────────────────────
  "gra.ph":      "图表；图形",
  "paragra.ph":  "段落",
  "photogra.ph": "照片；摄影",
  "telegra.ph":  "电报",
  "autogra.ph":  "签名",
  "monogra.ph":  "专题论文",
  "lithogra.ph": "石印画",
  "polygra.ph":  "测谎仪",
  "cardiogra.ph":"心电图",
  "hololgra.ph": "全息图",
  "typogra.ph":  "印刷工",

  // ── .gy domain hacks ───────────────────────────────────────────────────────
  "technolo.gy":  "技术",
  "biolo.gy":     "生物学",
  "ecolo.gy":     "生态学",
  "psycholo.gy":  "心理学",
  "sociolo.gy":   "社会学",
  "geolo.gy":     "地质学",
  "ideolo.gy":    "意识形态",
  "theolo.gy":    "神学",
  "mytholo.gy":   "神话学",
  "zoolo.gy":     "动物学",
  "cosmolo.gy":   "宇宙学",
  "cardiolo.gy":  "心脏病学",
  "neurolo.gy":   "神经病学",
  "oncolo.gy":    "肿瘤学",
  "pharmacolo.gy":"药理学",
  "archaeolo.gy": "考古学",
  "anthropolo.gy":"人类学",
  "criminolo.gy": "犯罪学",
  "paleontolo.gy":"古生物学",
  "analo.gy":     "类比；比喻",
  "apolo.gy":     "道歉",
  "antholo.gy":   "文集；选集",
  "trilo.gy":     "三部曲",
  "eulogy":       "颂词；悼词",
  "ener.gy":      "能量；精力",
  "syner.gy":     "协同效应",
  "aller.gy":     "过敏",
  "surger.y":     "外科手术",
  "metallur.gy":  "冶金学",
  "strate.gy":    "策略；战略",
  "ele.gy":       "挽歌；悲歌",
  "lethar.gy":    "昏睡；无精打采",
  "biotechnolo.gy":"生物技术",
  "nanotechnolo.gy":"纳米技术",
  "cryptogra.phy": "密码学",
  "photographgy":  "摄影术",
  "typogra.phy":   "排版；印刷术",

  // ── .my domain hacks ───────────────────────────────────────────────────────
  "astrono.my":  "天文学",
  "econo.my":    "经济；经济学",
  "autono.my":   "自治；自主",
  "gastro.my":   "美食学",
  "taxo.my":     "分类学",
  "agro.my":     "农学",
  "anato.my":    "解剖学",
  "dicho.tomy":  "二分法",
  "harmo.ny":    "和谐；和声",
  "ceremo.ny":   "仪式；典礼",
  "testimo.ny":  "证词；证明",
  "matrimo.ny":  "婚姻",
  "parsimo.ny":  "吝啬",
  "hegemo.ny":   "霸权",
  "alimo.ny":    "赡养费",
  "acri.mo.ny":  "刻薄；尖刻",
  "alche.my":    "炼金术",
  "ene.my":      "敌人",
  "acade.my":    "学院；学会",
  "infamy":      "臭名昭著",
  "bigamy":      "重婚罪",
  "monogamy":    "一夫一妻制",
  "polygamy":    "一夫多妻",
  "pharma.cy":   "药房；药学",
  "democra.cy":  "民主；民主制",
  "priva.cy":    "隐私",
  "diplo.ma.cy": "外交",
  "bureaucra.cy":"官僚体制",
  "aristocra.cy":"贵族政治",
  "meritocracy": "精英政治",

  // ── .sy domain hacks ───────────────────────────────────────────────────────
  "ea.sy":     "容易的",
  "bu.sy":     "忙碌的",
  "ro.sy":     "玫瑰色的；乐观",
  "no.sy":     "爱管闲事的",
  "dai.sy":    "雏菊",
  "pan.sy":    "三色堇；懦弱",
  "fanta.sy":  "幻想；奇幻",
  "ecsta.sy":  "狂喜；迷幻",
  "here.sy":   "异端；异教",
  "hypocri.sy":"虚伪；伪善",
  "apostа.sy": "叛教；背叛",
  "emba.ss.y": "大使馆",
  "bossy":     "霸道的",
  "classy":    "有品位的",
  "messy":     "凌乱的",
  "fussy":     "挑剔的",
  "tipsy":     "微醉的",

  // ── .ag domain hacks ───────────────────────────────────────────────────────
  "b.ag":     "包；袋",
  "t.ag":     "标签；追踪",
  "dr.ag":    "拖拽；阻力",
  "fl.ag":    "旗帜",
  "st.ag":    "雄鹿",
  "br.ag":    "吹牛；自夸",
  "sw.ag":    "赃物；时尚",
  "sn.ag":    "障碍；意外问题",
  "zigz.ag":  "锯齿形",
  "handb.ag": "手提包",
  "sandb.ag": "沙袋",
  "airb.ag":  "安全气囊",

  // ── .ug domain hacks ───────────────────────────────────────────────────────
  "b.ug":    "虫子；窃听",
  "dr.ug":   "药物；毒品",
  "h.ug":    "拥抱",
  "m.ug":    "马克杯；抢劫",
  "pl.ug":   "插头；宣传",
  "sl.ug":   "蛞蝓；懒鬼",
  "sn.ug":   "舒适的；紧凑",
  "th.ug":   "暴徒",
  "shr.ug":  "耸肩",
  "deb.ug":  "调试",
  "unpl.ug": "拔掉插头",

  // ── .bi domain hacks ───────────────────────────────────────────────────────
  "ali.bi":  "不在场证明",
  "rab.bi":  "拉比（犹太教士）",
  "bam.bi":  "小鹿斑比",

  // ── .gi domain hacks ───────────────────────────────────────────────────────
  "yo.gi":   "瑜伽士",
  "fun.gi":  "真菌",
  "cor.gi":  "柯基犬",

  // ── .ni domain hacks ───────────────────────────────────────────────────────
  "alum.ni":    "校友；毕业生",
  "biki.ni":    "比基尼",
  "macaro.ni":  "通心粉",
  "peppero.ni": "意式辣香肠",
  "marti.ni":   "马提尼",
  "Gemi.ni":    "双子座",
  "zucchi.ni":  "西葫芦",

  // ── .li domain hacks ───────────────────────────────────────────────────────
  "brocco.li": "西兰花",
  "chi.li":    "辣椒",
  "napo.li":   "那不勒斯",
  "canno.li":  "卡诺里（意大利甜点）",
  "ravio.li":  "意大利饺子",

  // ── .fi domain hacks ───────────────────────────────────────────────────────
  "wi.fi":   "无线网络",
  "sci.fi":  "科幻",
  "hi.fi":   "高保真",

  // ── .ad domain hacks ───────────────────────────────────────────────────────
  "nom.ad":   "游牧者；流浪",
  "tri.ad":   "三元组；黑帮",
  "sal.ad":   "沙拉",
  "ball.ad":  "民谣；歌谣",
  "squ.ad":   "小队；班组",
  "gr.ad":    "毕业生",
  "olympiad": "奥林匹克运动会",

  // ── .il domain hacks ───────────────────────────────────────────────────────
  "ema.il":   "电子邮件",
  "unt.il":   "直到；在…之前",
  "civ.il":   "文明的；公民",
  "ev.il":    "邪恶的",
  "foss.il":  "化石",
  "penc.il":  "铅笔",
  "anv.il":   "铁砧",
  "vig.il":   "守夜；守候",
  "per.il":   "危险",
  "pup.il":   "学生；瞳孔",
  "counc.il": "委员会；理事",
  "utens.il": "器具；用具",
  "daffod.il":"水仙花",
  "Braz.il":  "巴西",
  "profil.e": "简介；轮廓",
  "domicil.e":"住所；定居",
};
