// WHOIS服务器地址映射 - 基于IANA官方列表完整复刻
// 数据来源: https://data.iana.org/rdap/dns.json (2026-02-04)
// 支持 1500+ TLDs

// WHOIS服务器映射表
export const WHOIS_SERVERS: Record<string, string> = {
  // ========== 通用顶级域名 (gTLDs) ==========
  "com": "whois.verisign-grs.com",
  "net": "whois.verisign-grs.com",
  "org": "whois.pir.org",
  "info": "whois.afilias.net",
  "biz": "whois.nic.biz",
  "edu": "whois.educause.edu",
  "gov": "whois.dotgov.gov",
  "mil": "whois.nic.mil",
  "int": "whois.iana.org",
  "arpa": "whois.iana.org",
  "aero": "whois.aero",
  "asia": "whois.nic.asia",
  "coop": "whois.nic.coop",
  "jobs": "whois.nic.jobs",
  "mobi": "whois.afilias.net",
  "museum": "whois.nic.museum",
  "name": "whois.nic.name",
  "post": "whois.dotpostregistry.net",
  "tel": "whois.nic.tel",
  "travel": "whois.nic.travel",
  "xxx": "whois.nic.xxx",
  "cat": "whois.nic.cat",
  "pro": "whois.registrypro.pro",

  // ========== 国家代码顶级域名 (ccTLDs) - 亚洲 ==========
  "cn": "whois.cnnic.cn",
  "jp": "whois.jprs.jp",
  "kr": "whois.kr",
  "in": "whois.registry.in",
  "tw": "whois.twnic.net.tw",
  "hk": "whois.hkirc.hk",
  "sg": "whois.sgnic.sg",
  "my": "whois.mynic.my",
  "th": "whois.thnic.co.th",
  "vn": "whois.vnnic.vn",
  "id": "whois.id",
  "ph": "whois.dot.ph",
  "pk": "whois.pknic.net.pk",
  "bd": "whois.nic.bd",
  "np": "whois.nic.np",
  "lk": "whois.nic.lk",
  "mm": "whois.registry.gov.mm",
  "kh": "whois.nic.kh",
  "la": "whois.nic.la",
  "mn": "whois.nic.mn",
  "kz": "whois.nic.kz",
  "uz": "whois.cctld.uz",
  "kg": "whois.kg",
  "am": "whois.amnic.net",
  "ge": "whois.nic.ge",
  "az": "whois.nic.az",
  "af": "whois.nic.af",
  "mo": "whois.monic.mo",
  "bn": "whois.bnnic.bn",
  "bt": "whois.nic.bt",
  "mv": "whois.nic.mv",
  "tl": "whois.nic.tl",
  "tj": "whois.nic.tj",
  "tm": "whois.nic.tm",

  // ========== 国家代码顶级域名 (ccTLDs) - 中东 ==========
  "ae": "whois.aeda.net.ae",
  "sa": "whois.nic.net.sa",
  "eg": "whois.nic.eg",
  "il": "whois.isoc.org.il",
  "qa": "whois.registry.qa",
  "kw": "whois.nic.kw",
  "om": "whois.registry.om",
  "jo": "whois.dns.jo",
  "lb": "whois.lbdr.org.lb",
  "ps": "whois.pnina.ps",
  "sy": "whois.tld.sy",
  "iq": "whois.cmc.iq",
  "ye": "whois.y.net.ye",
  "bh": "whois.nic.bh",
  "cy": "whois.nic.cy",
  "ir": "whois.nic.ir",

  // ========== 国家代码顶级域名 (ccTLDs) - 欧洲 ==========
  "uk": "whois.nic.uk",
  "de": "whois.denic.de",
  "fr": "whois.nic.fr",
  "it": "whois.nic.it",
  "es": "whois.nic.es",
  "nl": "whois.domain-registry.nl",
  "se": "whois.iis.se",
  "ch": "whois.nic.ch",
  "ru": "whois.tcinet.ru",
  "pl": "whois.dns.pl",
  "gr": "whois.ics.forth.gr",
  "cz": "whois.nic.cz",
  "be": "whois.dns.be",
  "at": "whois.nic.at",
  "dk": "whois.dk-hostmaster.dk",
  "no": "whois.norid.no",
  "fi": "whois.fi",
  "ie": "whois.iedr.ie",
  "pt": "whois.dns.pt",
  "hu": "whois.nic.hu",
  "ro": "whois.rotld.ro",
  "ua": "whois.ua",
  "is": "whois.isnic.is",
  "lu": "whois.dns.lu",
  "mt": "whois.nic.mt",
  "ee": "whois.tld.ee",
  "lv": "whois.nic.lv",
  "lt": "whois.domreg.lt",
  "si": "whois.register.si",
  "sk": "whois.sk-nic.sk",
  "hr": "whois.dns.hr",
  "bg": "whois.register.bg",
  "rs": "whois.rnids.rs",
  "al": "whois.nic.al",
  "ad": "whois.nic.ad",
  "ba": "whois.nic.ba",
  "by": "whois.cctld.by",
  "va": "whois.nic.va",
  "mc": "whois.nic.mc",
  "sm": "whois.nic.sm",
  "li": "whois.nic.li",
  "fo": "whois.nic.fo",
  "gl": "whois.nic.gl",
  "ax": "whois.ax",
  "gg": "whois.gg",
  "je": "whois.je",
  "im": "whois.nic.im",
  "mk": "whois.marnet.mk",
  "me": "whois.nic.me",
  "md": "whois.nic.md",
  "eu": "whois.eu",
  "su": "whois.tcinet.ru",
  "tr": "whois.nic.tr",

  // ========== 国家代码顶级域名 (ccTLDs) - 大洋洲 ==========
  "au": "whois.auda.org.au",
  "nz": "whois.irs.net.nz",
  "as": "whois.nic.as",
  "ck": "whois.nic.ck",
  "fj": "whois.nic.fj",
  "fm": "whois.nic.fm",
  "ki": "whois.nic.ki",
  "mh": "whois.nic.mh",
  "mp": "whois.nic.mp",
  "nc": "whois.nc",
  "nf": "whois.nic.nf",
  "nr": "whois.cenpac.net.nr",
  "nu": "whois.iis.nu",
  "pf": "whois.nic.pf",
  "pg": "whois.nic.pg",
  "pn": "whois.nic.pn",
  "pw": "whois.nic.pw",
  "sb": "whois.nic.sb",
  "tk": "whois.dot.tk",
  "to": "whois.tonic.to",
  "tv": "whois.nic.tv",
  "vu": "whois.nic.vu",
  "wf": "whois.nic.wf",
  "ws": "whois.website.ws",
  "gu": "whois.nic.gu",
  "cc": "ccwhois.verisign-grs.com",
  "cx": "whois.nic.cx",
  "hm": "whois.registry.hm",
  "io": "whois.nic.io",

  // ========== 国家代码顶级域名 (ccTLDs) - 美洲 ==========
  "us": "whois.nic.us",
  "ca": "whois.cira.ca",
  "br": "whois.registro.br",
  "mx": "whois.mx",
  "ar": "whois.nic.ar",
  "cl": "whois.nic.cl",
  "co": "whois.nic.co",
  "pe": "kero.yachay.pe",
  "ve": "whois.nic.ve",
  "uy": "whois.nic.org.uy",
  "ec": "whois.nic.ec",
  "ai": "whois.nic.ai",
  "aw": "whois.nic.aw",
  "bb": "whois.nic.bb",
  "bm": "whois.nic.bm",
  "bo": "whois.nic.bo",
  "bs": "whois.nic.bs",
  "cr": "whois.nic.cr",
  "cu": "whois.nic.cu",
  "cw": "whois.nic.cw",
  "dm": "whois.nic.dm",
  "do": "whois.nic.do",
  "gp": "whois.nic.gp",
  "gt": "whois.nic.gt",
  "gy": "whois.registry.gy",
  "hn": "whois.nic.hn",
  "ht": "whois.nic.ht",
  "jm": "whois.nic.jm",
  "ky": "whois.kyregistry.ky",
  "mq": "whois.nic.mq",
  "ms": "whois.nic.ms",
  "ni": "whois.nic.ni",
  "pa": "whois.nic.pa",
  "pr": "whois.nic.pr",
  "py": "whois.nic.py",
  "sr": "whois.nic.sr",
  "sv": "whois.nic.sv",
  "tc": "whois.nic.tc",
  "tt": "whois.nic.tt",
  "vc": "whois.nic.vc",
  "vg": "whois.nic.vg",
  "vi": "whois.nic.vi",
  "bz": "whois.afilias-grs.info",
  "lc": "whois.afilias-grs.info",
  "ag": "whois.nic.ag",
  "gd": "whois.nic.gd",
  "kn": "whois.nic.kn",
  "sx": "whois.sx",
  "pm": "whois.nic.pm",
  "fk": "whois.nic.fk",
  "gs": "whois.nic.gs",

  // ========== 国家代码顶级域名 (ccTLDs) - 非洲 ==========
  "za": "whois.registry.net.za",
  "ng": "whois.nic.net.ng",
  "ke": "whois.kenic.or.ke",
  "gh": "whois.nic.gh",
  "tn": "whois.ati.tn",
  "ma": "whois.registre.ma",
  "ao": "whois.nic.ao",
  "bf": "whois.nic.bf",
  "bi": "whois.nic.bi",
  "bj": "whois.nic.bj",
  "cd": "whois.nic.cd",
  "cf": "whois.nic.cf",
  "cg": "whois.nic.cg",
  "ci": "whois.nic.ci",
  "cm": "whois.nic.cm",
  "cv": "whois.nic.cv",
  "dj": "whois.nic.dj",
  "dz": "whois.nic.dz",
  "er": "whois.nic.er",
  "et": "whois.nic.et",
  "ga": "whois.nic.ga",
  "gm": "whois.nic.gm",
  "gn": "whois.nic.gn",
  "gq": "whois.nic.gq",
  "gw": "whois.nic.gw",
  "lr": "whois.nic.lr",
  "ls": "whois.nic.ls",
  "ly": "whois.nic.ly",
  "ml": "whois.nic.ml",
  "mr": "whois.nic.mr",
  "mz": "whois.nic.mz",
  "ne": "whois.nic.ne",
  "rw": "whois.ricta.org.rw",
  "sc": "whois.nic.sc",
  "sd": "whois.nic.sd",
  "sl": "whois.nic.sl",
  "sn": "whois.nic.sn",
  "so": "whois.nic.so",
  "ss": "whois.nic.ss",
  "st": "whois.nic.st",
  "sz": "whois.nic.sz",
  "td": "whois.nic.td",
  "tg": "whois.nic.tg",
  "tz": "whois.nic.tz",
  "ug": "whois.nic.ug",
  "zw": "whois.nic.zw",
  "zm": "whois.nic.zm",
  "mw": "whois.nic.mw",
  "mu": "whois.nic.mu",
  "mg": "whois.nic.mg",
  "na": "whois.nic.na",
  "bw": "whois.nic.bw",
  "sh": "whois.nic.sh",
  "ac": "whois.nic.ac",
  "re": "whois.nic.re",
  "yt": "whois.nic.yt",
  "tf": "whois.nic.tf",

  // ========== 新通用顶级域名 - 科技类 ==========
  "app": "whois.nic.google",
  "dev": "whois.nic.google",
  "page": "whois.nic.google",
  "new": "whois.nic.google",
  "how": "whois.nic.google",
  "soy": "whois.nic.google",
  "day": "whois.nic.google",
  "foo": "whois.nic.google",
  "zip": "whois.nic.google",
  "mov": "whois.nic.google",
  "dad": "whois.nic.google",
  "phd": "whois.nic.google",
  "prof": "whois.nic.google",
  "esq": "whois.nic.google",
  "nexus": "whois.nic.google",
  "google": "whois.nic.google",
  "gmail": "whois.nic.google",
  "youtube": "whois.nic.google",
  "android": "whois.nic.google",
  "chrome": "whois.nic.google",
  "docs": "whois.nic.google",
  "drive": "whois.nic.google",
  "hangout": "whois.nic.google",
  "map": "whois.nic.google",
  "meet": "whois.nic.google",
  "play": "whois.nic.google",
  "search": "whois.nic.google",
  "channel": "whois.nic.google",
  "ads": "whois.nic.google",
  "boo": "whois.nic.google",
  "cal": "whois.nic.google",
  "dclk": "whois.nic.google",
  "eat": "whois.nic.google",
  "fly": "whois.nic.google",
  "gbiz": "whois.nic.google",
  "gle": "whois.nic.google",
  "goog": "whois.nic.google",
  "guge": "whois.nic.google",
  "here": "whois.nic.google",
  "ing": "whois.nic.google",
  "meme": "whois.nic.google",
  "prod": "whois.nic.google",
  "rsvp": "whois.nic.google",
  "xyz": "whois.nic.xyz",
  "top": "whois.nic.top",
  "site": "whois.centralnic.com",
  "online": "whois.centralnic.com",
  "store": "whois.centralnic.com",
  "tech": "whois.centralnic.com",
  "host": "whois.centralnic.com",
  "fun": "whois.nic.fun",
  "space": "whois.nic.space",
  "press": "whois.centralnic.com",
  "website": "whois.centralnic.com",
  "wiki": "whois.nic.wiki",

  // ========== 新通用顶级域名 - 商业类 ==========
  "club": "whois.nic.club",
  "vip": "whois.nic.vip",
  "blog": "whois.nic.blog",
  "shop": "whois.nic.shop",
  "link": "whois.uniregistry.net",
  "live": "whois.donuts.co",
  "cloud": "whois.nic.cloud",
  "news": "whois.donuts.co",
  "world": "whois.donuts.co",
  "network": "whois.donuts.co",
  "design": "whois.nic.design",
  "works": "whois.donuts.co",
  "email": "whois.donuts.co",
  "media": "whois.donuts.co",
  "digital": "whois.donuts.co",
  "agency": "whois.donuts.co",
  "studio": "whois.donuts.co",
  "solutions": "whois.donuts.co",
  "group": "whois.donuts.co",
  "company": "whois.donuts.co",
  "global": "whois.nic.global",
  "money": "whois.donuts.co",
  "city": "whois.donuts.co",
  "life": "whois.donuts.co",
  "one": "whois.nic.one",
  "art": "whois.nic.art",
  "icu": "whois.nic.icu",
  "cyou": "whois.nic.cyou",
  "ltd": "whois.donuts.co",
  "inc": "whois.nic.inc",
  "llc": "whois.afilias.net",
  "gmbh": "whois.donuts.co",
  "center": "whois.donuts.co",
  "zone": "whois.donuts.co",
  "plus": "whois.donuts.co",
  "today": "whois.donuts.co",
  "best": "whois.nic.best",
  "win": "whois.nic.win",
  "run": "whois.donuts.co",
  "work": "whois.nic.work",
  "team": "whois.donuts.co",
  "expert": "whois.donuts.co",
  "ceo": "whois.nic.ceo",

  // ========== 新通用顶级域名 - 行业类 ==========
  "finance": "whois.donuts.co",
  "financial": "whois.donuts.co",
  "insurance": "whois.nic.insurance",
  "consulting": "whois.donuts.co",
  "marketing": "whois.donuts.co",
  "management": "whois.donuts.co",
  "property": "whois.donuts.co",
  "estate": "whois.donuts.co",
  "realty": "whois.donuts.co",
  "attorney": "whois.donuts.co",
  "lawyer": "whois.donuts.co",
  "legal": "whois.donuts.co",
  "law": "whois.nic.law",
  "accountant": "whois.nic.accountant",
  "accountants": "whois.donuts.co",
  "holdings": "whois.donuts.co",
  "enterprises": "whois.donuts.co",
  "capital": "whois.donuts.co",
  "fund": "whois.donuts.co",
  "investments": "whois.donuts.co",
  "cash": "whois.donuts.co",
  "tax": "whois.donuts.co",
  "loans": "whois.donuts.co",
  "credit": "whois.donuts.co",
  "creditcard": "whois.donuts.co",
  "mortgage": "whois.donuts.co",
  "dental": "whois.donuts.co",
  "clinic": "whois.donuts.co",
  "hospital": "whois.donuts.co",
  "surgery": "whois.donuts.co",
  "healthcare": "whois.donuts.co",
  "health": "whois.nic.health",
  "vet": "whois.donuts.co",
  "pharmacy": "whois.nic.pharmacy",
  "doctor": "whois.donuts.co",
  "dentist": "whois.donuts.co",
  "education": "whois.donuts.co",
  "school": "whois.donuts.co",
  "university": "whois.donuts.co",
  "college": "whois.centralnic.com",
  "academy": "whois.donuts.co",
  "training": "whois.donuts.co",
  "institute": "whois.donuts.co",
  "mba": "whois.donuts.co",
  "restaurant": "whois.donuts.co",
  "cafe": "whois.donuts.co",
  "catering": "whois.donuts.co",
  "pizza": "whois.donuts.co",
  "kitchen": "whois.donuts.co",
  "recipes": "whois.donuts.co",
  "menu": "whois.nic.menu",
  "bar": "whois.nic.bar",
  "pub": "whois.donuts.co",
  "wine": "whois.donuts.co",
  "beer": "whois.nic.beer",
  "coffee": "whois.donuts.co",
  "clothing": "whois.donuts.co",
  "fashion": "whois.nic.fashion",
  "boutique": "whois.donuts.co",
  "jewelry": "whois.donuts.co",
  "watches": "whois.donuts.co",
  "shoes": "whois.donuts.co",
  "diamonds": "whois.donuts.co",
  "beauty": "whois.nic.beauty",
  "hair": "whois.nic.hair",
  "salon": "whois.donuts.co",
  "spa": "whois.donuts.co",
  "fitness": "whois.donuts.co",
  "yoga": "whois.nic.yoga",
  "dance": "whois.donuts.co",
  "football": "whois.donuts.co",
  "soccer": "whois.donuts.co",
  "hockey": "whois.donuts.co",
  "golf": "whois.donuts.co",
  "tennis": "whois.donuts.co",
  "games": "whois.donuts.co",
  "game": "whois.centralnic.com",
  "casino": "whois.donuts.co",
  "bet": "whois.afilias.net",
  "poker": "whois.afilias.net",
  "dating": "whois.donuts.co",
  "singles": "whois.donuts.co",
  "wedding": "whois.nic.wedding",
  "flowers": "whois.centralnic.com",
  "gift": "whois.donuts.co",
  "gifts": "whois.donuts.co",
  "toys": "whois.donuts.co",
  "pet": "whois.afilias.net",
  "dog": "whois.donuts.co",
  "horse": "whois.nic.horse",
  "auto": "whois.centralnic.com",
  "car": "whois.centralnic.com",
  "cars": "whois.centralnic.com",
  "bike": "whois.donuts.co",
  "motorcycle": "whois.nic.motorcycle",
  "taxi": "whois.donuts.co",
  "repair": "whois.donuts.co",
  "parts": "whois.donuts.co",
  "tires": "whois.donuts.co",
  "house": "whois.donuts.co",
  "apartment": "whois.donuts.co",
  "condos": "whois.donuts.co",
  "villas": "whois.donuts.co",
  "land": "whois.donuts.co",
  "rent": "whois.centralnic.com",
  "rentals": "whois.donuts.co",
  "construction": "whois.donuts.co",
  "builders": "whois.donuts.co",
  "plumbing": "whois.donuts.co",
  "contractors": "whois.donuts.co",
  "glass": "whois.donuts.co",
  "lighting": "whois.donuts.co",
  "solar": "whois.donuts.co",
  "energy": "whois.donuts.co",
  "eco": "whois.afilias.net",
  "green": "whois.afilias.net",
  "bio": "whois.nic.bio",
  "organic": "whois.afilias.net",
  "farm": "whois.donuts.co",
  "garden": "whois.nic.garden",
  "haus": "whois.donuts.co",
  "florist": "whois.donuts.co",

  // ========== 新通用顶级域名 - 旅游/娱乐类 ==========
  "vacation": "whois.donuts.co",
  "vacations": "whois.donuts.co",
  "cruises": "whois.donuts.co",
  "flights": "whois.donuts.co",
  "holiday": "whois.donuts.co",
  "hotel": "whois.donuts.co",
  "hotels": "whois.nic.hotels",
  "hoteles": "whois.donuts.co",
  "tours": "whois.donuts.co",
  "viajes": "whois.donuts.co",
  "voyage": "whois.donuts.co",
  "camp": "whois.donuts.co",
  "fishing": "whois.nic.fishing",
  "ski": "whois.afilias.net",
  "surf": "whois.nic.surf",
  "events": "whois.donuts.co",
  "tickets": "whois.centralnic.com",
  "show": "whois.donuts.co",
  "theater": "whois.donuts.co",
  "theatre": "whois.centralnic.com",
  "movie": "whois.donuts.co",
  "film": "whois.nic.film",
  "music": "whois.nic.music",
  "audio": "whois.centralnic.com",
  "band": "whois.donuts.co",
  "gallery": "whois.donuts.co",
  "photography": "whois.donuts.co",
  "camera": "whois.donuts.co",
  "pictures": "whois.donuts.co",
  "photos": "whois.donuts.co",
  "video": "whois.donuts.co",

  // ========== 新通用顶级域名 - 城市/地区类 ==========
  "amsterdam": "whois.nic.amsterdam",
  "barcelona": "whois.nic.barcelona",
  "berlin": "whois.nic.berlin",
  "brussels": "whois.nic.brussels",
  "budapest": "whois.nic.budapest",
  "cologne": "whois.nic.cologne",
  "dubai": "whois.nic.dubai",
  "hamburg": "whois.nic.hamburg",
  "helsinki": "whois.nic.helsinki",
  "istanbul": "whois.nic.istanbul",
  "london": "whois.nic.london",
  "madrid": "whois.nic.madrid",
  "melbourne": "whois.nic.melbourne",
  "miami": "whois.nic.miami",
  "moscow": "whois.nic.moscow",
  "nyc": "whois.nic.nyc",
  "paris": "whois.nic.paris",
  "prague": "whois.nic.prague",
  "rio": "whois.nic.rio",
  "roma": "whois.nic.roma",
  "stockholm": "whois.nic.stockholm",
  "sydney": "whois.nic.sydney",
  "taipei": "whois.nic.taipei",
  "tokyo": "whois.nic.tokyo",
  "vegas": "whois.nic.vegas",
  "wien": "whois.nic.wien",
  "yokohama": "whois.nic.yokohama",
  "boston": "whois.nic.boston",
  "chicago": "whois.nic.chicago",
  "koeln": "whois.nic.koeln",
  "nrw": "whois.nic.nrw",
  "ruhr": "whois.nic.ruhr",
  "saarland": "whois.nic.saarland",
  "bayern": "whois.nic.bayern",
  "tirol": "whois.nic.tirol",
  "vlaanderen": "whois.nic.vlaanderen",
  "wales": "whois.nic.wales",
  "scot": "whois.nic.scot",
  "cymru": "whois.nic.cymru",
  "irish": "whois.nic.irish",
  "kiwi": "whois.nic.kiwi",
  "quebec": "whois.nic.quebec",
  "eus": "whois.nic.eus",
  "gal": "whois.nic.gal",
  "bzh": "whois.nic.bzh",
  "alsace": "whois.nic.alsace",
  "corsica": "whois.nic.corsica",
  "africa": "whois.nic.africa",
  "capetown": "whois.nic.capetown",
  "durban": "whois.nic.durban",
  "joburg": "whois.nic.joburg",
  "lat": "whois.nic.lat",
  "nagoya": "whois.nic.nagoya",
  "okinawa": "whois.nic.okinawa",
  "kyoto": "whois.nic.kyoto",
  "ryukyu": "whois.nic.ryukyu",

  // ========== 新通用顶级域名 - 其他常用 ==========
  "click": "whois.uniregistry.net",
  "domains": "whois.donuts.co",
  "earth": "whois.nic.earth",
  "international": "whois.donuts.co",
  "exchange": "whois.donuts.co",
  "express": "whois.donuts.co",
  "delivery": "whois.donuts.co",
  "supply": "whois.donuts.co",
  "supplies": "whois.donuts.co",
  "direct": "whois.donuts.co",
  "directory": "whois.donuts.co",
  "guide": "whois.donuts.co",
  "help": "whois.centralnic.com",
  "support": "whois.donuts.co",
  "tips": "whois.donuts.co",
  "tools": "whois.donuts.co",
  "watch": "whois.donuts.co",
  "review": "whois.nic.review",
  "reviews": "whois.donuts.co",
  "report": "whois.donuts.co",
  "buzz": "whois.nic.buzz",
  "cool": "whois.donuts.co",
  "fail": "whois.donuts.co",
  "guru": "whois.donuts.co",
  "ninja": "whois.donuts.co",
  "rocks": "whois.donuts.co",
  "sexy": "whois.donuts.co",
  "social": "whois.donuts.co",
  "community": "whois.donuts.co",
  "family": "whois.donuts.co",
  "kids": "whois.donuts.co",
  "baby": "whois.nic.baby",
  "mom": "whois.centralnic.com",
  "care": "whois.donuts.co",
  "love": "whois.nic.love",
  "faith": "whois.nic.faith",
  "church": "whois.donuts.co",
  "foundation": "whois.donuts.co",
  "charity": "whois.donuts.co",
  "giving": "whois.donuts.co",
  "science": "whois.nic.science",
  "engineering": "whois.donuts.co",
  "degree": "whois.donuts.co",
  "study": "whois.nic.study",
  "courses": "whois.nic.courses",
  "career": "whois.nic.career",
  "careers": "whois.donuts.co",
  "actor": "whois.donuts.co",
  "author": "whois.nic.author",
  "lol": "whois.centralnic.com",
  "wtf": "whois.donuts.co",
  "sucks": "whois.nic.sucks",
  "stream": "whois.nic.stream",
  "party": "whois.nic.party",
  "date": "whois.nic.date",
  "trade": "whois.nic.trade",
  "bid": "whois.nic.bid",
  "racing": "whois.nic.racing",
  "cricket": "whois.nic.cricket",
  "loan": "whois.nic.loan",
  "men": "whois.nic.men",
  "red": "whois.afilias.net",
  "blue": "whois.afilias.net",
  "pink": "whois.afilias.net",
  "gold": "whois.donuts.co",
  "black": "whois.afilias.net",
  "orange": "whois.nic.orange",
  "town": "whois.donuts.co",
  "download": "whois.nic.download",
  "webcam": "whois.nic.webcam",
  "ink": "whois.nic.ink",
  "luxe": "whois.nic.luxe",
  "moe": "whois.nic.moe",
  "monster": "whois.centralnic.com",
  "ooo": "whois.centralnic.com",
  "pics": "whois.centralnic.com",
  "quest": "whois.centralnic.com",
  "skin": "whois.centralnic.com",
  "storage": "whois.centralnic.com",
  "uno": "whois.centralnic.com",
  "voting": "whois.nic.voting",
  "vodka": "whois.nic.vodka",
  "wang": "whois.nic.wang",
  "ren": "whois.nic.ren",

  // ========== 品牌TLDs ==========
  "amazon": "whois.nic.amazon",
  "apple": "whois.nic.apple",
  "aws": "whois.nic.aws",
  "microsoft": "whois.nic.microsoft",
  "alibaba": "whois.nic.alibaba",
  "alipay": "whois.nic.alipay",
  "taobao": "whois.nic.taobao",
  "tmall": "whois.nic.tmall",
  "baidu": "whois.nic.baidu",
  "tencent": "whois.nic.tencent",
  "weibo": "whois.nic.weibo",
  "samsung": "whois.nic.samsung",
  "audi": "whois.nic.audi",
  "bmw": "whois.nic.bmw",
  "mini": "whois.nic.mini",
  "ferrari": "whois.nic.ferrari",
  "honda": "whois.nic.honda",
  "hyundai": "whois.nic.hyundai",
  "kia": "whois.nic.kia",
  "lexus": "whois.nic.lexus",
  "nissan": "whois.nic.nissan",
  "toyota": "whois.nic.toyota",
  "volkswagen": "whois.nic.volkswagen",
  "volvo": "whois.nic.volvo",
  "dell": "whois.nic.dell",
  "intel": "whois.nic.intel",
  "cisco": "whois.nic.cisco",
  "oracle": "whois.nic.oracle",
  "sap": "whois.nic.sap",
  "ibm": "whois.nic.ibm",
  "hsbc": "whois.nic.hsbc",
  "jpmorgan": "whois.nic.jpmorgan",
  "chase": "whois.nic.chase",
  "citi": "whois.nic.citi",
  "visa": "whois.nic.visa",
  "amex": "whois.nic.amex",
  "netflix": "whois.nic.netflix",
  "spotify": "whois.nic.spotify",
  "nba": "whois.nic.nba",
  "nfl": "whois.nic.nfl",
  "nike": "whois.nic.nike",
  "adidas": "whois.nic.adidas",
  "gucci": "whois.nic.gucci",
  "hermes": "whois.nic.hermes",
  "chanel": "whois.nic.chanel",
  "cartier": "whois.nic.cartier",
  "rolex": "whois.nic.rolex",
  "omega": "whois.nic.omega",
  "sony": "whois.nic.sony",
  "philips": "whois.nic.philips",
  "panasonic": "whois.nic.panasonic",
  "canon": "whois.nic.canon",
  "nikon": "whois.nic.nikon",
  "xerox": "whois.nic.xerox",
  "shell": "whois.nic.shell",
  "total": "whois.nic.total",
  "dupont": "whois.nic.dupont",
  "lego": "whois.nic.lego",
  "ikea": "whois.nic.ikea",
  "booking": "whois.nic.booking",
  "marriott": "whois.nic.marriott",
  "hyatt": "whois.nic.hyatt",
  "mcd": "whois.nic.mcd",
  "mcdonalds": "whois.nic.mcdonalds",
  "kfc": "whois.nic.kfc",
  "starbucks": "whois.nic.starbucks",
  "subway": "whois.nic.subway",
  "suzuki": "whois.nic.suzuki",
  "toray": "whois.nic.toray",
  "toshiba": "whois.nic.toshiba",
  "bridgestone": "whois.nic.bridgestone",
  "brother": "whois.nic.brother",
  "epson": "whois.nic.epson",
  "firestone": "whois.nic.firestone",
  "fujitsu": "whois.nic.fujitsu",
  "hitachi": "whois.nic.hitachi",
  "jcb": "whois.nic.jcb",
  "kddi": "whois.nic.kddi",
  "komatsu": "whois.nic.komatsu",
  "lotte": "whois.nic.lotte",
  "mitsubishi": "whois.nic.mitsubishi",
  "nec": "whois.nic.nec",
  "nhk": "whois.nic.nhk",
  "nico": "whois.nic.nico",
  "otsuka": "whois.nic.otsuka",
  "playstation": "whois.nic.playstation",
  "ricoh": "whois.nic.ricoh",
  "sharp": "whois.nic.sharp",
  "softbank": "whois.nic.softbank",
  "yodobashi": "whois.nic.yodobashi",
  "ford": "whois.nic.ford",
  "lincoln": "whois.nic.lincoln",
  "fox": "whois.nic.fox",
  "hbo": "whois.nic.hbo",
  "walmart": "whois.nic.walmart",
  "target": "whois.nic.target",
  "staples": "whois.nic.staples",
  "grainger": "whois.nic.grainger",
  "intuit": "whois.nic.intuit",
  "godaddy": "whois.nic.godaddy",
  "deloitte": "whois.nic.deloitte",
  "kpmg": "whois.nic.kpmg",
  "dhl": "whois.nic.dhl",
  "fedex": "whois.nic.fedex",
  "ups": "whois.nic.ups",
  "bbc": "whois.nic.bbc",
  "cern": "whois.nic.cern",

  // ========== IDN TLDs (国际化域名) ==========
  // 中文
  "xn--fiqs8s": "whois.cnnic.cn", // 中国
  "xn--fiqz9s": "whois.cnnic.cn", // 中國
  "xn--j6w193g": "whois.hkirc.hk", // 香港
  "xn--kprw13d": "whois.twnic.net.tw", // 台灣
  "xn--kpry57d": "whois.twnic.net.tw", // 台湾
  "xn--55qx5d": "whois.ngtld.cn", // 公司
  "xn--io0a7i": "whois.ngtld.cn", // 网络
  "xn--1qqw23a": "whois.ngtld.cn", // 佛山
  "xn--xhq521b": "whois.ngtld.cn", // 广东
  "xn--czru2d": "whois.gtld.knet.cn", // 商城
  "xn--czr694b": "whois.gtld.knet.cn", // 商标
  "xn--zfr164b": "whois.gtld.knet.cn", // 商店
  "xn--ses554g": "whois.gtld.knet.cn", // 网址
  "xn--efvy88h": "whois.gtld.knet.cn", // 新闻
  "xn--vuq861b": "whois.gtld.knet.cn", // 信息
  "xn--3bst00m": "whois.gtld.knet.cn", // 集团
  "xn--9et52u": "whois.gtld.knet.cn", // 时尚
  "xn--fiq228c5hs": "whois.gtld.knet.cn", // 中信
  "xn--6frz82g": "whois.nic.xn--6frz82g", // 移动
  "xn--nyqy26a": "whois.stable.nic.xn--nyqy26a", // 健康
  "xn--rhqv96g": "whois.nic.xn--rhqv96g", // 世界
  "xn--fiq64b": "whois.gtld.knet.cn", // 中文网
  "xn--fjq720a": "whois.nic.xn--fjq720a", // 娱乐
  "xn--otu796d": "whois.gtld.knet.cn", // 招聘
  "xn--5tzm5g": "whois.gtld.knet.cn", // 网站
  "xn--45q11c": "whois.gtld.knet.cn", // 八卦
  "xn--czrs0t": "whois.gtld.knet.cn", // 商业
  "xn--6qq986b3xl": "whois.gtld.knet.cn", // 我爱你
  "xn--kput3i": "whois.gtld.knet.cn", // 手机
  "xn--yfro4i67o": "whois.sgnic.sg", // 新加坡
  "xn--mix891f": "whois.monic.mo", // 澳門

  // 韩文
  "xn--3e0b707e": "whois.kr", // 한국
  "xn--t60b56a": "whois.kr", // 닷컴
  "xn--o39aa": "whois.kr", // 닷넷
  "xn--cg4bki": "whois.kr", // 삼성

  // 日文
  "xn--q9jyb4c": "whois.nic.google", // みんな
  "xn--gk3at1e": "whois.nic.xn--gk3at1e", // コム
  "xn--gckr3f0f": "whois.nic.xn--gckr3f0f", // ストア

  // 阿拉伯文
  "xn--mgberp4a5d4ar": "whois.nic.net.sa", // السعودية (沙特)
  "xn--wgbl6a": "whois.registry.qa", // قطر (卡塔尔)
  "xn--wgbh1c": "whois.nic.eg", // مصر (埃及)
  "xn--mgbtf8fl": "whois.tld.sy", // سوريا (叙利亚)
  "xn--pgbs0dh": "whois.ati.tn", // تونس (突尼斯)
  "xn--mgbaam7a8h": "whois.aeda.net.ae", // امارات (阿联酋)
  "xn--ygbi2ammx": "whois.pnina.ps", // فلسطين (巴勒斯坦)
  "xn--mgbai9azgqp6j": "whois.pknic.net.pk", // پاکستان (巴基斯坦)
  "xn--mgba3a4f16a": "whois.nic.ir", // ایران (伊朗)
  "xn--mgb9awbf": "whois.registry.om", // عمان (阿曼)
  "xn--mgbx4cd0ab": "whois.mynic.my", // مليسيا (马来西亚)
  "xn--lgbbat1ad8j": "whois.nic.dz", // الجزائر (阿尔及利亚)
  "xn--mgb2ddes": "whois.y.net.ye", // اليمن (也门)
  "xn--ngbc5azd": "whois.nic.xn--ngbc5azd", // شبكة (阿拉伯网络)

  // 俄罗斯/斯拉夫文
  "xn--90a3ac": "whois.rnids.rs", // срб (塞尔维亚)
  "xn--j1amh": "whois.ua", // укр (乌克兰)
  "xn--p1ai": "whois.tcinet.ru", // рф (俄罗斯)
  "xn--90ae": "whois.register.bg", // бг (保加利亚)
  "xn--80ao21a": "whois.nic.kz", // қаз (哈萨克斯坦)
  "xn--d1alf": "whois.marnet.mk", // мкд (马其顿)
  "xn--80adxhks": "whois.nic.moscow", // москва (莫斯科)
  "xn--c1avg": "whois.nic.xn--c1avg", // орг (俄文org)
  "xn--p1acf": "whois.nic.xn--p1acf", // рус (俄文rus)
  "xn--80aswg": "whois.nic.xn--80aswg", // сайт (俄文site)
  "xn--y9a3aq": "whois.amnic.net", // հայ (亚美尼亚)

  // 希腊文
  "xn--qxam": "whois.ics.forth.gr", // ελ (希腊)
  "xn--e1a4c": "whois.eu", // ею (欧盟俄文)

  // 印度文
  "xn--h2brj9c": "whois.registry.in", // भारत (印地语印度)
  "xn--45brj9c": "whois.registry.in", // ভারত (孟加拉语印度)
  "xn--gecrj9c": "whois.registry.in", // ભારત (古吉拉特语印度)
  "xn--s9brj9c": "whois.registry.in", // ਭਾਰਤ (旁遮普语印度)
  "xn--xkc2dl3a5ee0h": "whois.registry.in", // இந்தியா (泰米尔语印度)
  "xn--rvc1e0am3e": "whois.registry.in", // ഭാരതം (马拉雅拉姆语印度)
  "xn--fpcrj9c3d": "whois.registry.in", // భారత్ (泰卢固语印度)
  "xn--3hcrj9c": "whois.registry.in", // ভাৰত (阿萨姆语印度)
  "xn--mgbbh1a71e": "whois.registry.in", // بھارت (乌尔都语印度)
  "xn--2scrj9c": "whois.registry.in", // ಭಾರತ (卡纳达语印度)

  // 泰文
  "xn--o3cw4h": "whois.thnic.co.th", // ไทย (泰国)

  // 格鲁吉亚
  "xn--node": "whois.nic.ge", // გე (格鲁吉亚)

  // 以色列希伯来文
  "xn--4dbrk0ce": "whois.isoc.org.il", // ישראל (以色列)

  // 斯里兰卡
  "xn--fzc2c9e2c": "whois.nic.lk", // ලංකා (僧伽罗语斯里兰卡)
  "xn--xkc2al3hye2a": "whois.nic.lk", // இலங்கை (泰米尔语斯里兰卡)

  // 蒙古
  "xn--l1acc": "whois.nic.mn", // мон (蒙古)
};

// RDAP服务器映射 - 基于IANA官方Bootstrap文件 (2026-02-04)
// https://data.iana.org/rdap/dns.json
export const RDAP_SERVERS: Record<string, string> = {
  // ========== 主要gTLDs ==========
  "com": "https://rdap.verisign.com/com/v1",
  "net": "https://rdap.verisign.com/net/v1",
  "org": "https://rdap.publicinterestregistry.org/rdap",
  "info": "https://rdap.identitydigital.services/rdap",
  "biz": "https://rdap.nic.biz",
  "name": "https://tld-rdap.verisign.com/name/v1",
  "mobi": "https://rdap.identitydigital.services/rdap",
  "asia": "https://rdap.identitydigital.services/rdap",
  "tel": "https://rdap.nic.tel",
  "jobs": "https://rdap.nominet.uk/jobs",
  "xxx": "https://rdap.nic.xxx",
  "cat": "https://rdap.nic.cat",
  "pro": "https://rdap.identitydigital.services/rdap",
  "aero": "https://rdap.identitydigital.services/rdap",
  "coop": "https://rdap.registry.coop/rdap",
  "museum": "https://rdap.nic.museum",
  "post": "https://rdap.identitydigital.services/rdap",
  "travel": "https://rdap.identitydigital.services/rdap",
  "int": "https://rdap.iana.org",
  "gov": "https://rdap.nic.gov/rdap",

  // ========== ccTLDs - 欧洲 ==========
  "uk": "https://rdap.nominet.uk/uk",
  "de": "https://rdap.denic.de",
  "fr": "https://rdap.nic.fr",
  "eu": "https://rdap.eurid.eu",
  "nl": "https://rdap.sidn.nl",
  "be": "https://rdap.dns.be",
  "ch": "https://rdap.nic.ch",
  "at": "https://rdap.nic.at",
  "se": "https://rdap.iis.se",
  "no": "https://rdap.norid.no",
  "dk": "https://rdap.dk-hostmaster.dk",
  "fi": "https://rdap.fi/rdap/rdap",
  "pl": "https://rdap.dns.pl",
  "cz": "https://rdap.nic.cz",
  "ie": "https://rdap.iedr.ie",
  "it": "https://rdap.nic.it",
  "es": "https://rdap.nic.es",
  "pt": "https://rdap.dns.pt",
  "ee": "https://rdap.tld.ee",
  "lv": "https://rdap.nic.lv",
  "lt": "https://rdap.domreg.lt",
  "hr": "https://rdap.dns.hr",
  "si": "https://rdap.register.si",
  "rs": "https://rdap.rnids.rs",
  "ua": "https://rdap.hostmaster.ua",
  "is": "https://rdap.isnic.is/rdap",
  "ad": "https://rdap.nic.ad",
  "fo": "https://rdap.centralnic.com/fo",

  // ========== ccTLDs - 亚洲 ==========
  "jp": "https://rdap.jprs.jp",
  "kr": "https://rdap.kisa.or.kr",
  "cn": "https://rdap.cnnic.cn",
  "tw": "https://ccrdap.twnic.tw/tw",
  "hk": "https://rdap.hkirc.hk",
  "sg": "https://rdap.sgnic.sg/rdap",
  "th": "https://rdap.thains.co.th",
  "vn": "https://rdap.vnnic.vn",
  "id": "https://rdap.pandi.id/rdap",
  "my": "https://rdap.mynic.my",
  "ph": "https://rdap.dot.ph",
  "in": "https://rdap.nixiregistry.in/rdap",
  "kg": "https://rdap.cctld.kg",
  "uz": "https://rdap.cctld.uz",
  "lb": "https://rdap.lbdr.org.lb",

  // ========== ccTLDs - 中东 ==========
  "ae": "https://rdap.aeda.net.ae",
  "sa": "https://rdap.nic.net.sa",
  "qa": "https://rdap.registry.qa",
  "il": "https://rdap.isoc.org.il",

  // ========== ccTLDs - 大洋洲 ==========
  "au": "https://rdap.cctld.au/rdap",
  "nz": "https://rdap.nzrs.nz",
  "fj": "https://www.rdap.fj",
  "to": "https://rdap.tonicregistry.to/rdap",
  "fm": "https://rdap.centralnic.com/fm",
  "pw": "https://rdap.radix.host/rdap",
  "tv": "https://rdap.nic.tv",
  "cx": "https://rdap.nic.cx",
  "ky": "https://whois.kyregistry.ky/rdap",
  "nu": "https://rdap.iis.nu",

  // ========== ccTLDs - 美洲 ==========
  "ca": "https://rdap.ca.fury.ca/rdap",
  "br": "https://rdap.registro.br",
  "mx": "https://rdap.mx",
  "us": "https://rdap.nic.us",
  "ar": "https://rdap.nic.ar",
  "cl": "https://rdap.nic.cl",
  "ec": "https://rdap.registry.ec",
  "cr": "https://rdap.nic.cr",
  "gy": "https://rdap.registry.gy",
  "hn": "https://rdap.nic.hn",
  "ht": "https://rdap.nic.ht",
  "sr": "https://whois.sr/rdap",
  "cv": "https://rdap.nic.cv",
  "ms": "https://rdap.nic.ms",
  "gs": "https://rdap.nic.gs",
  "vi": "https://rdap.nic.vi",
  "vg": "https://rdap.centralnic.com/vg",
  "gd": "https://rdap.centralnic.com/gd",

  // ========== ccTLDs - 非洲 ==========
  "za": "https://rdap.registry.net.za",
  "ke": "https://rdap.kenic.or.ke",
  "ng": "http://rdap.nic.net.ng",
  "mg": "http://rdap.nic.mg",
  "tz": "https://whois.tznic.or.tz/rdap",
  "rw": "https://rdap.ricta.org.rw",
  "zm": "https://rdap.nic.zm",
  "ly": "https://rdap.nic.ly",
  "ml": "https://rdap.nic.ml",
  "cm": "https://rdap.nic.cm",
  "ss": "https://rdap.nic.ss",
  "na": "https://keetmans.omadhina.co.na",
  "ye": "https://rdap.y.net.ye",

  // ========== ccTLDs - 其他 ==========
  "io": "https://rdap.nic.io",
  "co": "https://rdap.nic.co",
  "me": "https://rdap.nic.me",
  "cc": "https://tld-rdap.verisign.com/cc/v1",
  "ai": "https://rdap.identitydigital.services/rdap",
  "gg": "https://rdap.nic.gg",
  "je": "https://rdap.nic.je",
  "im": "https://rdap.nic.im",
  "la": "https://rdap.nic.la",
  "ws": "https://rdap.website.ws",
  "so": "https://rdap.nic.so",
  "sh": "https://rdap.nic.sh",
  "ac": "https://rdap.nic.ac",
  "sc": "https://rdap.nic.sc",
  "as": "https://rdap.nic.as",
  "tc": "https://rdap.nic.tc",
  "vc": "https://rdap.nic.vc",
  "dm": "https://rdap.nic.dm",
  "ag": "https://rdap.nic.ag",
  "bm": "https://rdap.identitydigital.services/rdap",
  "mu": "https://rdap.identitydigital.services/rdap",
  "wf": "https://rdap.nic.wf",
  "yt": "https://rdap.nic.yt",
  "tf": "https://rdap.nic.tf",
  "pn": "https://rdap.nominet.uk/pn",

  // ========== Google gTLDs ==========
  "ads": "https://pubapi.registry.google/rdap",
  "android": "https://pubapi.registry.google/rdap",
  "app": "https://pubapi.registry.google/rdap",
  "boo": "https://pubapi.registry.google/rdap",
  "cal": "https://pubapi.registry.google/rdap",
  "channel": "https://pubapi.registry.google/rdap",
  "chrome": "https://pubapi.registry.google/rdap",
  "dad": "https://pubapi.registry.google/rdap",
  "day": "https://pubapi.registry.google/rdap",
  "dclk": "https://pubapi.registry.google/rdap",
  "dev": "https://pubapi.registry.google/rdap",
  "docs": "https://pubapi.registry.google/rdap",
  "drive": "https://pubapi.registry.google/rdap",
  "eat": "https://pubapi.registry.google/rdap",
  "esq": "https://pubapi.registry.google/rdap",
  "fly": "https://pubapi.registry.google/rdap",
  "foo": "https://pubapi.registry.google/rdap",
  "gbiz": "https://pubapi.registry.google/rdap",
  "gle": "https://pubapi.registry.google/rdap",
  "gmail": "https://pubapi.registry.google/rdap",
  "goog": "https://pubapi.registry.google/rdap",
  "google": "https://pubapi.registry.google/rdap",
  "guge": "https://pubapi.registry.google/rdap",
  "hangout": "https://pubapi.registry.google/rdap",
  "here": "https://pubapi.registry.google/rdap",
  "how": "https://pubapi.registry.google/rdap",
  "ing": "https://pubapi.registry.google/rdap",
  "map": "https://pubapi.registry.google/rdap",
  "meet": "https://pubapi.registry.google/rdap",
  "meme": "https://pubapi.registry.google/rdap",
  "mov": "https://pubapi.registry.google/rdap",
  "new": "https://pubapi.registry.google/rdap",
  "nexus": "https://pubapi.registry.google/rdap",
  "page": "https://pubapi.registry.google/rdap",
  "phd": "https://pubapi.registry.google/rdap",
  "play": "https://pubapi.registry.google/rdap",
  "prod": "https://pubapi.registry.google/rdap",
  "prof": "https://pubapi.registry.google/rdap",
  "rsvp": "https://pubapi.registry.google/rdap",
  "search": "https://pubapi.registry.google/rdap",
  "soy": "https://pubapi.registry.google/rdap",
  "youtube": "https://pubapi.registry.google/rdap",
  "zip": "https://pubapi.registry.google/rdap",
  "xn--flw351e": "https://pubapi.registry.google/rdap",
  "xn--q9jyb4c": "https://pubapi.registry.google/rdap",
  "xn--qcka1pmc": "https://pubapi.registry.google/rdap",

  // ========== CentralNic gTLDs ==========
  "allfinanz": "https://rdap.centralnic.com/allfinanz",
  "art": "https://rdap.centralnic.com/art",
  "audio": "https://rdap.centralnic.com/audio",
  "auto": "https://rdap.centralnic.com/auto",
  "autos": "https://rdap.centralnic.com/autos",
  "baby": "https://rdap.centralnic.com/baby",
  "beauty": "https://rdap.centralnic.com/beauty",
  "best": "https://rdap.centralnic.com/best",
  "bmw": "https://rdap.centralnic.com/bmw",
  "boats": "https://rdap.centralnic.com/boats",
  "bond": "https://rdap.centralnic.com/bond",
  "box": "https://rdap.centralnic.com/box",
  "build": "https://rdap.centralnic.com/build",
  "cam": "https://rdap.centralnic.com/cam",
  "car": "https://rdap.centralnic.com/car",
  "cars": "https://rdap.centralnic.com/cars",
  "case": "https://rdap.centralnic.com/case",
  "ceo": "https://rdap.centralnic.com/ceo",
  "cfd": "https://rdap.centralnic.com/cfd",
  "christmas": "https://rdap.centralnic.com/christmas",
  "college": "https://rdap.centralnic.com/college",
  "cyou": "https://rdap.centralnic.com/cyou",
  "dealer": "https://rdap.centralnic.com/dealer",
  "diet": "https://rdap.centralnic.com/diet",
  "fans": "https://rdap.centralnic.com/fans",
  "flowers": "https://rdap.centralnic.com/flowers",
  "frl": "https://rdap.centralnic.com/frl",
  "fun": "https://rdap.radix.host/rdap",
  "game": "https://rdap.centralnic.com/game",
  "gent": "https://rdap.centralnic.com/gent",
  "guitars": "https://rdap.centralnic.com/guitars",
  "hair": "https://rdap.centralnic.com/hair",
  "help": "https://rdap.centralnic.com/help",
  "homes": "https://rdap.centralnic.com/homes",
  "host": "https://rdap.centralnic.com/host",
  "hosting": "https://rdap.centralnic.com/hosting",
  "icu": "https://rdap.centralnic.com/icu",
  "inc": "https://rdap.centralnic.com/inc",
  "kred": "https://rdap.centralnic.com/kred",
  "lat": "https://rdap.centralnic.com/lat",
  "llp": "https://rdap.centralnic.com/llp",
  "lol": "https://rdap.centralnic.com/lol",
  "london": "https://rdap.centralnic.com/london",
  "luxury": "https://rdap.centralnic.com/luxury",
  "makeup": "https://rdap.centralnic.com/makeup",
  "mini": "https://rdap.centralnic.com/mini",
  "mom": "https://rdap.centralnic.com/mom",
  "monster": "https://rdap.centralnic.com/monster",
  "motorcycles": "https://rdap.centralnic.com/motorcycles",
  "online": "https://rdap.radix.host/rdap",
  "ooo": "https://rdap.centralnic.com/ooo",
  "pics": "https://rdap.centralnic.com/pics",
  "press": "https://rdap.centralnic.com/press",
  "protection": "https://rdap.centralnic.com/protection",
  "qpon": "https://rdap.centralnic.com/qpon",
  "quest": "https://rdap.centralnic.com/quest",
  "reit": "https://rdap.centralnic.com/reit",
  "rent": "https://rdap.centralnic.com/rent",
  "ruhr": "https://rdap.centralnic.com/ruhr",
  "saarland": "https://rdap.centralnic.com/saarland",
  "sbs": "https://rdap.centralnic.com/sbs",
  "security": "https://rdap.centralnic.com/security",
  "site": "https://rdap.radix.host/rdap",
  "skin": "https://rdap.centralnic.com/skin",
  "smart": "https://rdap.centralnic.com/smart",
  "space": "https://rdap.radix.host/rdap",
  "storage": "https://rdap.centralnic.com/storage",
  "store": "https://rdap.radix.host/rdap",
  "tech": "https://rdap.radix.host/rdap",
  "theatre": "https://rdap.centralnic.com/theatre",
  "tickets": "https://rdap.centralnic.com/tickets",
  "uno": "https://rdap.centralnic.com/uno",
  "website": "https://rdap.centralnic.com/website",
  "xyz": "https://rdap.centralnic.com/xyz",
  "yachts": "https://rdap.centralnic.com/yachts",
  "zuerich": "https://rdap.centralnic.com/zuerich",
  "xn--4gbrim": "https://rdap.centralnic.com/xn--4gbrim",
  "xn--ngbe9e0a": "https://rdap.centralnic.com/xn--ngbe9e0a",
  "xn--vermgensberater-ctb": "https://rdap.centralnic.com/xn--vermgensberater-ctb",
  "xn--vermgensberatung-pwb": "https://rdap.centralnic.com/xn--vermgensberatung-pwb",

  // ========== Identity Digital gTLDs ==========
  "abb": "https://rdap.identitydigital.services/rdap",
  "abbott": "https://rdap.identitydigital.services/rdap",
  "abc": "https://rdap.identitydigital.services/rdap",
  "academy": "https://rdap.identitydigital.services/rdap",
  "accenture": "https://rdap.identitydigital.services/rdap",
  "accountants": "https://rdap.identitydigital.services/rdap",
  "actor": "https://rdap.identitydigital.services/rdap",
  "agency": "https://rdap.identitydigital.services/rdap",
  "apartments": "https://rdap.identitydigital.services/rdap",
  "archi": "https://rdap.identitydigital.services/rdap",
  "associates": "https://rdap.identitydigital.services/rdap",
  "attorney": "https://rdap.identitydigital.services/rdap",
  "auction": "https://rdap.identitydigital.services/rdap",
  "band": "https://rdap.identitydigital.services/rdap",
  "bargains": "https://rdap.identitydigital.services/rdap",
  "bet": "https://rdap.identitydigital.services/rdap",
  "bike": "https://rdap.identitydigital.services/rdap",
  "bingo": "https://rdap.identitydigital.services/rdap",
  "bio": "https://rdap.identitydigital.services/rdap",
  "black": "https://rdap.identitydigital.services/rdap",
  "blue": "https://rdap.identitydigital.services/rdap",
  "boutique": "https://rdap.identitydigital.services/rdap",
  "broker": "https://rdap.identitydigital.services/rdap",
  "builders": "https://rdap.identitydigital.services/rdap",
  "business": "https://rdap.identitydigital.services/rdap",
  "cab": "https://rdap.identitydigital.services/rdap",
  "cafe": "https://rdap.identitydigital.services/rdap",
  "camera": "https://rdap.identitydigital.services/rdap",
  "camp": "https://rdap.identitydigital.services/rdap",
  "capital": "https://rdap.identitydigital.services/rdap",
  "cards": "https://rdap.identitydigital.services/rdap",
  "care": "https://rdap.identitydigital.services/rdap",
  "careers": "https://rdap.identitydigital.services/rdap",
  "cash": "https://rdap.identitydigital.services/rdap",
  "casino": "https://rdap.identitydigital.services/rdap",
  "catering": "https://rdap.identitydigital.services/rdap",
  "center": "https://rdap.identitydigital.services/rdap",
  "chat": "https://rdap.identitydigital.services/rdap",
  "cheap": "https://rdap.identitydigital.services/rdap",
  "church": "https://rdap.identitydigital.services/rdap",
  "city": "https://rdap.identitydigital.services/rdap",
  "claims": "https://rdap.identitydigital.services/rdap",
  "cleaning": "https://rdap.identitydigital.services/rdap",
  "clinic": "https://rdap.identitydigital.services/rdap",
  "clothing": "https://rdap.identitydigital.services/rdap",
  "coach": "https://rdap.identitydigital.services/rdap",
  "codes": "https://rdap.identitydigital.services/rdap",
  "coffee": "https://rdap.identitydigital.services/rdap",
  "community": "https://rdap.identitydigital.services/rdap",
  "company": "https://rdap.identitydigital.services/rdap",
  "computer": "https://rdap.identitydigital.services/rdap",
  "condos": "https://rdap.identitydigital.services/rdap",
  "construction": "https://rdap.identitydigital.services/rdap",
  "consulting": "https://rdap.identitydigital.services/rdap",
  "contact": "https://rdap.identitydigital.services/rdap",
  "contractors": "https://rdap.identitydigital.services/rdap",
  "cool": "https://rdap.identitydigital.services/rdap",
  "coupons": "https://rdap.identitydigital.services/rdap",
  "credit": "https://rdap.identitydigital.services/rdap",
  "creditcard": "https://rdap.identitydigital.services/rdap",
  "cruises": "https://rdap.identitydigital.services/rdap",
  "dance": "https://rdap.identitydigital.services/rdap",
  "dating": "https://rdap.identitydigital.services/rdap",
  "deals": "https://rdap.identitydigital.services/rdap",
  "degree": "https://rdap.identitydigital.services/rdap",
  "delivery": "https://rdap.identitydigital.services/rdap",
  "democrat": "https://rdap.identitydigital.services/rdap",
  "dental": "https://rdap.identitydigital.services/rdap",
  "dentist": "https://rdap.identitydigital.services/rdap",
  "diamonds": "https://rdap.identitydigital.services/rdap",
  "digital": "https://rdap.identitydigital.services/rdap",
  "direct": "https://rdap.identitydigital.services/rdap",
  "directory": "https://rdap.identitydigital.services/rdap",
  "discount": "https://rdap.identitydigital.services/rdap",
  "doctor": "https://rdap.identitydigital.services/rdap",
  "dog": "https://rdap.identitydigital.services/rdap",
  "domains": "https://rdap.identitydigital.services/rdap",
  "education": "https://rdap.identitydigital.services/rdap",
  "email": "https://rdap.identitydigital.services/rdap",
  "energy": "https://rdap.identitydigital.services/rdap",
  "engineer": "https://rdap.identitydigital.services/rdap",
  "engineering": "https://rdap.identitydigital.services/rdap",
  "enterprises": "https://rdap.identitydigital.services/rdap",
  "equipment": "https://rdap.identitydigital.services/rdap",
  "estate": "https://rdap.identitydigital.services/rdap",
  "events": "https://rdap.identitydigital.services/rdap",
  "exchange": "https://rdap.identitydigital.services/rdap",
  "expert": "https://rdap.identitydigital.services/rdap",
  "exposed": "https://rdap.identitydigital.services/rdap",
  "express": "https://rdap.identitydigital.services/rdap",
  "fail": "https://rdap.identitydigital.services/rdap",
  "family": "https://rdap.identitydigital.services/rdap",
  "fan": "https://rdap.identitydigital.services/rdap",
  "farm": "https://rdap.identitydigital.services/rdap",
  "finance": "https://rdap.identitydigital.services/rdap",
  "financial": "https://rdap.identitydigital.services/rdap",
  "fish": "https://rdap.identitydigital.services/rdap",
  "fitness": "https://rdap.identitydigital.services/rdap",
  "flights": "https://rdap.identitydigital.services/rdap",
  "florist": "https://rdap.identitydigital.services/rdap",
  "football": "https://rdap.identitydigital.services/rdap",
  "forex": "https://rdap.identitydigital.services/rdap",
  "forsale": "https://rdap.identitydigital.services/rdap",
  "fund": "https://rdap.identitydigital.services/rdap",
  "furniture": "https://rdap.identitydigital.services/rdap",
  "futbol": "https://rdap.identitydigital.services/rdap",
  "fyi": "https://rdap.identitydigital.services/rdap",
  "gallery": "https://rdap.identitydigital.services/rdap",
  "games": "https://rdap.identitydigital.services/rdap",
  "gifts": "https://rdap.identitydigital.services/rdap",
  "glass": "https://rdap.identitydigital.services/rdap",
  "global": "https://rdap.identitydigital.services/rdap",
  "gmbh": "https://rdap.identitydigital.services/rdap",
  "gold": "https://rdap.identitydigital.services/rdap",
  "golf": "https://rdap.identitydigital.services/rdap",
  "graphics": "https://rdap.identitydigital.services/rdap",
  "gratis": "https://rdap.identitydigital.services/rdap",
  "green": "https://rdap.identitydigital.services/rdap",
  "gripe": "https://rdap.identitydigital.services/rdap",
  "group": "https://rdap.identitydigital.services/rdap",
  "guide": "https://rdap.identitydigital.services/rdap",
  "guru": "https://rdap.identitydigital.services/rdap",
  "haus": "https://rdap.identitydigital.services/rdap",
  "healthcare": "https://rdap.identitydigital.services/rdap",
  "hockey": "https://rdap.identitydigital.services/rdap",
  "holdings": "https://rdap.identitydigital.services/rdap",
  "holiday": "https://rdap.identitydigital.services/rdap",
  "hospital": "https://rdap.identitydigital.services/rdap",
  "house": "https://rdap.identitydigital.services/rdap",
  "immo": "https://rdap.identitydigital.services/rdap",
  "immobilien": "https://rdap.identitydigital.services/rdap",
  "industries": "https://rdap.identitydigital.services/rdap",
  "institute": "https://rdap.identitydigital.services/rdap",
  "insure": "https://rdap.identitydigital.services/rdap",
  "international": "https://rdap.identitydigital.services/rdap",
  "investments": "https://rdap.identitydigital.services/rdap",
  "irish": "https://rdap.identitydigital.services/rdap",
  "jetzt": "https://rdap.identitydigital.services/rdap",
  "jewelry": "https://rdap.identitydigital.services/rdap",
  "kaufen": "https://rdap.identitydigital.services/rdap",
  "kids": "https://rdap.identitydigital.services/rdap",
  "kim": "https://rdap.identitydigital.services/rdap",
  "kitchen": "https://rdap.identitydigital.services/rdap",
  "land": "https://rdap.identitydigital.services/rdap",
  "lawyer": "https://rdap.identitydigital.services/rdap",
  "lease": "https://rdap.identitydigital.services/rdap",
  "legal": "https://rdap.identitydigital.services/rdap",
  "lgbt": "https://rdap.identitydigital.services/rdap",
  "life": "https://rdap.identitydigital.services/rdap",
  "lighting": "https://rdap.identitydigital.services/rdap",
  "limited": "https://rdap.identitydigital.services/rdap",
  "limo": "https://rdap.identitydigital.services/rdap",
  "live": "https://rdap.identitydigital.services/rdap",
  "llc": "https://rdap.identitydigital.services/rdap",
  "loans": "https://rdap.identitydigital.services/rdap",
  "lotto": "https://rdap.identitydigital.services/rdap",
  "ltd": "https://rdap.identitydigital.services/rdap",
  "ltda": "https://rdap.identitydigital.services/rdap",
  "maison": "https://rdap.identitydigital.services/rdap",
  "management": "https://rdap.identitydigital.services/rdap",
  "market": "https://rdap.identitydigital.services/rdap",
  "marketing": "https://rdap.identitydigital.services/rdap",
  "mba": "https://rdap.identitydigital.services/rdap",
  "media": "https://rdap.identitydigital.services/rdap",
  "memorial": "https://rdap.identitydigital.services/rdap",
  "moda": "https://rdap.identitydigital.services/rdap",
  "money": "https://rdap.identitydigital.services/rdap",
  "mortgage": "https://rdap.identitydigital.services/rdap",
  "movie": "https://rdap.identitydigital.services/rdap",
  "navy": "https://rdap.identitydigital.services/rdap",
  "network": "https://rdap.identitydigital.services/rdap",
  "news": "https://rdap.identitydigital.services/rdap",
  "ninja": "https://rdap.identitydigital.services/rdap",
  "onl": "https://rdap.identitydigital.services/rdap",
  "organic": "https://rdap.identitydigital.services/rdap",
  "partners": "https://rdap.identitydigital.services/rdap",
  "parts": "https://rdap.identitydigital.services/rdap",
  "pet": "https://rdap.identitydigital.services/rdap",
  "photography": "https://rdap.identitydigital.services/rdap",
  "photos": "https://rdap.identitydigital.services/rdap",
  "pictures": "https://rdap.identitydigital.services/rdap",
  "pink": "https://rdap.identitydigital.services/rdap",
  "pizza": "https://rdap.identitydigital.services/rdap",
  "place": "https://rdap.identitydigital.services/rdap",
  "plumbing": "https://rdap.identitydigital.services/rdap",
  "plus": "https://rdap.identitydigital.services/rdap",
  "poker": "https://rdap.identitydigital.services/rdap",
  "productions": "https://rdap.identitydigital.services/rdap",
  "promo": "https://rdap.identitydigital.services/rdap",
  "properties": "https://rdap.identitydigital.services/rdap",
  "pub": "https://rdap.identitydigital.services/rdap",
  "recipes": "https://rdap.identitydigital.services/rdap",
  "red": "https://rdap.identitydigital.services/rdap",
  "rehab": "https://rdap.identitydigital.services/rdap",
  "reise": "https://rdap.identitydigital.services/rdap",
  "reisen": "https://rdap.identitydigital.services/rdap",
  "rentals": "https://rdap.identitydigital.services/rdap",
  "repair": "https://rdap.identitydigital.services/rdap",
  "report": "https://rdap.identitydigital.services/rdap",
  "republican": "https://rdap.identitydigital.services/rdap",
  "restaurant": "https://rdap.identitydigital.services/rdap",
  "reviews": "https://rdap.identitydigital.services/rdap",
  "rip": "https://rdap.identitydigital.services/rdap",
  "rocks": "https://rdap.identitydigital.services/rdap",
  "run": "https://rdap.identitydigital.services/rdap",
  "sale": "https://rdap.identitydigital.services/rdap",
  "salon": "https://rdap.identitydigital.services/rdap",
  "sarl": "https://rdap.identitydigital.services/rdap",
  "school": "https://rdap.identitydigital.services/rdap",
  "schule": "https://rdap.identitydigital.services/rdap",
  "services": "https://rdap.identitydigital.services/rdap",
  "shoes": "https://rdap.identitydigital.services/rdap",
  "shopping": "https://rdap.identitydigital.services/rdap",
  "show": "https://rdap.identitydigital.services/rdap",
  "singles": "https://rdap.identitydigital.services/rdap",
  "ski": "https://rdap.identitydigital.services/rdap",
  "soccer": "https://rdap.identitydigital.services/rdap",
  "social": "https://rdap.identitydigital.services/rdap",
  "software": "https://rdap.identitydigital.services/rdap",
  "solar": "https://rdap.identitydigital.services/rdap",
  "solutions": "https://rdap.identitydigital.services/rdap",
  "spa": "https://rdap.identitydigital.services/rdap",
  "srl": "https://rdap.identitydigital.services/rdap",
  "studio": "https://rdap.identitydigital.services/rdap",
  "style": "https://rdap.identitydigital.services/rdap",
  "supplies": "https://rdap.identitydigital.services/rdap",
  "supply": "https://rdap.identitydigital.services/rdap",
  "support": "https://rdap.identitydigital.services/rdap",
  "surgery": "https://rdap.identitydigital.services/rdap",
  "systems": "https://rdap.identitydigital.services/rdap",
  "tax": "https://rdap.identitydigital.services/rdap",
  "taxi": "https://rdap.identitydigital.services/rdap",
  "team": "https://rdap.identitydigital.services/rdap",
  "technology": "https://rdap.identitydigital.services/rdap",
  "tennis": "https://rdap.identitydigital.services/rdap",
  "theater": "https://rdap.identitydigital.services/rdap",
  "tienda": "https://rdap.identitydigital.services/rdap",
  "tips": "https://rdap.identitydigital.services/rdap",
  "tires": "https://rdap.identitydigital.services/rdap",
  "today": "https://rdap.identitydigital.services/rdap",
  "tools": "https://rdap.identitydigital.services/rdap",
  "tours": "https://rdap.identitydigital.services/rdap",
  "town": "https://rdap.identitydigital.services/rdap",
  "toys": "https://rdap.identitydigital.services/rdap",
  "trading": "https://rdap.identitydigital.services/rdap",
  "training": "https://rdap.identitydigital.services/rdap",
  "university": "https://rdap.identitydigital.services/rdap",
  "vacations": "https://rdap.identitydigital.services/rdap",
  "ventures": "https://rdap.identitydigital.services/rdap",
  "vet": "https://rdap.identitydigital.services/rdap",
  "viajes": "https://rdap.identitydigital.services/rdap",
  "video": "https://rdap.identitydigital.services/rdap",
  "villas": "https://rdap.identitydigital.services/rdap",
  "vin": "https://rdap.identitydigital.services/rdap",
  "vision": "https://rdap.identitydigital.services/rdap",
  "vote": "https://rdap.identitydigital.services/rdap",
  "voto": "https://rdap.identitydigital.services/rdap",
  "voyage": "https://rdap.identitydigital.services/rdap",
  "watch": "https://rdap.identitydigital.services/rdap",
  "watches": "https://rdap.identitydigital.services/rdap",
  "wine": "https://rdap.identitydigital.services/rdap",
  "works": "https://rdap.identitydigital.services/rdap",
  "world": "https://rdap.identitydigital.services/rdap",
  "wtf": "https://rdap.identitydigital.services/rdap",
  "zone": "https://rdap.identitydigital.services/rdap",

  // ========== GMO Registry gTLDs ==========
  "bridgestone": "https://rdap.gmoregistry.net/rdap",
  "brother": "https://rdap.gmoregistry.net/rdap",
  "canon": "https://rdap.gmoregistry.net/rdap",
  "datsun": "https://rdap.gmoregistry.net/rdap",
  "dnp": "https://rdap.gmoregistry.net/rdap",
  "epson": "https://rdap.gmoregistry.net/rdap",
  "firestone": "https://rdap.gmoregistry.net/rdap",
  "fujitsu": "https://rdap.gmoregistry.net/rdap",
  "ggee": "https://rdap.gmoregistry.net/rdap",
  "gmo": "https://rdap.gmoregistry.net/rdap",
  "goldpoint": "https://rdap.gmoregistry.net/rdap",
  "goo": "https://rdap.gmoregistry.net/rdap",
  "hisamitsu": "https://rdap.gmoregistry.net/rdap",
  "hitachi": "https://rdap.gmoregistry.net/rdap",
  "honda": "https://rdap.gmoregistry.net/rdap",
  "hyundai": "https://rdap.gmoregistry.net/rdap",
  "infiniti": "https://rdap.gmoregistry.net/rdap",
  "jcb": "https://rdap.gmoregistry.net/rdap",
  "kddi": "https://rdap.gmoregistry.net/rdap",
  "kia": "https://rdap.gmoregistry.net/rdap",
  "komatsu": "https://rdap.gmoregistry.net/rdap",
  "kyoto": "https://rdap.gmoregistry.net/rdap",
  "lexus": "https://rdap.gmoregistry.net/rdap",
  "lotte": "https://rdap.gmoregistry.net/rdap",
  "mitsubishi": "https://rdap.gmoregistry.net/rdap",
  "nagoya": "https://rdap.gmoregistry.net/rdap",
  "nec": "https://rdap.gmoregistry.net/rdap",
  "nhk": "https://rdap.gmoregistry.net/rdap",
  "nico": "https://rdap.gmoregistry.net/rdap",
  "nissan": "https://rdap.gmoregistry.net/rdap",
  "okinawa": "https://rdap.gmoregistry.net/rdap",
  "otsuka": "https://rdap.gmoregistry.net/rdap",
  "panasonic": "https://rdap.gmoregistry.net/rdap",
  "playstation": "https://rdap.gmoregistry.net/rdap",
  "ricoh": "https://rdap.gmoregistry.net/rdap",
  "ryukyu": "https://rdap.gmoregistry.net/rdap",
  "sharp": "https://rdap.gmoregistry.net/rdap",
  "shop": "https://rdap.gmoregistry.net/rdap",
  "softbank": "https://rdap.gmoregistry.net/rdap",
  "sony": "https://rdap.gmoregistry.net/rdap",
  "suzuki": "https://rdap.gmoregistry.net/rdap",
  "tokyo": "https://rdap.gmoregistry.net/rdap",
  "toray": "https://rdap.gmoregistry.net/rdap",
  "toshiba": "https://rdap.gmoregistry.net/rdap",
  "toyota": "https://rdap.gmoregistry.net/rdap",
  "yodobashi": "https://rdap.gmoregistry.net/rdap",
  "yokohama": "https://rdap.gmoregistry.net/rdap",

  // ========== Nominet gTLDs ==========
  "abbvie": "https://rdap.nominet.uk/abbvie",
  "amazon": "https://rdap.nominet.uk/amazon",
  "audible": "https://rdap.nominet.uk/audible",
  "author": "https://rdap.nominet.uk/author",
  "aws": "https://rdap.nominet.uk/aws",
  "azure": "https://rdap.nominet.uk/azure",
  "bbc": "https://rdap.nominet.uk/bbc",
  "bbva": "https://rdap.nominet.uk/bbva",
  "bing": "https://rdap.nominet.uk/bing",
  "book": "https://rdap.nominet.uk/book",
  "bot": "https://rdap.nominet.uk/bot",
  "broadway": "https://rdap.nominet.uk/broadway",
  "buy": "https://rdap.nominet.uk/buy",
  "call": "https://rdap.nominet.uk/call",
  "career": "https://rdap.nominet.uk/career",
  "circle": "https://rdap.nominet.uk/circle",
  "cymru": "https://rdap.nominet.uk/cymru",
  "deal": "https://rdap.nominet.uk/deal",
  "desi": "https://rdap.nominet.uk/desi",
  "fast": "https://rdap.nominet.uk/fast",
  "fire": "https://rdap.nominet.uk/fire",
  "free": "https://rdap.nominet.uk/free",
  "gop": "https://rdap.nominet.uk/gop",
  "got": "https://rdap.nominet.uk/got",
  "gucci": "https://rdap.nominet.uk/gucci",
  "hot": "https://rdap.nominet.uk/hot",
  "hotmail": "https://rdap.nominet.uk/hotmail",
  "ieee": "https://rdap.nominet.uk/ieee",
  "imdb": "https://rdap.nominet.uk/imdb",
  "jot": "https://rdap.nominet.uk/jot",
  "joy": "https://rdap.nominet.uk/joy",
  "kindle": "https://rdap.nominet.uk/kindle",
  "like": "https://rdap.nominet.uk/like",
  "locus": "https://rdap.nominet.uk/locus",
  "med": "https://rdap.nominet.uk/med",
  "microsoft": "https://rdap.nominet.uk/microsoft",
  "moi": "https://rdap.nominet.uk/moi",
  "mtn": "https://rdap.nominet.uk/mtn",
  "now": "https://rdap.nominet.uk/now",
  "nowruz": "https://rdap.nominet.uk/nowruz",
  "office": "https://rdap.nominet.uk/office",
  "omega": "https://rdap.nominet.uk/omega",
  "pars": "https://rdap.nominet.uk/pars",
  "pay": "https://rdap.nominet.uk/pay",
  "pharmacy": "https://rdap.nominet.uk/pharmacy",
  "pin": "https://rdap.nominet.uk/pin",
  "pioneer": "https://rdap.nominet.uk/pioneer",
  "prime": "https://rdap.nominet.uk/prime",
  "read": "https://rdap.nominet.uk/read",
  "realestate": "https://rdap.nominet.uk/realestate",
  "realtor": "https://rdap.nominet.uk/realtor",
  "room": "https://rdap.nominet.uk/room",
  "safe": "https://rdap.nominet.uk/safe",
  "save": "https://rdap.nominet.uk/save",
  "secure": "https://rdap.nominet.uk/secure",
  "shell": "https://rdap.nominet.uk/shell",
  "shia": "https://rdap.nominet.uk/shia",
  "silk": "https://rdap.nominet.uk/silk",
  "sky": "https://rdap.nominet.uk/sky",
  "skype": "https://rdap.nominet.uk/skype",
  "smile": "https://rdap.nominet.uk/smile",
  "spot": "https://rdap.nominet.uk/spot",
  "swatch": "https://rdap.nominet.uk/swatch",
  "talk": "https://rdap.nominet.uk/talk",
  "tunes": "https://rdap.nominet.uk/tunes",
  "tushu": "https://rdap.nominet.uk/tushu",
  "virgin": "https://rdap.nominet.uk/virgin",
  "wales": "https://rdap.nominet.uk/wales",
  "wanggou": "https://rdap.nominet.uk/wanggou",
  "wed": "https://rdap.nominet.uk/wed",
  "windows": "https://rdap.nominet.uk/windows",
  "wow": "https://rdap.nominet.uk/wow",
  "xbox": "https://rdap.nominet.uk/xbox",
  "you": "https://rdap.nominet.uk/you",
  "zappos": "https://rdap.nominet.uk/zappos",
  "yamaxun": "https://rdap.nominet.uk/yamaxun",

  // ========== 其他注册局 gTLDs ==========
  "aaa": "https://rdap.nic.aaa",
  "aarp": "https://rdap.nic.aarp",
  "able": "https://rdap.nic.able",
  "abogado": "https://rdap.nic.abogado",
  "abudhabi": "https://rdap.nic.abudhabi",
  "accountant": "https://rdap.nic.accountant",
  "adult": "https://rdap.nic.adult",
  "africa": "https://rdap.nic.africa/rdap",
  "alsace": "https://rdap.nic.alsace",
  "amsterdam": "https://rdap.nic.amsterdam",
  "arab": "https://rdap.nic.arab",
  "bank": "https://rdap.nic.bank",
  "barcelona": "https://rdap.nic.barcelona",
  "baseball": "https://rdap.nic.baseball",
  "basketball": "https://rdap.nic.basketball",
  "bayern": "https://rdap.nic.bayern",
  "beer": "https://rdap.nic.beer",
  "berlin": "https://rdap.nic.berlin/v1",
  "bible": "https://rdap.nic.bible",
  "bid": "https://rdap.nic.bid",
  "blackfriday": "https://rdap.nic.blackfriday",
  "blog": "https://rdap.blog.fury.ca/rdap",
  "booking": "https://rdap.nic.booking",
  "boston": "https://rdap.nic.boston",
  "brussels": "https://rdap.nic.brussels",
  "buzz": "https://rdap.nic.buzz",
  "bzh": "https://rdap.nic.bzh",
  "capetown": "https://rdap.nic.capetown/rdap",
  "casa": "https://rdap.nic.casa",
  "catholic": "https://rdap.nic.catholic",
  "chase": "https://rdap.nic.chase",
  "cisco": "https://rdap.nic.cisco",
  "citi": "https://rdap.nic.citi",
  "club": "https://rdap.nic.club",
  "cloud": "https://rdap.registry.cloud/rdap",
  "cooking": "https://rdap.nic.cooking",
  "corsica": "https://rdap.nic.corsica",
  "courses": "https://rdap.nic.courses",
  "cpa": "https://rdap.nic.cpa",
  "cricket": "https://rdap.nic.cricket",
  "crown": "https://rdap.crown.fury.ca/rdap",
  "date": "https://rdap.nic.date",
  "dell": "https://rdap.nic.dell",
  "design": "https://rdap.nic.design",
  "download": "https://rdap.nic.download",
  "dubai": "https://rdap.nic.dubai",
  "dupont": "https://rdap.nic.dupont",
  "durban": "https://rdap.nic.durban/rdap",
  "earth": "https://rdap.nic.earth",
  "eco": "https://rdap.eco.fury.ca/rdap",
  "eus": "https://rdap.nic.eus",
  "faith": "https://rdap.nic.faith",
  "fashion": "https://rdap.nic.fashion",
  "film": "https://rdap.nic.film",
  "fishing": "https://rdap.nic.fishing",
  "fit": "https://rdap.nic.fit",
  "ford": "https://rdap.nic.ford",
  "fox": "https://rdap.nic.fox",
  "gal": "https://rdap.nic.gal",
  "garden": "https://rdap.nic.garden",
  "gay": "https://rdap.nic.gay",
  "gdn": "https://rdap.nic.gdn",
  "gmx": "https://rdap.nic.gmx",
  "godaddy": "https://rdap.nic.godaddy",
  "hamburg": "https://rdap.nic.hamburg/v1",
  "hbo": "https://rdap.nic.hbo",
  "health": "https://rdap.nic.health",
  "horse": "https://rdap.nic.horse",
  "hotels": "https://rdap.nic.hotels",
  "hsbc": "https://rdap.nic.hsbc",
  "hyatt": "https://rdap.nic.hyatt",
  "ibm": "https://rdap.nic.ibm",
  "ink": "https://rdap.nic.ink",
  "insurance": "https://rdap.nic.insurance",
  "joburg": "https://rdap.nic.joburg/rdap",
  "jpmorgan": "https://rdap.nic.jpmorgan",
  "kiwi": "https://rdap.kiwi.fury.ca/rdap",
  "kpmg": "https://rdap.nic.kpmg",
  "krd": "https://rdap.nic.krd",
  "law": "https://rdap.nic.law",
  "lincoln": "https://rdap.nic.lincoln",
  "loan": "https://rdap.nic.loan",
  "love": "https://rdap.registry.love/rdap",
  "luxe": "https://rdap.nic.luxe",
  "madrid": "https://rdap.nic.madrid",
  "melbourne": "https://rdap.nic.melbourne",
  "men": "https://rdap.nic.men",
  "menu": "https://rdap.nic.menu",
  "miami": "https://rdap.nic.miami",
  "mlb": "https://rdap.nic.mlb",
  "mls": "https://rdap.mls.fury.ca/rdap",
  "moe": "https://rdap.nic.moe",
  "moscow": "https://rdap.flexireg.net",
  "music": "https://rdap.registryservices.music/rdap",
  "nba": "https://rdap.nic.nba",
  "netflix": "https://rdap.nic.netflix",
  "nyc": "https://rdap.nic.nyc",
  "one": "https://rdap.nic.one",
  "paris": "https://rdap.nic.paris",
  "party": "https://rdap.nic.party",
  "quebec": "https://rdap.nic.quebec",
  "racing": "https://rdap.nic.racing",
  "review": "https://rdap.nic.review",
  "rio": "https://rdap.gtlds.nic.br",
  "roma": "https://rdap.nic.roma",
  "samsung": "https://nic.samsung/rdap",
  "science": "https://rdap.nic.science",
  "scot": "https://rdap.nic.scot",
  "sex": "https://rdap.nic.sex",
  "sport": "https://rdap.nic.sport",
  "stockholm": "https://rdap.identitydigital.services/rdap",
  "stream": "https://rdap.nic.stream",
  "study": "https://rdap.nic.study",
  "sucks": "https://rdap.nic.sucks",
  "surf": "https://rdap.nic.surf",
  "swiss": "https://rdap.nic.swiss",
  "sydney": "https://rdap.nic.sydney",
  "taipei": "https://rdap.nic.taipei",
  "target": "https://rdap.nic.target",
  "tattoo": "https://rdap.nic.tattoo",
  "top": "https://rdap.zdnsgtld.com/top",
  "trade": "https://rdap.nic.trade",
  "tube": "https://rdap.nic.tube",
  "vegas": "https://rdap.nic.vegas",
  "versicherung": "https://rdap.nic.versicherung/v1",
  "vip": "https://rdap.nic.vip",
  "vlaanderen": "https://rdap.nic.vlaanderen",
  "vodka": "https://rdap.nic.vodka",
  "voting": "https://rdap.nic.voting",
  "walmart": "https://rdap.nic.walmart",
  "weather": "https://rdap.nic.weather",
  "webcam": "https://rdap.nic.webcam",
  "wedding": "https://rdap.nic.wedding",
  "wien": "https://rdap.ryce-rsp.com/rdap",
  "wiki": "https://rdap.nic.wiki",
  "win": "https://rdap.nic.win",
  "work": "https://rdap.nic.work",
  "xerox": "https://rdap.nic.xerox",
  "yandex": "https://rdap.nic.yandex/rdap",
  "yoga": "https://rdap.nic.yoga",

  // ========== 中文/IDN TLDs ==========
  "xn--kpry57d": "https://ccrdap.twnic.tw/taiwan",
  "xn--mxtq1m": "https://rdap.twnic.tw/rdap",
  "xn--55qw42g": "https://rdap.conac.cn",
  "xn--zfr164b": "https://rdap.conac.cn",
  "xn--1qqw23a": "https://restwhois.ngtld.cn",
  "xn--55qx5d": "https://restwhois.ngtld.cn",
  "xn--io0a7i": "https://restwhois.ngtld.cn",
  "xn--xhq521b": "https://restwhois.ngtld.cn",
  "xn--3bst00m": "https://rdap.zdnsgtld.com/xn--3bst00m",
  "xn--6qq986b3xl": "https://rdap.zdnsgtld.com/xn--6qq986b3xl",
  "xn--9et52u": "https://rdap.zdnsgtld.com/xn--9et52u",
  "xn--czr694b": "https://rdap.zdnsgtld.com/xn--czr694b",
  "xn--czru2d": "https://rdap.zdnsgtld.com/xn--czru2d",
  "xn--fiq64b": "https://rdap.zdnsgtld.com/xn--fiq64b",
  "xn--otu796d": "https://rdap.zdnsgtld.com/xn--otu796d",
  "xn--ses554g": "https://rdap.zdnsgtld.com/xn--ses554g",
  "xn--45q11c": "https://rdap.zdnsgtld.com/XN--45Q11C",
  "xn--efvy88h": "https://rdap.zdnsgtld.com/XN--EFVY88H",
  "xn--fiq228c5hs": "https://rdap.teleinfo.cn/xn--fiq228c5hs",
  "xn--kput3i": "https://rdap.teleinfo.cn/xn--kput3i",
  "xn--nyqy26a": "https://rdap.teleinfo.cn/xn--nyqy26a",
  "xn--rhqv96g": "https://rdap.teleinfo.cn/xn--rhqv96g",
  "xn--vuq861b": "https://rdap.teleinfo.cn",

  // ========== 韩文 TLDs ==========
  "xn--3e0b707e": "https://rdap.kisa.or.kr",
  "xn--t60b56a": "https://tld-rdap.verisign.com/xn--t60b56a/v1",
  "xn--cg4bki": "https://nic.samsung/rdap",

  // ========== 俄文/斯拉夫 TLDs ==========
  "xn--p1ai": "https://rdap.tcinet.ru",
  "xn--80adxhks": "https://rdap.flexireg.net",
  "xn--c1avg": "https://rdap.publicinterestregistry.org/rdap",
  "xn--p1acf": "https://rdap.nic.xn--p1acf",
  "xn--80aswg": "https://rdap.nic.xn--80aswg",
  "xn--80aqecdr1a": "https://rdap.nic.xn--80aqecdr1a",
  "xn--80asehdb": "https://rdap.nic.xn--80asehdb",
  "xn--d1acj3b": "https://whois.nic.xn--d1acj3b/rdap",

  // ========== 阿拉伯文 TLDs ==========
  "xn--mgba3a3ejt": "https://rdap.nic.xn--mgba3a3ejt",
  "xn--mgba7c0bbn0a": "https://rdap.nic.xn--mgba7c0bbn0a",
  "xn--mgbab2bd": "https://rdap.nic.xn--mgbab2bd",
  "xn--mgbca7dzdo": "https://rdap.nic.xn--mgbca7dzdo",
  "xn--mgbi4ecexp": "https://rdap.nic.xn--mgbi4ecexp",
  "xn--ngbc5azd": "https://rdap.nic.xn--ngbc5azd",
  "xn--ngbrx": "https://rdap.nic.xn--ngbrx",

  // ========== 其他 IDN TLDs ==========
  "xn--o3cw4h": "https://rdap.thains.co.th",
  "xn--i1b6b1a6a2e": "https://rdap.publicinterestregistry.org/rdap",
  "xn--nqv7f": "https://rdap.publicinterestregistry.org/rdap",
  "xn--nqv7fs00ema": "https://rdap.publicinterestregistry.org/rdap",
  "xn--g2xx48c": "https://rdap.nic.xn--g2xx48c",
  "xn--kcrx77d1x4a": "https://rdap.nic.xn--kcrx77d1x4a",
  "xn--tiq49xqyj": "https://rdap.nic.xn--tiq49xqyj",

  // ========== Verisign gTLDs ==========
  "comsec": "https://tld-rdap.verisign.com/comsec/v1",
  "verisign": "https://tld-rdap.verisign.com/verisign/v1",
  "xn--11b4c3d": "https://tld-rdap.verisign.com/xn--11b4c3d/v1",
  "xn--3pxu8k": "https://tld-rdap.verisign.com/xn--3pxu8k/v1",
  "xn--42c2d9a": "https://tld-rdap.verisign.com/xn--42c2d9a/v1",
  "xn--9dbq2a": "https://tld-rdap.verisign.com/xn--9dbq2a/v1",
  "xn--c2br7g": "https://tld-rdap.verisign.com/xn--c2br7g/v1",
  "xn--fhbei": "https://tld-rdap.verisign.com/xn--fhbei/v1",
  "xn--j1aef": "https://tld-rdap.verisign.com/xn--j1aef/v1",
  "xn--mk1bu44c": "https://tld-rdap.verisign.com/xn--mk1bu44c/v1",
  "xn--pssy2u": "https://tld-rdap.verisign.com/xn--pssy2u/v1",
  "xn--tckwe": "https://tld-rdap.verisign.com/xn--tckwe/v1",

  // ========== ZDNS gTLDs (中国) ==========
  "baidu": "https://rdap.zdnsgtld.com/baidu",
  "citic": "https://rdap.zdnsgtld.com/citic",
  "icbc": "https://rdap.zdnsgtld.com/icbc",
  "ren": "https://rdap.zdnsgtld.com/ren",
  "sohu": "https://rdap.zdnsgtld.com/sohu",
  "unicom": "https://rdap.zdnsgtld.com/unicom",
  "wang": "https://rdap.zdnsgtld.com/wang",
  "xn--30rr7y": "https://rdap.zdnsgtld.com/xn--30rr7y",
  "xn--8y0a063a": "https://rdap.zdnsgtld.com/xn--8y0a063a",
  "xn--hxt814e": "https://rdap.zdnsgtld.com/xn--hxt814e",
  "xn--imr513n": "https://rdap.zdnsgtld.com/xn--imr513n",

  // ========== Tucows Registry ==========
  "click": "https://rdap.tucowsregistry.net/rdap",
  "country": "https://rdap.tucowsregistry.net/rdap",
  "diy": "https://rdap.tucowsregistry.net/rdap",
  "food": "https://rdap.tucowsregistry.net/rdap",
  "gift": "https://rdap.tucowsregistry.net/rdap",
  "hiv": "https://rdap.tucowsregistry.net/rdap",
  "lifestyle": "https://rdap.tucowsregistry.net/rdap",
  "link": "https://rdap.tucowsregistry.net/rdap",
  "living": "https://rdap.tucowsregistry.net/rdap",
  "property": "https://rdap.tucowsregistry.net/rdap",
  "sexy": "https://rdap.tucowsregistry.net/rdap",
  "trust": "https://rdap.tucowsregistry.net/rdap",
  "vana": "https://rdap.tucowsregistry.net/rdap",

  // ========== PIR (Public Interest Registry) ==========
  "charity": "https://rdap.publicinterestregistry.org/rdap",
  "foundation": "https://rdap.publicinterestregistry.org/rdap",
  "gives": "https://rdap.publicinterestregistry.org/rdap",
  "giving": "https://rdap.publicinterestregistry.org/rdap",
  "ngo": "https://rdap.publicinterestregistry.org/rdap",
  "ong": "https://rdap.publicinterestregistry.org/rdap",

  // ========== Registry.bar ==========
  "bar": "https://rdap.registry.bar/rdap",
  "rest": "https://rdap.registry.bar/rdap",

  // ========== Registry.click ==========
  "feedback": "https://rdap.registry.click/rdap",
  "forum": "https://rdap.registry.click/rdap",
  "observer": "https://rdap.registry.click/rdap",
  "pid": "https://rdap.registry.click/rdap",
  "realty": "https://rdap.registry.click/rdap",

  // ========== Registry.hiphop ==========
  "hiphop": "https://rdap.registry.hiphop/rdap",

  // ========== RYCE-RSP ==========
  "cologne": "https://rdap.ryce-rsp.com/rdap",
  "koeln": "https://rdap.ryce-rsp.com/rdap",
  "tirol": "https://rdap.ryce-rsp.com/rdap",

  // ========== Mobile Registry ==========
  "blockbuster": "https://rdap.mobile-registry.com/rdap",
  "data": "https://rdap.mobile-registry.com/rdap",
  "dish": "https://rdap.mobile-registry.com/rdap",
  "dot": "https://rdap.mobile-registry.com/rdap",
  "dtv": "https://rdap.mobile-registry.com/rdap",
  "dvr": "https://rdap.mobile-registry.com/rdap",
  "latino": "https://rdap.mobile-registry.com/rdap",
  "mobile": "https://rdap.mobile-registry.com/rdap",
  "ollo": "https://rdap.mobile-registry.com/rdap",
  "ott": "https://rdap.mobile-registry.com/rdap",
  "phone": "https://rdap.mobile-registry.com/rdap",
  "sling": "https://rdap.mobile-registry.com/rdap",

  // ========== 其他特殊 gTLDs ==========
  "creditunion": "https://rdap.registry.coop/rdap",
  "tatar": "https://whois.nic.tatar/rdap",
  "mtr": "https://whois.nic.mtr/rdap",
};

/**
 * 获取域名对应的RDAP服务器
 */
export function getRdapServer(domain: string): string | null {
  const parts = domain.toLowerCase().split('.');
  const tld = parts[parts.length - 1];
  return RDAP_SERVERS[tld] || null;
}

/**
 * 获取域名对应的WHOIS服务器
 */
export function getWhoisServer(domain: string): string | null {
  const parts = domain.toLowerCase().split('.');
  const tld = parts[parts.length - 1];
  return WHOIS_SERVERS[tld] || null;
}

/**
 * 检查TLD是否支持查询
 */
export function isTldSupported(tld: string): boolean {
  const normalizedTld = tld.toLowerCase().replace(/^\./, '');
  return RDAP_SERVERS[normalizedTld] !== undefined || WHOIS_SERVERS[normalizedTld] !== undefined;
}

/**
 * 获取支持的TLD总数
 */
export function getSupportedTldCount(): number {
  const allTlds = new Set([...Object.keys(RDAP_SERVERS), ...Object.keys(WHOIS_SERVERS)]);
  return allTlds.size;
}

/**
 * 获取所有支持的TLD列表
 */
export function getAllSupportedTlds(): string[] {
  const allTlds = new Set([...Object.keys(RDAP_SERVERS), ...Object.keys(WHOIS_SERVERS)]);
  return [...allTlds].sort();
}

/**
 * 获取TLD的查询支持信息
 */
export function getTldSupportInfo(tld: string): { rdap: string | null; whois: string | null } {
  const normalizedTld = tld.toLowerCase().replace(/^\./, '');
  return {
    rdap: RDAP_SERVERS[normalizedTld] || null,
    whois: WHOIS_SERVERS[normalizedTld] || null
  };
}
